### ISSUE TITLE
Malformed elements in the statistics object for the player endpoint

### ISSUE THREAD

**Issue by talle117** [HypixelDev/PublicAPI#100]
The following list contains elements that have spaces where underscores should be placed. There are also a few that include non alphanumeric characters. These elements cause a few issues while working with the Hypixel API, would be greatly appreciated if these were fixed ASAP. 

- Skywars:
  - "quickjoin_uses_Festive Shire"
  - "quickjoin_uses_Festive Tribute"
  - "quickjoin_uses_Onionring 2017"
  - "quickjoin_uses_Onionring 2"
  - "quickjoin_uses_Firelink Shrine"
  - "quickjoin_uses_Desserted Islands"
  - "quickjoin_uses_Oberon Towers" 

- UHC Champions:
  - "heads_eaten_red vs blue"
  - "kills_red vs blue"
  - "deaths_red vs blue"
  - "wins_red vs blue"
  - "heads_eaten_vanilla doubles"
  - "deaths_vanilla doubles"
  - "kills_vanilla doubles"
  - "wins_vanilla doubles"
  - "kills_no diamonds"
  - "deaths_no diamonds"
  - "heads_eaten_no diamonds"
  - "wins_no diamonds"
  - "heads_eaten_duo brawl"
  - "kills_duo brawl"
  - "deaths_duo brawl"
  - "wins_duo brawl"

- Quake:
  - "votes_Lost World"
  - "votes_Apex II"
  - "messageOthers' Kills/deaths"
  - "messageMulti-kill" *Should be _ not - 
  - "messageYour Kills"
  - "messageCoin Messages"
  - "messagePowerup Collections"
  - "messageYour Deaths"

- Walls3
  - "votes_Forsaken "

- Bedwars:
  - "eight_two_permanent _items_purchased_bedwars"
  - "permanent _items_purchased_bedwars"
  - "four_three_permanent _items_purchased_bedwars"
  - "four_four_permanent _items_purchased_bedwars"
  - "eight_one_permanent _items_purchased_bedwars"
  - "eight_two_ultimate_permanent _items_purchased_bedwars"
  - "four_four_ultimate_permanent _items_purchased_bedwars"
  - "castle_permanent _items_purchased_bedwars"
  - "four_four_rush_permanent _items_purchased_bedwars"
  - "eight_one_ultimate_permanent _items_purchased_bedwars"
  - "eight_one_rush_permanent _items_purchased_bedwars"
  - "quickjoin_uses_Wrapped Up"
  - "four_four_lucky_permanent _items_purchased_bedwars"

- Murder Mystery:
  - "quickjoin_uses_Ancient Tomb"
  - "quickjoin_uses_Gold Rush" 
  - "quickjoin_uses_Hypixel World"
  - "quickjoin_uses_Cruise Ship"
  - "quickjoin_uses_San Peratico"
  - "quickjoin_uses_Widow's Den"
  - "quickjoin_uses_Archives Top Floor"
  - "quickjoin_uses_Easter World"

- Build Battle:
  - "votes_Christmas tree"
  - "votes_Candy Cane"
  - "votes_Starry Night"
  - "votes_Fishing Rod"
  - "votes_Top hat"

- MCGO:
  - "game_wins_melon factory"

- PaintBall:
  - "votes_Oh Canada!"

- Hunger Games:
  - "votes_Caelum v2"
  - "votes_Despair v1"
  - "shadow knight"
  - "votes_Mirador Basin"
  - "hype train"
  - "votes_Aelin's Tower"
  - "votes_Docks v1"
  - "Shadow KnightInventory"
  - "Hype TrainInventory"
  - "chests_opened_hype train"
  - "potions_drunk_hype train"
  - "time_played_hype train"
  - "games_played_hype train"
  - "wins_teams_hype train"
  - "damage_taken_hype train"
  - "damage_hype train"
  - "kills_hype train"
  - "potions_thrown_hype train"
  - "arrows_hit_hype train"
  - "arrows_fired_hype train"
  - "time_played_shadow knight"
  - "chests_opened_shadow knight"
  - "arrows_hit_shadow knight"
  - "kills_shadow knight"
  - "damage_taken_shadow knight"
  - "wins_teams_shadow knight"
  - "arrows_fired_shadow knight"
  - "games_played_shadow knight"
  - "potions_thrown_shadow knight"
  - "damage_shadow knight"
  - "potions_drunk_shadow knight"
  - "blocks_traveled_minecart_hype train"
  - "rails_placed_hype train"
  - "wins_hype train"
  - "mobs_spawned_hype train"
  - "wins_shadow knight"
  - "tnt_placed_hype train"
 
- SkyClash:
  - "votes_Shroom Forest"

- TNT Games:
  - "votes_TNT Run (F)"
  - "votes_TNT Run (B)"
  - "votes_Bow Spleef (A)"
  - "votes_Bow Spleef (C)"
  - "votes_Dread Pit"
  - "votes_Ice Fortress"
  - "votes_Forgotten Planet"
  - "votes_Wizards (A)"
  - "votes_The Vale"
  - "votes_Wizards (C)"
  - "votes_Wizards (B)"

**Comment by bshayhoe** [comment]
Hey, just bumping this issue as it is still relevant

**Comment by ConnorLinfoot** [comment]
It's unlikely these values will be changes as they are being used by their respective games still.

**Comment by notWolfxd** [comment]
And how hard would it be to update these values ingame? Maybe when the next patch for each of these games rolls around you can stick a fix for each of these in there?

**Comment by mdashlw** [comment]
Quite unlikely this will get changed, because it doesn't benefit anything and makes more issues than solves:
1: data migration
2: backwards compatibility, so either more data in the database or pre-processing data in the route handler, both are bad
