### ISSUE TITLE
Battle Pass

### ISSUE THREAD

**Issue by Picsou993** [HypixelDev/PublicAPI#102]
Is it possible to add Battle Pass data to the API, like when each tier is reached and what daily quests the player have as the daily missions are differents for everyone.
Also, it should be interesting to know if a player has buy the battle pass.

**Comment by original-codematrix** [comment]
@Plancke, It would be nice to have something like that is there already an REST-API offered which is possible to be implemented?

**Comment by builder-247** [comment]
> Also, it should be interesting to know if a player has buy the battle pass.

For the curious, as a temporary hack you can check if `player.vanityMeta.packages` array has one of the exclusive rewards, such as "cloak_lovely".

**Comment by Picsou993** [comment]
> > Also, it should be interesting to know if a player has buy the battle pass.
> 
> For the curious, as a temporary hack you can check if `player.vanityMeta.packages` array has one of the exclusive rewards, such as "cloak_lovely".

Yes but the player has to reach tier 22 (even if I hope that all players reach tier 100 with the paid battle pass :P)

**Comment by builder-247** [comment]
> > > Also, it should be interesting to know if a player has buy the battle pass.
> > 
> > 
> > For the curious, as a temporary hack you can check if `player.vanityMeta.packages` array has one of the exclusive rewards, such as "cloak_lovely".
> 
> Yes but the player has to reach tier 22 (even if I hope that all players reach tier 100 with the paid battle pass :P)

You could also check the lowest custom reward, it's in the game specific entries though.
