### ISSUE TITLE
API Is off?

### ISSUE THREAD

**Issue by Justin2528** [HypixelDev/PublicAPI#103]
So I tried to use the api.hypixel.net but it's not working. even the commands (my discord bot). is the api off?

**Comment by robere2** [comment]
Please try visiting https://api.hypixel.net/player?key=YOUR_KEY&name=bugfroggy
Do you receive a response? It's working fine for me.

**Comment by Picsou993** [comment]
The API was offline for a moment due to an invalid SSL certificate. It is now fixed.
