### ISSUE TITLE
Documentation for gameCounts endpoint

### ISSUE THREAD

**Issue by GamingGeek** [HypixelDev/PublicAPI#104]
Hey, I was planning on integrating the gameCounts endpoint into my Discord bot but I cannot find a list of the games it can show and friendly names, something like [this](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/misc/GameType.md). Not all of the games show up on the API if they don't have any players so I can't even attempt to make it myself.

**Comment by GamingGeek** [comment]
![oof](https://i.imgur.com/Qa7SmCy.png)
Also, this makes no sense to me. Why not just have the players key instead of having PIT under modes and having the exact same value there?

**Comment by robere2** [comment]
> ![oof](https://camo.githubusercontent.com/df792ff6c835cea475dc9aa86edb5ad904bff352/68747470733a2f2f692e696d6775722e636f6d2f516137536d43792e706e67)
> Also, this makes no sense to me. Why not just have the players key instead of having PIT under modes and having the exact same value there?


It's a future-proof design to allow for the addition of more modes to The Pit. At the moment only one exists.
