### ISSUE TITLE
Skyblock API

### ISSUE THREAD

**Issue by MichaelPriebe** [HypixelDev/PublicAPI#105]
I would love to see an API for Skyblock. Since it's more of a MMO type game, along with stats, item and crafting databases would be super cool. Basically to make something like Wowhead for Skyblock.

**Comment by JoeZwet** [comment]
I made a gist of what I think the API should be like.
https://gist.github.com/JoeZwet/304c554cfec9ade02ae155506942c119

**Comment by jamin-bagel** [comment]
> I made a gist of what I think the API should be like.
> https://gist.github.com/JoeZwet/304c554cfec9ade02ae155506942c119

For the most part, it looks pretty good with a lot of useful stats. Worth noting though that endpoints independent of player data (specifically `receipe` and `level`) would probably be better off as JSON files in the [misc documentation folder](https://github.com/HypixelDev/PublicAPI/tree/master/Documentation/misc) with similar metadata (ie Achievements.json, Challenges.json, etc).

**Comment by MichaelPriebe** [comment]
Looks good 😍

**Comment by TrueDimaGaming** [comment]
wow that's pretty good

**Comment by MichaelPriebe** [comment]
Don't forget auctions API too. Undermine Journal anyone?

**Comment by Camzure** [comment]
+1

Are we coming anywhere to this? In my opinion Hypixel should release an API for Skyblock very soon since it has become very popular.

**Comment by MichaelPriebe** [comment]
Any info on this?

**Comment by JoeZwet** [comment]
Nothing yet. most likely because Skyblock is still in the PTL. 
I'm gonna work on some JSON files of the static stuff cause I need it for a mod I'm working on. I'll update here when those are done.

**Comment by MohammadAbuSaleem** [comment]
I will be waiting for such a great thing, once its opened, status web tracker will be ready for all for free from, I will be so happy to contribute for such a great game as a web developer here.

**Comment by ConnorLinfoot** [comment]
We've added some methods for SkyBlock profiles and other pieces of data, this is a first step in the SkyBlock API. They can be found [here](https://github.com/HypixelDev/PublicAPI/tree/master/Documentation/methods/skyblock). 

I'll close this issue but rest assured we do have plans to expand the API further in the future.
