### ISSUE TITLE
WebHooks

### ISSUE THREAD

**Issue by Xiopoly** [HypixelDev/PublicAPI#107]
It would be awesome to add a web-hook option for discord servers such as change logs for certain game modes like sky block.

**Comment by FinalException** [comment]
Add it yourself? This is an API after all.

**Comment by robere2** [comment]
The issue isn't very clear, but webhooks can't be added by anyone. Hypixel developers would have to add it to the API.

**Comment by Dance-Dog** [comment]
For Sky Block at least, you can watch the RSS feed at https://hypixel.net/forums/158/-/index.rss

Some sort of events API would be nice for guild automation though. Maybe a WebSocket API for sending/receiving guild events (chat, kick, join, promote/demote, change settings, party, etc) based on the key owner’s guild perms?

**Comment by FinalException** [comment]
@robere2 
I think hes asking to add an option that takes a Discord webhook and send stuff to it on certain events.

**Comment by ConnorLinfoot** [comment]
As mentioned above this wouldn't be part of an API directly. You can use RSS feeds to monitor the forums or there is a feature within Discord to have the official Hypixel Discord server post announcements into your own Discord server.
