### ISSUE TITLE
api.hypixel.net/watchdogstats endpoint not returning any information.

### ISSUE THREAD

**Issue by talle117** [HypixelDev/PublicAPI#108]
At the start of the month I noticed that my web application was throwing some errors regarding the Hypixel watchdog statistics endpoint. Currently, the endpoint sends a 200 status code with a single JSON response. The response I'm getting is:  `{"success":true}`. Just wondering if this endpoint has been removed or if there is an issue on Hypixel's end.

**Comment by ConnorLinfoot** [comment]
Hey, this has been fixed now. Thanks!
