### ISSUE TITLE
Bad encoding in new Skyblocks Methods: collections and skills

### ISSUE THREAD

**Issue by Picsou993** [HypixelDev/PublicAPI#109]
There are a lot of characters that are not well encoded in the skills methods and 6 characters for the collections with the Speed Talisman/Ring.
![API   Encoding  Skyblock - Collections](https://user-images.githubusercontent.com/33390780/66600019-e0314500-eba4-11e9-9f87-26fec71acd87.PNG)

**Comment by ConnorLinfoot** [comment]
This was an encoding issue and should now be fixed :)
