### ISSUE TITLE
Why are API keys required for static/inexpensive data?

### ISSUE THREAD

**Issue by MichaelPriebe** [HypixelDev/PublicAPI#110]
For example the new Skyblock endpoints, the collections should only update every game update, so performing these endpoints should be relatively inexpensive. Any public-facing usage of these API's will require a wrapper to keep your key private.

**Comment by ConnorLinfoot** [comment]
We'll be introducing a change soon to serve these "semi-static" resources without an API key.

**Comment by MichaelPriebe** [comment]
🎊

**Comment by ConnorLinfoot** [comment]
There is now a `resources` endpoint to retrieve these semi-static resources. More can be found [here](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/resources.md).

**Comment by MichaelPriebe** [comment]
Wonderful and quick!
