### ISSUE TITLE
Suggestion: Getting certain SkyBlock auctions through their UUID

### ISSUE THREAD

**Issue by mat-1** [HypixelDev/PublicAPI#119]
It'd be great if there was some sort of way to get specific SkyBlock auctions that have already ended through the auction UUID.

**Comment by puppy0cam** [comment]
You can keep track of an auction by syncing your application's cached state with the API approximately once per minute and if an auction is missing from the results, then you can be fairly sure that the last cached result of the auction was the final state for it.

**Comment by Bregann** [comment]
+1 would be really beneficial to quickly find the auctions of a specified player
