### ISSUE TITLE
Bug: Auction endpoint doesn't return anything with uuid or playername

### ISSUE THREAD

**Issue by Bregann** [HypixelDev/PublicAPI#121]
When calling the auction endpoint with uuid and playername, it returns nothing: https://i.imgur.com/tWS8ukj.png

The profile returns the correct info

**Comment by puppy0cam** [comment]
Hi there, all filtering options appear to be working correctly!

`uuid` refers to the auction's uuid
`player` refers to the player's uuid
`profile` refers to the profile's uuid

Once an auction has ended, I don't recommend expecting it's information to be available forever, as it's entirely possible that it will be deleted once both the buyer has claimed the item and the seller has claimed the coins.

**Comment by Bregann** [comment]
Aah I thought the uuid field meant the player uuid and the player being player name. All makes sense and works now, thanks for the help :)

**Comment by Bregann** [comment]
Aah I thought the uuid field meant the player uuid and the player being player name. All makes sense and works now, thanks for the help :)
