### ISSUE TITLE
 resources endpoint waiting for browser verification

### ISSUE THREAD

**Issue by Wonderpants** [HypixelDev/PublicAPI#124]
/resources endpoint is cute and all but it's useless if we can't use it. In my opinion it should still require an API key to prevent flood attacks or whatever and perhaps add a special rate limit to it that doesn't stack with the traditional api key rate limits of 120/minute

![image](https://user-images.githubusercontent.com/36536592/67030730-f5a7f100-f107-11e9-950f-749bddc39eac.png)

**Comment by ConnorLinfoot** [comment]
You seem to be making the request over HTTP which could result in this, the API requires SSL.

**Comment by Wonderpants** [comment]
I thought every request to hypixel.net was redirected to HTTPS. Either way, I tried the request again (roughly 2 hours later) and it worked fine, I also tried to force HTTP and it gave me a 301 error code so I doubt it was because of that.

**Comment by ConnorLinfoot** [comment]
The rules within our systems are only configured via the HTTPs domain. If you make a request over HTTP it is possible it can be security checked before the redirect occurs.
