### ISSUE TITLE
Guild member ranks are outdated (Java)

### ISSUE THREAD

**Issue by Qufyy** [HypixelDev/PublicAPI#126]
When requesting a guild member's ranks from the API, it will either be three things ("MEMBER", "OFFICER", "GUILDMASTER") which were the only ranks before the guild update. If a guild member has a rank named differently (e.g. "TRIAL OFFICER") it returns null.

**Comment by puppy0cam** [comment]
Relevant lines:
https://github.com/HypixelDev/PublicAPI/blob/4e17fcb68f69f304b26aaf5b28e09274fa1d55c7/Java/src/main/java/net/hypixel/api/reply/GuildReply.java#L140-L142 https://github.com/HypixelDev/PublicAPI/blob/4e17fcb68f69f304b26aaf5b28e09274fa1d55c7/Java/src/main/java/net/hypixel/api/reply/GuildReply.java#L146 https://github.com/HypixelDev/PublicAPI/blob/4e17fcb68f69f304b26aaf5b28e09274fa1d55c7/Java/src/main/java/net/hypixel/api/reply/GuildReply.java#L153-L155
