### ISSUE TITLE
Make all Skyblock achievements public through API?

### ISSUE THREAD

**Issue by WaningMatrix** [HypixelDev/PublicAPI#128]
Is there a way to get the list of Skyblock achievements? I tried looking up the current API but couldn't find a way to get the Skyblock Achievements.
Any help would be appreciated.

**Comment by mdashlw** [comment]
SkyBlock (as well as all other games) achievements are available in [`resources/achievements` endpoint](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/resources.md)

**Comment by WaningMatrix** [comment]
> SkyBlock (as well as all other games) achievements are available in [`resources/achievements` endpoint](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/resources.md)

Oh, I see. I looking up the player's Skyblock profile and searching for the achievements.

Thanks!
