### ISSUE TITLE
Missing leaders in leaderboards endpoint

### ISSUE THREAD

**Issue by mdashlw** [HypixelDev/PublicAPI#131]
SkyWars leaderboard:
* a leaderboard with path `skywars_rating_a` is missing leaders
* field `stats.SkyWars.skywars_rating_a` doesn't exist in player response

Duels leaderboard:
* leaderboards with paths `trophies_weekly_b` and `trophies_monthly_a` are missing leaders

And for these leaderboards location is always `0,0,0`:
* BEDWARS -> bedwars_level
* BEDWARS -> wins
* BEDWARS -> wins_1
* BEDWARS -> final_kills
* BEDWARS -> final_kills_1
* BUILD_BATTLE -> score
* BUILD_BATTLE -> coins
* BUILD_BATTLE -> wins
* MCGO -> normal_wins_2
* MCGO -> normal_wins_1
* MCGO -> deathmatch_wins_2
* MCGO -> deathmatch_wins_1
* MURDER_MYSTERY -> wins
* MURDER_MYSTERY -> wins_1
* MURDER_MYSTERY -> kills
* MURDER_MYSTERY -> kills_1
* MURDER_MYSTERY -> murderer_kills
* MURDER_MYSTERY -> murderer_kills_1
* DUELS -> trophies_weekly_b
* DUELS -> trophies_monthly_a
* DUELS -> wins_weekly_b
* DUELS -> wins_monthly_a

**Comment by ConnorLinfoot** [comment]
- SkyWars: This was broken due to the data being moved internally, I've now fixed that.
- Duels: I've removed those leaderboards as they are no longer in use.
- Locations are for internal use of legacy systems, so it is correct that a lot are `0,0,0`.
