### ISSUE TITLE
[SkyBlock] "Coins Spent" field in AH stats returns wrong value

### ISSUE THREAD

**Issue by TBlazeWarriorT** [HypixelDev/PublicAPI#133]
![image](https://user-images.githubusercontent.com/25572454/67223780-44a29e80-f406-11e9-904c-4c31b1750789.png)
"Gold/Coins spent" is wrong both in-game and in the API, it returns the value of Auctions Won instead
(in-game stats also seem to refer to Coins as Gold but I have already reported that in the forums in september, not sure if API is affected)

**Comment by puppy0cam** [comment]
This is not on topic for the API

**Comment by TBlazeWarriorT** [comment]
Doesn't it directly affect/involve the API?

**Comment by original-codematrix** [comment]
It depends you can't say that they will use their public API on the server. They can also have a public API and an internal one.

**Comment by ConnorLinfoot** [comment]
This is a bug with the game itself, not the API. I've passed it on.
