### ISSUE TITLE
[Suggestion] More specific endpoints for the RESTful api

### ISSUE THREAD

**Issue by spthiel** [HypixelDev/PublicAPI#137]
I think it's sub optimal that the /player endpoint returns the entire player stats and that there is no way (at least not from the docs) to just get the stats of a specific game. E.g. I only need the HITW stats for the project I made but for that I still need to parse the entire player stats

Due to this I suggest adding endpoints for the specific stats of a player e.g.
api.hypixel.net/player/arcade?uuid=<UUID> should return only the arcade stats of the user.

This would save processing time on the client, (possibly the server) and also reduce packet size significantly (Currently my stats are 81KB big and if I remove everything besides arcade statistics it's reduced to 2KB which is only 2.5% of the entire packet)

**Comment by ConnorLinfoot** [comment]
There isn't really a significant reason to split these up for the majority of use cases. This would just shift the few milliseconds (if that) to find the sub-object from the user of the API to ourselves.
