### ISSUE TITLE
Some user's UUIDs don't seem to be connected to a user.

### ISSUE THREAD

**Issue by Kuba314** [HypixelDev/PublicAPI#140]
I posted a bug report here: https://hypixel.net/threads/website-api-some-uuids-dont-seem-to-be-connected-to-any-user-at-all.2399284/

Basically I found 2 players from the guild Rebel and made requests to the API with their UUIDs. The result came back as if those UUIDs didn't exist.

**Comment by mdashlw** [comment]
Most likely you found uuids of staff members. They can hide themselves from the API so this is intended behavior.

**Comment by ConnorLinfoot** [comment]
As mentioned above this is due to staff being able to hide themselves in the API.

**Comment by puppy0cam** [comment]
Duplicate of #139
