### ISSUE TITLE
[SkyBlock] Add "last_save" field to list of profiles in /player endpoint

### ISSUE THREAD

**Issue by LeaPhant** [HypixelDev/PublicAPI#141]
I'm having issues with hitting api limits on my site and apparently the limit is 120 requests per minute. I could save on a lot on requests if the `last_save` was already in the `/player` endpoint so I didn't have to fetch all profiles to get the currently used one. 

This could also be used to serve profiles from cache if they haven't updated yet without redoing the heavy request to `/skyblock/profile` (which is over 100 KB for a lot of profiles).

**Comment by ConnorLinfoot** [comment]
The `last_save` field as you have noticed is stored in the profile object itself, and not the player. The API serves data from the database directly so it's not possible to add this without creating more load on the API itself.
