### ISSUE TITLE
Skyblock Auction API Suggestion

### ISSUE THREAD

**Issue by hisuie08** [HypixelDev/PublicAPI#142]
Sorry poor English.
At present, I can get data about auction that I created through the API.
I would like to know about auctions status that I bid but it is unable as far my knowledge now
Are you planning to add key of my bid?
Could you consider about it when you are convenience?
I'm sure it will help so much:)
Thank you.

**Comment by Wonderpants** [comment]
> I would like to know about auctions status that I bid

I believe you can request every page from the auctions endpoint to obtain every auction and from there you can filter so it only applies to auctions you've bid on.


> I think this could be easily abused, like if you made a bot to automatically outbid everyone else

Any sort of automation to gain advantage over other players should be bannable

**Comment by ConnorLinfoot** [comment]
Looking up auctions by specific bids is more difficult due to the method they are stored. You can as mentioned above load the active auctions and find bids via that method.
