### ISSUE TITLE
No candy bag inventory

### ISSUE THREAD

**Issue by figgyc** [HypixelDev/PublicAPI#143]
basically #116 but for the Candy bag from the Spooky event

**Comment by ConnorLinfoot** [comment]
If you are referring to the Trick or Treat back, this isn't per player but is stored in the inventory similar to backpacks.

**Comment by figgyc** [comment]
Bit confused about that because the item description claims otherwise:
![image](https://user-images.githubusercontent.com/8902415/68547180-73dd7780-03d6-11ea-9610-1ca37e1f9091.png)
Also I tried looking in the inventory and couldnt find it, maybe it was changed?
