### ISSUE TITLE
Future date showing in guild member expHistory

### ISSUE THREAD

**Issue by Kuba314** [HypixelDev/PublicAPI#145]
![Screenshot from 2019-11-01 21-07-14_edit](https://user-images.githubusercontent.com/35199722/68053403-1cf7e400-fcec-11e9-9945-7b9802108109.png)

Today is 1.11.2019 and I don't know how this happened. Is this a bug in the API or a wrong time and date of that user's client?

Edit: ALRIGHT... I swear I didn't edit this screenshot other that that red line. It somehow fixed itself? It happened to me like 3 times and now nothing?
Edit 2: Ok, now I noticed that the length of the expHistory is 6, not seven as it is normal. Is this a timing bug in the API? Sending the response before it's complete?
Edit 3: Found 2 players again. But this time the expHistory is 7 days again. Also they are different players
![Screenshot from 2019-11-01 21-40-56](https://user-images.githubusercontent.com/35199722/68055337-b45f3600-fcf0-11e9-9d50-d38c44c07da5.png)
![Screenshot from 2019-11-01 21-41-50](https://user-images.githubusercontent.com/35199722/68055338-b4f7cc80-fcf0-11e9-9913-34b72206ceb0.png)

Edit 4: The people with "expHistory" shorter than 7 changes. But not per every request.
![Screenshot from 2019-11-10 20-11-45](https://user-images.githubusercontent.com/35199722/68549339-3ccb8e00-03f7-11ea-9e4d-727c1c3f77a1.png)
![Screenshot from 2019-11-10 20-12-28](https://user-images.githubusercontent.com/35199722/68549341-3e955180-03f7-11ea-98e0-9b2defcbee2d.png)

**Comment by Kuba314** [comment]
There is this scipt I wrote for python:
```
import json, requests

def get_errors(guild_name):
	txt = requests.get('https://api.hypixel.net/guild?key=<YOUR_API_KEY>&name=' + guild_name).text
	obj = json.loads(txt)
	if not obj['success']:
		print obj['cause']
	for member in obj['guild']['members']:
		if len(member['expHistory']) < 7:
			print member['uuid'], len(member['expHistory']), member['expHistory']
```
replace `<YOUR_API_KEY>` in the function with your api key for this to function

**Comment by Kuba314** [comment]
I also found out that sometimes the whole 'expHistory' dictionary is just straight up empty.

**Comment by Kuba314** [comment]
Made a report here: https://hypixel.net/threads/website-api-exphistory-date-is-not-correct.2473652/

**Comment by Kuba314** [comment]
Update: still a thing. `2020-04-31` is sometimes in the response `expHistory`

**Comment by Kuba314** [comment]
Is there any reason this bug still exists? Can't you guys find it or is it like this for a reason? Or do you focus more on updating skyblock than on fixing api bugs?

**Comment by pownsgg** [comment]
@Kuba314 This issue indeed is still occuring, I created this thread on the Hypixel forums earlier: https://hypixel.net/threads/guild-api-gexp-for-certain-date-missing-for-players.2903158/

Sometimes data for a day is either missing or completely incorrect :/

**Comment by Eqrly** [comment]
imagine hypixel fixed this

**Comment by Kuba314** [comment]
Oh look, both errors in one member's `gexpHistory`
![image](https://user-images.githubusercontent.com/35199722/89109322-6e323100-d440-11ea-8e75-2c681f21db54.png)

**Comment by Kuba314** [comment]
Guess what happened on `2020-09-01`?
That's right!
It tried showing `2020-08-31`, but failed and showed `2020-09-31` instead!
![image](https://user-images.githubusercontent.com/35199722/91968550-17589980-ed15-11ea-944a-8528be066be9.png)

**Comment by TheNullicorn** [comment]
Based on your screenshots alone, it looks like the issue with incorrect dates is only ever off by +1 month. Until this is fixed (if ever), you could just subtract one month whenever it's out of range, and default to 0 gexp for missing dates.

**Comment by Plancke** [comment]
Incorrect date issue should be fixed, missing values frequency should also have reduced significantly though we'd rather show the guild response with a missing value than fail completely. Just handle missing data as 0 and don't assume it always has 7 days in there.
