### ISSUE TITLE
Request: Auctions in the last hour

### ISSUE THREAD

**Issue by Ekwav** [HypixelDev/PublicAPI#147]
I try to collect all auctions that are happening, to calculate the average selling price of items, so I can make a good starting bid, and can see the richest players I might sell something to.

However to get all the auctions in the auction house I have to query all pages of the auction API every one to two miniutes, parse everything and see what it is new.
This is a lot of overhead just to not miss 2 min lasting auctions.

I would like to have a new API endpoint, or option for the current `/skyblock/auctions` endpoint (like `includePast=true&time=6h`, to get every auction happened in the last hour or day.
That way I will save me and you a lot of bandwith and not get anywhere close to the rate limit.
The result may be cached for the next hour on your side as well.

**Comment by ConnorLinfoot** [comment]
At this time we don't plan to add a method to view past auctions in a method like this.
