### ISSUE TITLE
Fix item collection names

### ISSUE THREAD

**Issue by skyblockz** [HypixelDev/PublicAPI#148]
Names in skyblock/profile profile.member.playeruuid.collection is corrupted, example: cocoa beans turned into inksack:3, lapis lazuli turned into ink sack:4...etc

**Comment by puppy0cam** [comment]
Prior to the updates that phased out item IDs, all dyes were stored as a
sub-item of ink sacks. As Hypixel is running on 1.8, it is likely using a
combination of Bukkit's item naming system as well as metadata.

>

**Comment by skyblockz** [comment]
Ah~ Alright!
