### ISSUE TITLE
skyblock/collections issue

### ISSUE THREAD

**Issue by skyblockz** [HypixelDev/PublicAPI#151]
A key doesnt exist in it when the user didnt collect at least one of the item, so maybe we can make it say collection:0 when user has not collected one yet, makes it less errors
thanks

**Comment by mdashlw** [comment]
Did you mean the `skyblock/profile` endpoint?
If so, this is intended behaviour that items the player has never collected are not in the `collection` field. This probably won't be changed as it's pretty easy to deal with this behaviour.

**Comment by skyblockz** [comment]
oh it's intended
well never mind then
