### ISSUE TITLE
[SkyBlock] Highest Crit Damage field is completely broken, hits integer limit and can decrease

### ISSUE THREAD

**Issue by TBlazeWarriorT** [HypixelDev/PublicAPI#156]
_Once again I'm not sure if this is an API or exclusively in-game bug, so sorry in advance._

The API is returning absolutely wrong values for "Highest crit damage", as can be seen on [here](https://skyblock.matdoes.dev/leaderboard/highest_crit_damage)

The number seems to be dozens of times higher than the real value that should be sent or displayed by the API, and seems to cap a bit over the integer/float max limit, at 2.1m.

To make it even worse, the "Highest crit damage" dealt can decrease, submitting a lower value than previous to the API, as seen below:
before
![image](https://user-images.githubusercontent.com/25572454/69304202-8d649780-0bfe-11ea-90a3-01970a117cca.png)
after
![image](https://user-images.githubusercontent.com/25572454/69304212-93f30f00-0bfe-11ea-9848-ded024527565.png)
(not an issue with the website, it's the API itself letting those values get overrided by lower ones)

**Comment by puppy0cam** [comment]
related: https://hypixel.net/threads/skyblock-highest-crit-damage.2388921/

**Comment by ConnorLinfoot** [comment]
This is a bug with the game, I've passed it on to be investigated.
