### ISSUE TITLE
API doesn't update

### ISSUE THREAD

**Issue by skyblockz** [HypixelDev/PublicAPI#157]
Sometimes the API doesn't update even the user has changed their settings
For example they have turned their api settings for collection on, but it doesnt allow us to query it until they relog, maybe there is a solution?
Please tell me, thanks!

**Comment by puppy0cam** [comment]
https://shouldiblamecaching.com/
Most likely a cache at play, do you refer to it being a relog from the Hypixel network entirely, or to switch islands, or to go to the prototype lobby and back?

**Comment by ConnorLinfoot** [comment]
Yep, a form of caching is the reason for this. We don't instantly save data to the database to reduce overall requests, leaving SkyBlock does cause it to save or waiting for a little bit will result in the settings being saved.
