### ISSUE TITLE
SkyBlock API character encoding problem: question marks in the data

### ISSUE THREAD

**Issue by Flachdachs** [HypixelDev/PublicAPI#158]
In APIs like https://api.hypixel.net/resources/skyblock/skills there are text data, e.g. in the "unlocks" fields of the levels. But some characters are lost, because they are converted server side to question marks (U+003F). So this API data is less useful.

Example, Level 2 of Farming skill:

```
Farmhand II 4?8% chance to get double crops.
+2 HP ? Health
```

The first question mark is in the game an arrow, the second stand for a heart.

https://api.hypixel.net/resources/skyblock/collections has the same problem e.g. in both tier 5 and 8 of sugar collection

```
Speed Talisman ? Speed Ring Upgrade
...
Speed Ring ? Speed Artifact Upgrade
```

As a consumer of these data there is no (easy) way to know which character is actually represented by these question marks.

Cross reference: https://hypixel.net/threads/skyblock-api-character-encoding-problem.2457741/

**Comment by puppy0cam** [comment]
related issues:
#109
#93 (59b6453e428ec91508ebffa2bc03de90da75a616)

**Comment by Flachdachs** [comment]
Someone fixed it, mentioned characters are now correctly encoded.
