### ISSUE TITLE
Document game subtypes

### ISSUE THREAD

**Issue by Tmpod** [HypixelDev/PublicAPI#159]
I was playing around with the `gamesCount` endpoint and I was having a bit of trouble trying to create records for each game type as their currently available subtypes is not consistent (due to seasonal gamemodes). Could you add something like the `GameType` file, listing all the existent game subtypes?  
I'd be very grateful ;)

**Comment by ConnorLinfoot** [comment]
Unfortunately, not currently. There are too many modes of which can also easily come and go for us to keep something that is up to date.
