### ISSUE TITLE
API down - HTTP/2.0 526 No Reason Phrase

### ISSUE THREAD

**Issue by Flachdachs** [HypixelDev/PublicAPI#160]
Right now whatever API request I try (with API key like /skyblock/news or without like /resources/skyblock/collections) I get a response

HTTP/2.0 526 No Reason Phrase

Also other web sites that obviously use the API only answer with error messages, like 
https://sky.lea.moe/
https://hsb.gg/
So, it seems that is not a problem that only happens for me.

**Comment by Flachdachs** [comment]
Seems to be a temporary error, because it now works again.

**Comment by mdashlw** [comment]
Also don't report maintenances like that here in the future. I don't think this issue tracker is reserved for temporary errors like in this case - invalid ssl certificate. Most of the times devs are fully aware if the whole api is down.

**Comment by Flachdachs** [comment]
How do I distinguish between a maintenance issue and other reasons? The Error code 526 is not standardized nor was a reason text specified.

**Comment by mdashlw** [comment]
526 is Invalid SSL certificate error. Also https://api.hypixel.net/ was returning an html page with error message.
