### ISSUE TITLE
Add patch note endpoint

### ISSUE THREAD

**Issue by hisuie08** [HypixelDev/PublicAPI#162]
In additional to skyblock/news i want more infomation about update.
so could you add patch note end point and be enable to get from https://hypixel.net/forums/skyblock-patch-notes.158/ in json format?
if you allow to do, i can get them with web scraping but i think its not cool way.

**Comment by mdashlw** [comment]
You can retrieve posts using RSS: https://hypixel.net/forums/skyblock-patch-notes.158/index.rss

Also everyone is allowed to scrap any public information from the website without asking a permission.

**Comment by hisuie08** [comment]
Thank you too much!
