### ISSUE TITLE
[SkyBlock] Add a way to get HP, Crit Chance, Crit Damage, etc...

### ISSUE THREAD

**Issue by Franko1307** [HypixelDev/PublicAPI#164]
Currently there's no way to get those stats. The only way to get those stats right now is to  calculate them yourself which is a lot of work and it's pretty hard to be precise.

**Comment by puppy0cam** [comment]
There is something to be said for making base stats available. However values during gameplay are calculated by the server and probably aren't even stored in the database.

**Comment by ConnorLinfoot** [comment]
That ^ these stats are generated dynamically due to the amount of things that affect them. There isn't any advantage for us to store these.
