### ISSUE TITLE
Fields missing but was on the API before.

### ISSUE THREAD

**Issue by Picsou993** [HypixelDev/PublicAPI#168]
Some fiels are missing from the API but was on it before.
These that I have seen are holidays presents from 2015 to 2018:
2015: PRESENT_FIND_**_GameName_**
2016: xmas2016_**_GameName_**
2017: xmas2017_**_GameName_**
2018: xmas2018_**_GameName_**

I have also seen that NPC Rewards are also missing: REWARD_FIND_**_NPCName_**.

It is possible that other fields have been removed without any reason. So is it possible to put them back or know why they have been removed.

**Comment by ConnorLinfoot** [comment]
These fields were removed as they're no longer needed and provide no purpose on the server.
