### ISSUE TITLE
Add an amount attribute to an auction

### ISSUE THREAD

**Issue by XanderDJ** [HypixelDev/PublicAPI#169]
It would be useful. For example when someone sells 62 enchanted diamond ores it doesn't show up on the /skyblock/auctions JSON returned. Which makes you unable to know how many enchanted diamonds are being sold only that there is an enchanted diamond on the ah right now.

**Comment by Wonderpants** [comment]
There's an "item_bytes" field that if you decompile and read it, there is a "Count" value that holds the item count.

**Comment by builder-247** [comment]
If you are looking for an easier option, you should look in [Slothpixel API](https://docs.slothpixel.me), the `/api/auctions` endpoint provides count alongside other item metadata and also allows custom queries.

**Comment by XanderDJ** [comment]
Yea I got it out of the item bytes. I was confused how it worked. But I figured it out eventually.
