### ISSUE TITLE
[SkyBlock] Kicked members still showing in profile

### ISSUE THREAD

**Issue by mat-1** [HypixelDev/PublicAPI#170]
When viewing someone's profile if they have a member that was kicked, they'll still show up in the list.
Example: https://api.hypixel.net/skyblock/profile?key=&profile=54ecc1f81d3c42c49f67f6e2c802d180
![image](https://user-images.githubusercontent.com/27899617/71594438-841ff200-2afd-11ea-8a85-189deba95843.png) (3dffd... was kicked)

However, if you go to their player data https://api.hypixel.net/player?key=&uuid=3dffdff959bd4cfb837585329ddee18d (player.stats.SkyBlock.profiles), you'll see that there's only a single profile that's not in the co-op
![image](https://user-images.githubusercontent.com/27899617/71607265-78ecb680-2b3d-11ea-8926-f3f1f71148de.png)

**Comment by puppy0cam** [comment]
This is because the data still exists for the coop member, notice how in your collections, the name of the left player still remains. You likely need the value to correctly get the true collection value.

**Comment by jtagt** [comment]
I think there should be a field that is present that tells us whether or not they are still present. Rather than having to request the players profiles.

**Comment by skyblockz** [comment]
> I think there should be a field that is present that tells us whether or not they are still present. Rather than having to request the players profiles.

Agreed, make a boolean value called in profile, true for current member, false for kicked or left

**Comment by Wonderpants** [comment]
> > I think there should be a field that is present that tells us whether or not they are still present. Rather than having to request the players profiles.
> 
> Agreed, make a boolean value called inProfile, true for current member, false for kicked or left

It should actually have a field for when that user left the coop since that information is displayed server-sided. If the field isn't present then that would mean the user didn't leave.

**Comment by TBlazeWarriorT** [comment]
true

**Comment by ptlthg** [comment]
I know this already has labels and a field to detect this is (hopefully) going to be added, but I just wanted to chime in that this would still be appreciated. I don't want to have broken links to removed profile members, but the only way around that is to also request that data, which takes more API requests.

**Comment by ConnorLinfoot** [comment]
We've added the field `deletion_notice` to the profile members when a member is marked as deleted, so as long as this field exists, the member profile is deleted and can be displayed/ignored accordingly. At this time this also includes a timestamp of when the member was deleted, either due to leaving, being kicked, or any other reason.

Some very old deleted members (we're talking from the first couple of months of SkyBlock) won't have this field when deleted due to a legacy field being used, we'll be converting these over as soon as possible so they will also have this field in the near future.
