### ISSUE TITLE
Create "count" value

### ISSUE THREAD

**Issue by skyblockz** [HypixelDev/PublicAPI#173]
Current Count value in skyblock/auctions is inside item_bytes, which takes time to encrypt, directly placing it inside the json itself makes so you can get it faster, please do so!

**Comment by builder-247** [comment]
Duplicate of #169.

**Comment by Wonderpants** [comment]
> which takes time to encrypt

do you mean decrypt? cuz if so, ~0.0009 seconds shouldn't really affect the program.

**Comment by robere2** [comment]
Keep in mind that providing this data directly in the JSON, if anything, will slow down your program, not speed it up. It would mean the API server would have to parse the NBT before sending out a response, and then provide this extra and already-included data in the response, which takes bandwidth and data transfer.

The main argument for this would be for ease of use of the API. It isn't really going to speed up your program and even if it did, it's nothing meaningful.

**Comment by skyblockz** [comment]
Realized https://api.slothpixel.me/api/skyblock/auctions was another good alternative of hypixel api
Thanks for the help, though
