### ISSUE TITLE
Add endpoint to pull player data from redis

### ISSUE THREAD

**Issue by mdashlw** [HypixelDev/PublicAPI#174]
It would be really useful to be able to get all the player data stored in redis (and therefore not available through /player endpoint), such as skywars rating, monthly/weekly kills/wins for all game modes, etc.
Maybe make more strict rate limits to this endpoint or caching if you think it will make too much load for redis.

**Comment by ConnorLinfoot** [comment]
We already have data shared from redis which is injected into existing endpoints. We don't plan to add anything further at this time.
