### ISSUE TITLE
Guild endpoint doesn't return default guild ranks

### ISSUE THREAD

**Issue by builder-247** [HypixelDev/PublicAPI#177]
The `ranks` array of guilds endpoint doesn't contain the rank of `GUILDMASTER` or other default roles that haven't been edited. This makes some member tags unavailable as well as makes sorting guild members by rank gimmicky [1].

---
[1] _All sorts of hacks need to be put in place to resolve the issue_ 

![image](https://user-images.githubusercontent.com/14019974/72908561-5285f980-3d3e-11ea-84ab-268d82fcbbdd.png)

**Comment by ConnorLinfoot** [comment]
Ranks are the list of ranks created by that guild since that's the data requested.
