### ISSUE TITLE
Make "queriesInPastMin" reset relative to first query

### ISSUE THREAD

**Issue by Kuba314** [HypixelDev/PublicAPI#178]
The "queriesInPastMin" parameter of the "key" page is reset every minute, but the reset time is not known. It is not exactly at a whole minute, nor is it relative.

If it was relative, a script could then be easily implemented to avoid key throttles and use it's 120 queries per minute.

Seriously. This is not that hard to fix.

**Comment by ConnorLinfoot** [comment]
There isn't anything to fix. It's reset every 60 seconds per the system that manages the API.

**Comment by Kuba314** [comment]
Then change how the system manages the limit. If you think I suggested this only for the Java API you're wrong. I got told to post about this here since this is supposed to be a place for the general API issues.

This is a suggestion, not an issue that needs a fix. However it's really annoying checking for a key throttle. Can't you just change the system that manages the API?

**Comment by puppy0cam** [comment]
This likely varies depending on the startup time for the API instance.
A solution could be to provide a startupTime parameter in order to synchronise the rate limit.

**Comment by Kuba314** [comment]
@puppy0cam you're talking like there is no way to make it relative. I don't know in what language the API is made, so I can't really design a solution.
But, maybe make a list and every time a user sends a request, add that time to the list. The server could then check the length of the list. And remove times older than 1 minute.
This sure makes this not a REST API.
So maybe the /key could have a param "apiStart" to allow users to synchronise? That is a good idea.
