### ISSUE TITLE
Create skyblock/npcprice resource

### ISSUE THREAD

**Issue by skyblockz** [HypixelDev/PublicAPI#179]
Basically a resource api that gives you all items of what npc sells, which npc sells them, and their price

**Comment by puppy0cam** [comment]
A resource listing sell values for items is somewhat reasonable, but I don't think the price for buying items from an NPC is viable. Especially specifying which NPC you can get it from.
Not all NPCs work the same way, for example in the end there is no centralised npc for buying items, it's just showcased.

**Comment by skyblockz** [comment]
But it would still be nice to have a full list of prices though

**Comment by ConnorLinfoot** [comment]
This is not something we wish to do at this time.
