### ISSUE TITLE
Rate limit response has status code 200

### ISSUE THREAD

**Issue by ThomDeMeulder** [HypixelDev/PublicAPI#182]
Hi!

I was trying to figure out how the rate limit works, and saw that when the rate limit has been reached the status code is still 200 OK. As you can see in the top right corner of [this screenshot](https://gyazo.com/e96f4d4ed99782cbfd87016c0adb5781) taken inside Postman. 

I'd like to suggest to change this to status code [429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) to make it easier to see if the API has rate limited the application, instead of having to parse the body and see whether or not it's the response I was expecting.

**Comment by builder-247** [comment]
Also every single other response is a `200 OK`, even internal errors and not founds. Using the appropriate status codes is not only a good practise, but makes development easier since sometimes the API returns an empty body for example.

**Comment by skyblockz** [comment]
And it should include reset after in that as well, to know when to start the next request in case of ban

**Comment by ConnorLinfoot** [comment]
We've changed any failure requests to now respond with the correct HTTP status codes.
