### ISSUE TITLE
(Suggestion) Make guild["members"] a dictionary

### ISSUE THREAD

**Issue by Kuba314** [HypixelDev/PublicAPI#183]
guild["members"] is a list. If you want to get member's data you have to loop through the list and find the desired member.

Why not just make it a dictionary with uuids as keys for quicker and less messy access?

Edit: Example in python. What do you think is nicer?
before:
```
member = next(m for m in guild['members'] if m['uuid'] == uuid)
```
after:
```
member = guild['members'][uuid]
```

**Comment by Plancke** [comment]
It's stored as a list in our database, we're just displaying it as is to prevent processing on our end.
