### ISSUE TITLE
Reduce caching delay 

### ISSUE THREAD

**Issue by Ekwav** [HypixelDev/PublicAPI#186]
Please lower the caching steps of the `/skyblock/auctions` again.
The currently served active auctions cache is almost 21 hours old.

**Comment by Picsou993** [comment]
Hi, the auctions cache is working good. It currently refreshes every minute.
However your issue had been probably linked to the recent SkyBlock issues as the Auction House had been disabled for hours so not needed to refresh it.

**Comment by Ekwav** [comment]
It is linked indeed. But I was able to access the auction house in Game,
about two hours prior to opening the issiue. Also i didn't get Data for
another 3 hours.

Picsou993 <notifications@github.com> schrieb am Mi., 26. Feb. 2020, 18:17:
