### ISSUE TITLE
Add more details about server the player is in.

### ISSUE THREAD

**Issue by syrphizan** [HypixelDev/PublicAPI#187]
Now there is a `session` method that only shows minigames, and does not include other places on the network (e.g. lobbies & limbo).

*I know that the `session` method is deprecated and will be removed at a later date. I'm talking about the future `session` equivalent.*

This feature will allow us to track whether the player is on a private island in the Skyblock or in the hub/limbo (due to a server reboot, etc.). It will be possible to make a notification app for efficient AFK Pool usage.

**Comment by mdashlw** [comment]
Your case can be solved by using `/locraw` on the server. However, I agree that there should be an endpoint that exposes player's game type, game mode, map, maybe instance id, and possibly players on the same game server.

**Comment by syrphizan** [comment]
Thank you, I didn't know about this command. In my modest opinion, the result returned by this command is a great example for the new method replacing the deprecated `session`.

**Comment by crinny** [comment]
While I think this is a great idea, this could possibly ruin streamers' lives. If this is going to be done, players should be able to disable it somewhere in the settings

**Comment by ConnorLinfoot** [comment]
There is a new status endpoint added to replace the previous session endpoint which should also offer what you need. https://hypixel.net/threads/2656659/
