### ISSUE TITLE
SkyBlock 'auction' method

### ISSUE THREAD

**Issue by Picsou993** [HypixelDev/PublicAPI#189]
Hi, the [auction method](https://api.hypixel.net/skyblock/auction?key=) does not return the good parameter.
It returns 'id' instead of 'uuid' for the auction uuid.

Also, I suggest to edit [the documentation](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/skyblock/auction.md) to add that 'player' must be the UUID of the player and not its username ;).

**Comment by ConnorLinfoot** [comment]
The issue with the API error has been fixed, thanks.
