### ISSUE TITLE
Add ranked sw rating and leaderboard

### ISSUE THREAD

**Issue by mdashlw** [HypixelDev/PublicAPI#190]
Hypixel has recently made a change that make it extremely difficult to scrape the website hypixel.net, although this is not prohibited by any rules and is absolutely legal.
But there are some statistics on the site that are not available in api, such as ranked skywars rating and ranked skywars leaderboard. It would be really great if this was added to api, because my stuff depends heavily on it, and it would be unpleasant if it lost its main feature.
Or another solution is to allow to scrape the site, as it always has been.

**Comment by ConnorLinfoot** [comment]
At this time we do not wish to add this data to the API.

**Comment by mdashlw** [comment]
Maybe then allow to scrap the site? There are no rules about it and it is legal. Right now I get 1020 cloudflare error when doing a request from any server at all.
I'm actually okay with this, I got used to scrape the website and deal with it, but what to do now?
