### ISSUE TITLE
Some SkyBlock profiles return "Internal error"

### ISSUE THREAD

**Issue by builder-247** [HypixelDev/PublicAPI#191]
Here is a list of example skyblock profiles that return `{"success":false,"cause":"Internal error"}` upon requesting.
```
d5e1578e45e54aa2834cbf16f1c44151
6699e1bf010a4c888d5cc9d3aa90635d
bbb5e597f67b400e9757e0b7d3239b3a
12d9a6cf8d874dfd9223f7323581a7c7
```
Also profile `7026524d8f10438ba89796c9e7207b47` returned the error yesterday but seems to have since then been fixed.

**Comment by puppy0cam** [comment]
I would imagine that there is some malformed data somewhere which the API is unable to transform into valid data. Most likely, having them log into the server will fix this issue.

**Comment by ConnorLinfoot** [comment]
This should be resolved now.
