### ISSUE TITLE
SkyBlock API returning wrong collection levels

### ISSUE THREAD

**Issue by TBlazeWarriorT** [HypixelDev/PublicAPI#192]
![image](https://user-images.githubusercontent.com/25572454/76169650-280ac700-6159-11ea-9aec-2137f5287750.png)
api.hypixel.net/skyblock/profile?key=**[redacted]**&profile=54ecc1f81d3c42c49f67f6e2c802d180

**"unlocked_coll_tiers":[...,"CLAY_BALL_-1","CLAY_BALL_1"** (only two times it appears)

**"collection":{"CLAY_BALL":7264036,**

7M clay collection, API still at tier -1

![image](https://user-images.githubusercontent.com/25572454/76169707-b5e6b200-6159-11ea-8efb-f1d585a7413f.png)
Redstone and Sand also look wrong, not a website issue, it's on the API side

**Comment by ConnorLinfoot** [comment]
These values seem to be due to how the game calculates the tiers. You are likely better to use the value and calculate it via the https://api.hypixel.net/resources/skyblock/collections endpoint.
