### ISSUE TITLE
Duels Match History

### ISSUE THREAD

**Issue by Picsou993** [HypixelDev/PublicAPI#193]
It is possible to see the list of the last 50 duels game played for players with 'matchHistory2'. These information should not be publicy visible as it also shows the real username of players even if they are nicked.

**Comment by ConnorLinfoot** [comment]
Thank you for informing us about this, it has now been removed.

**Comment by HardstylesDev** [comment]
> Thank you for informing us about this, it has now been removed.

Yeah or you could've simply fixed it instead of straight up removing it. Kind of lame Connor.

**Comment by ConnorLinfoot** [comment]
> > Thank you for informing us about this, it has now been removed.
> 
> Yeah or you could've simply fixed it instead of straight up removing it. Kind of lame Connor.

There was nothing to fix, it was never intended to be a public field.
