### ISSUE TITLE
Support Bazzar

### ISSUE THREAD

**Issue by skyblockz** [HypixelDev/PublicAPI#194]
It would be nice to allow us get information about all items that are sold in Bazzar and get their buy/sell price as well
shall be an endpoint like skyblock/bazzar

**Comment by crinny** [comment]
Also would be cool to get the data used to create graphs as it would let developers to create better looking ones.

**Comment by ChristolisOfficial** [comment]
Agreed!

**Comment by Minikloon** [comment]
Done.
https://github.com/HypixelDev/PublicAPI/tree/master/Documentation/methods/skyblock/bazaar
