### ISSUE TITLE
skyblock/auction endpoint returning old data

### ISSUE THREAD

**Issue by MylesMor** [HypixelDev/PublicAPI#195]
The skyblock/auction endpoint seems to return very old information.

If you try this:
https://api.hypixel.net/skyblock/auction?player=7b892af879f64e12a3ed6a895415212a&key=YOUR-KEY

Preview:
```
"success": true,
    "auctions": [{
             "_id": "5d040cd344f4175497be5fcf",
             "uuid": "cf8171abf94f44939cfb99599f866475",
             "auctioneer": "7b892af879f64e12a3ed6a895415212a",
             "profile_id": "7b892af879f64e12a3ed6a895415212a",
             "coop": [
                    "7b892af879f64e12a3ed6a895415212a"
             ],
             "start": 1560546515506,
             "end": 1560589715506,
             "item_name": "Stick",
             "item_lore": "§f§lCOMMON",
             "extra": "§fStick Stick",
             "category": "misc",
             "tier": "COMMON",
             "starting_bid": 10,
```

You can see that only 3 auctions made by myself (my UUID) are present, and these are the oldest auctions I've made. The start time for the first one is ``1560546515506`` which is 14th June. 

I've made many auctions since then, so is it possibly only retrieving the oldest auctions for whatever reason?

**Comment by ConnorLinfoot** [comment]
The auctions endpoints only return what auctions are still "active" in some way. Auctions are active until all bidders and winners claim their money/items.

**Comment by MylesMor** [comment]
> The auctions endpoints only return what auctions are still "active" in some way. Auctions are active until all bidders and winners claim their money/items.

Right, thanks for explaining. It might be useful to add this to the markdown file to explain this to newcomers, as seemingly no-one I asked knew about it.
