### ISSUE TITLE
Add modes to resources

### ISSUE THREAD

**Issue by builder-247** [HypixelDev/PublicAPI#197]
Due to introduction of the `recentGames` endpoint, a new resources for converting the mode values should be added. This data is already available via the unofficial https://api.connorlinfoot.com/v2/games/hypixel/ endpoint.

**Comment by ConnorLinfoot** [comment]
We have something in the works currently which will be released publicly when ready but we want to include as many if not all the modes we can.

I'll leave this issue open so people can subscribe for when its added.

**Comment by mdashlw** [comment]
It has been two months, is there any update on this? I also noticed game mode name varies on context, in /status: `MURDER_CLASSIC`, in /recentGames: just `CLASSIC`, making it even more difficult to make the whole mode list by ourselves
