### ISSUE TITLE
Make bazaar/products static

### ISSUE THREAD

**Issue by Picsou993** [HypixelDev/PublicAPI#198]
Is it possible to set the [bazaar/products method](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/skyblock/bazaar/products.md) a [static method](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/resources.md).

**Comment by ConnorLinfoot** [comment]
The data is not generated via static resources and thus will not be a resource endpoint.
