### ISSUE TITLE
Bazaar products

### ISSUE THREAD

**Issue by NotANullPointer** [HypixelDev/PublicAPI#200]
Shouldn't /skyblock/products be a resource since it almost never changes?
Products page:
![immagine](https://user-images.githubusercontent.com/13029101/76645730-dcda2500-6559-11ea-84e5-36dc47af3868.png)

Resources page:
![immagine](https://user-images.githubusercontent.com/13029101/76645788-f4191280-6559-11ea-8f5e-8e4e8e15bd49.png)

**Comment by mdashlw** [comment]
See #198

**Comment by NotANullPointer** [comment]
Alright, my bad, didn't see that.
