### ISSUE TITLE
Accept both itemname and productId in skyblock/bazaar/product

### ISSUE THREAD

**Issue by skyblockz** [HypixelDev/PublicAPI#201]
It is pretty annoying you have to replace user inputs to item id, so it shall be a thing
and add them into skyblock/bazaar/products as well

**Comment by puppy0cam** [comment]
It's entirely possible that the name of an item is not locked in and could change at any time in a future update. For example, Hypixel may add the ability to add a prefix or suffix to a weapon which would break systems trying to interpret the string.
It is my personal recommendation that you keep an internal list of item names and map them to an item id.
NBT data should supply the item ID already, so you can create a system to help you keep the list up to date automatically when scanning things such as auctions.

**Comment by ConnorLinfoot** [comment]
This isn't something we plan on supporting, the above comment gives some explanation to this.
