### ISSUE TITLE
Flawed calculation of Bazaar product buy/sell price in quick_status

### ISSUE THREAD

**Issue by pwign** [HypixelDev/PublicAPI#203]
I believe the way `sellPrice` and `buyPrice` is calculated in a product's `quick_status` is flawed, in the way that it's not a representation of the sell/buy price by any mean.

The documentation noted that
> prices are the weighted average of the top 2% of orders by volume

I'm unsure whether this is a bug or an intended effect, but as an example, the `SUPER_COMPACTOR_3000` has a current `buyPrice` (selling price) of around 12,000 and `sellPrice` (buying price) of 500,000. That is far from what the current buy/sell price reports if calculated from the latest `week_historic` index.

|  | `buyPrice` | `sellPrice` |
| :---                     |     :---:      |     :---:      |
| `quick_status`   | **12,735.02**     | 499,999.82    |
| `week_historic` | 485,250.52       | 499,999.71      |

`week_historic` row was calculated by dividing coins with volume.
Notice how the `buyPrice` from `quick_status` is very out of place.

**Comment by skyblockz** [comment]
It's broken ingame as well, hypixel is being strange at bazaar recently

**Comment by pwign** [comment]
Similar issue: #218

**Comment by 360camera** [comment]
For anyone having issues finding an accurate buy/sell price, use the first buy/sell summary value until this is fixed. [Source](https://hypixel.net/threads/help-bazaar-api-returning-wrong-numbers.2949055/post-20496121)

**Comment by ConnorLinfoot** [comment]
This issue seems to be with the game itself and not the API.
