### ISSUE TITLE
Quantity of item being bid

### ISSUE THREAD

**Issue by bchen290** [HypixelDev/PublicAPI#205]
The auction/auctions endpoint should return the quantity of item being bid

**Comment by puppy0cam** [comment]
You can obtain this information with the item bytes. Instructions to decode the data can be found here: https://github.com/HypixelDev/PublicAPI/tree/master/Documentation#skyblock-items-and-inventories

**Comment by bchen290** [comment]
This is the data after I decoded it
b'\n\x00\x00\t\x00\x01i\n\x00\x00\x00\x01\x02\x00\x02id\x00\x98\x01\x00\x05Count\x01\n\x00\x03tag\t\x00\x04ench\x00\x00\x00\x00\x00\x03\x00\tHideFlags\x00\x00\x00\xfe\n\x00\x07display\t\x00\x04Lore\x08\x00\x00\x00\x02\x00\x15\xc2\xa78Brewing Ingredient\x00\n\xc2\xa79\xc2\xa7lRARE\x08\x00\x04Name\x00\x1b\xc2\xa79Enchanted Redstone Block\x00\n\x00\x0fExtraAttributes\x08\x00\x02id\x00\x18ENCHANTED_REDSTONE_BLOCK\x00\x00\x02\x00\x06Damage\x00\x00\x00\x00'
I can't extract quantity information from this

**Comment by puppy0cam** [comment]
You haven't fully decoded it yet, you need to run it through an nbt parser
