### ISSUE TITLE
(Suggestion) player/stats/skywars json is huge and confusing

### ISSUE THREAD

**Issue by Kuba314** [HypixelDev/PublicAPI#206]
The skywars object is huge. You could make it into a hierarchy.
```
kits:
    teams:
        healer:
            kills: ...,
            deaths: ...
```
but instead you got a property called `kills_kit_supporting_team_healer`.
Why is it like this? It could be way nicer.

Also there is `kills_team_insane` and `kills_teams_insane` as well.

![image](https://user-images.githubusercontent.com/35199722/77248579-d2471c00-6c3a-11ea-9517-62de9444de30.png)

**Comment by mdashlw** [comment]
If this is how it is stored, it is the most efficient and convenient way for hypixel developers. This is already stored like that in the database, the only way to return it in a nice hierarchy is to preprocess the data in the endpoint handler, which probably will not happen.
By the way, there's unofficial api that tries to return stats in a nice way, however skywars stats are not done yet: https://docs.slothpixel.me/

**Comment by puppy0cam** [comment]
The API returns redacted data directly from their database They do not otherwise transform the data, so you are looking at the data as they would from ingame.
