### ISSUE TITLE
Missing items from Bazaar API

### ISSUE THREAD

**Issue by jonese1234** [HypixelDev/PublicAPI#207]
"ENCHANTED_COCOA" is included but regular "COCOA" is not.
"ENCHANTED_RAW_BEEF", but no "RAW_BEEF",
"ENCHANTED_LAPIS_LAZULI", but no "LAPIS_LAZULI",
"ENCHANTED_GUNPOWDER", but no "GUNPOWDER",

The Logs are all messed up
We have "Log", "LOG:1","LOG:2","LOG:3", What does it mean?

**Comment by puppy0cam** [comment]
LOG:1, etc are relics of bukkit's proprietary item naming system from before Mojang added a proper naming system. The numeral indicates the type of log.

**Comment by Bregann** [comment]
> "ENCHANTED_COCOA" is included but regular "COCOA" is not.
> "ENCHANTED_RAW_BEEF", but no "RAW_BEEF",
> "ENCHANTED_LAPIS_LAZULI", but no "LAPIS_LAZULI",
> "ENCHANTED_GUNPOWDER", but no "GUNPOWDER",
> 
> The Logs are all messed up
> We have "Log", "LOG:1","LOG:2","LOG:3", What does it mean?

beef is on there under RAW_BEEF

This might be of help identifying some of the weirder named items: https://gist.github.com/Bregann/345af23bbf9a878077fb65a162b4684b

The productToParse is the API product name

**Comment by yavkata999** [comment]
Guys is Raw_Fish:2 = clownfish? I think miikloon forgot to mention in forum post that they've added clownfish/enchanted_clownfish to the api.

**Comment by FreeSoccerHDX** [comment]
Still, nothing changed.
Its sad that we can't implement all products to our apps.
I think it only needs some minutes to change this, but however they don't do that.

**Comment by yavkata999** [comment]
I just made dictionary with all the items with the help of Bregann's values. Also what do you mean we can't implement all products to our app. I can do it just fine.

**Comment by FreeSoccerHDX** [comment]
the problem is, that you dont know all productIDs 
for example: raw_beef
you have to find them out like those:
SNOW_BALL, ENCHANTED_SNOW_BLOCK
they are not mentioned in the api but exist

**Comment by builder-247** [comment]
You can find missing items' IDs here https://api.slothpixel.me/api/skyblock/items

**Comment by yavkata999** [comment]
Thank you builder-247

**Comment by ConnorLinfoot** [comment]
Hey,

We've just updated the API to add a new endpoint that returns the data for all the products in a single request. We also swapped the buy + sell values so they are correct.

You can find the endpoint documentation [here](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/skyblock/bazaar.md).
