### ISSUE TITLE
"status" endpoint doesnt show if player is in limbo or not

### ISSUE THREAD

**Issue by KrUtOy228omg** [HypixelDev/PublicAPI#208]
Current '/status' endpoint doesnt show if player is in limbo, it returns LOBBY in both cases.
Like `{"success":true,"session":{"online":true,"gameType":"TNTGAMES","mode":"LOBBY"}}`, even if player is in limbo.

**Comment by ConnorLinfoot** [comment]
The status method uses the last server of the player to determine their location. Because limbo isn't an actual server it's not easily possible for us to update this to include limbo. The server provided is also where they will be sent when leaving limbo.

**Comment by KrUtOy228omg** [comment]
Ok so which method I should use to check for limbo?

**Comment by puppy0cam** [comment]
You cannot check for this. Limbo does not technically exist.
