### ISSUE TITLE
Add an productID=ALL to bazaar api

### ISSUE THREAD

**Issue by Fastloadd** [HypixelDev/PublicAPI#209]
I am currently in the process of making an spreadsheet which uses the bazaar api, but one problem that i am facing is that i have to make around 200-300 api requests to get all current instant sell and instant buy values. So i would like to have an feature added called product=ALL instead of for example productID=BONE. When you use productID=ALL you get to see the current InstantSell price ,the current InstantBuy price and the highest and lowest price of every item this day.

**Comment by yavkata999** [comment]
> 
> 
> I am currently in the process of making an spreadsheet which uses the bazaar api, but one problem that i am facing is that i have to make around 200-300 api requests to get all current instant sell and instant buy values. So i would like to have an feature added called product=ALL instead of for example productID=BONE. When you use productID=ALL you get to see the current InstantSell price ,the current InstantBuy price and the highest and lowest price of every item this day.

System.out.println(" https://en.wikipedia.org/wiki/For_loop");

**Comment by puppy0cam** [comment]
There's no need to be sarcastic. Everyone starts from somewhere and a public API for a video game is a great way to introduce someone into programming.

**Comment by RogiJAG** [comment]
> > I am currently in the process of making an spreadsheet which uses the bazaar api, but one problem that i am facing is that i have to make around 200-300 api requests to get all current instant sell and instant buy values. So i would like to have an feature added called product=ALL instead of for example productID=BONE. When you use productID=ALL you get to see the current InstantSell price ,the current InstantBuy price and the highest and lowest price of every item this day.
> 
> System.out.println(" https://en.wikipedia.org/wiki/For_loop");

He's not asking for a programming how-to. He is looking for a way to do it that doesn't require 200+ api requests.

**Comment by prajaybasu** [comment]
> > I am currently in the process of making an spreadsheet which uses the bazaar api, but one problem that i am facing is that i have to make around 200-300 api requests to get all current instant sell and instant buy values. So i would like to have an feature added called product=ALL instead of for example productID=BONE. When you use productID=ALL you get to see the current InstantSell price ,the current InstantBuy price and the highest and lowest price of every item this day.
> 
> System.out.println(" https://en.wikipedia.org/wiki/For_loop");

Please don't bring Hypixel forum cringe to GitHub. People want a way to get multiple Bazaar products at once and that may or may not be beneficial for the developers and Hypixel both. Nobody on here is asking for basic stuff. Don't comment useless stuff you don't have anything to contribute.

**Comment by jonese1234** [comment]
I think a better more Restful way would allow for an array of inputted ids rather than get all

**Comment by ConnorLinfoot** [comment]
Hey,

We've just updated the API to add a new endpoint that returns the data for all the products in a single request. We also swapped the buy + sell values so they are correct.

You can find the endpoint documentation [here](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/skyblock/bazaar.md).
