### ISSUE TITLE
Using multiple API keys

### ISSUE THREAD

**Issue by prajaybasu** [HypixelDev/PublicAPI#215]
Is pooling multiple API keys allowed (using API key "donations") to 'bypass' the limit? I want to make a service that checks prices, updates the cache and goes to sleep. I would like for it to go to sleep (serverless) instead of waiting on the API limit to reset.

P.S: It would be great if the Hypixel API supported HTTP/2 and used a per-day or per-hour limit instead. That would greatly improve the efficiency of all the bazaar/auction house mass queries.

**Comment by ConnorLinfoot** [comment]
Hey,

We've just updated the API to add a new endpoint that returns the data for all the products in a single request. We also swapped the buy + sell values so they are correct.

You can find the endpoint documentation [here](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/skyblock/bazaar.md).
