### ISSUE TITLE
Incorrect Sell Values

### ISSUE THREAD

**Issue by Chazza** [HypixelDev/PublicAPI#218]
Hi there,

It seems the sell value for each bazaar product is still incorrect when reflected ingame, while the buy price now seems to be fixed.

For example the Super Compactor 3000 shows as 404k coins but 143k sell.

**Comment by Chazza** [comment]
Another example is;
```
"buy_summary": [],
"quick_status": {
"productId": "ENCHANTED_CARROT_ON_A_STICK",
"sellPrice": 1920.4448160535117,
"sellVolume": 21727,
"sellMovingWeek": 0,
"sellOrders": 41,
"buyPrice": 0,
"buyVolume": 0,
"buyMovingWeek": 0,
"buyOrders": 0
}```

**Comment by ConnorLinfoot** [comment]
The data provided comes directly from the game, I'm not sure if this is still an issue but if so it would be a SkyBlock bug rather than the API itself.
