### ISSUE TITLE
Historical data in new Bazaar endpoint

### ISSUE THREAD

**Issue by LeaPhant** [HypixelDev/PublicAPI#220]
The new bazaar endpoint omits historical data which is probably due to the amount of data. Since the old endpoints are gonna be deprecated will there be no way to access this data anymore?

**Comment by Plancke** [comment]
That's most likely what's going to happen, if you want to display the changes over time you should keep track of it locally instead and request the data periodically which should be a lot easier now that it's all condensed in the single request.
