### ISSUE TITLE
Murder Mystery - Duplicated Data

### ISSUE THREAD

**Issue by Picsou993** [HypixelDev/PublicAPI#221]
There are a lot of data which are duplicated with 2 different keys in Murder Mystery.

- `kills_as_infected` with `kills_as_infected_MURDER_INFECTION`
- `kills_as_survivor` with `kills_as_survivor_MURDER_INFECTION`
- `longest_time_as_survivor_seconds` with `longest_time_as_survivor_seconds_MURDER_INFECTION`
- `quickest_detective_win_time_seconds` with `quickest_detective_win_time_seconds_MURDER_CLASSIC`
- `quickest_showdown_win_time_seconds` with `quickest_showdown_win_time_seconds_MURDER_SHOWDOWN`
- `survivor_wins` with `survivor_wins_MURDER_INFECTION`
- `total_time_survived_seconds` with `total_time_survived_seconds_MURDER_INFECTION`
Moreover, for all of them it is possible to add the maps name before the modes name (eg: `kills_as_infected_ancient_tomb` with `kills_as_infected_ancient_tomb_MURDER_INFECTION`)

We can see it easily if we sort the Murder Mystery Result on alphabetical order.

PS: The Total Time Survived returned by `total_time_survived_seconds` (and  so `total_time_survived_seconds_MURDER_INFECTION`) is not the total time so the sum from all maps but the maximum between all maps. This issue also leads the Lobby Leaderboard to be innacurate.

**Comment by mdashlw** [comment]
There is more much than that, but it won't get changed because this is how it's stored in the database and handled internally.
For example, `kills_as_infected` is a general murder mystery stat that can be used by any mode, field itself contains a sum of `kills_as_infected` in all modes, but in fact this stat is only used by infection mode leading to `kills_as_infected` and `kills_as_infected_MURDER_INFECTION` being equal.

**Comment by ConnorLinfoot** [comment]
The above is correct and there is a lot like this due to how games store their data.

**Comment by Picsou993** [comment]
What about the second part of the issue about `total_time_survived_seconds` which is not the total time so the sum but the max of the time on all maps?

**Comment by puppy0cam** [comment]
> What about the second part of the issue about `total_time_survived_seconds` which is not the total time so the sum but the max of the time on all maps?

This is not a problem with the API and is something to be fixed ingame.
