### ISSUE TITLE
Skyblock Collection contains Mystery Rabbit Pet Recipe twice

### ISSUE THREAD

**Issue by Flachdachs** [HypixelDev/PublicAPI#223]
The Mystery Rabbit Pet Recipe is listed twice in the "unlocks" section of the collection data. This is maybe not an API issue, because in-game you can also see this recipe listed two times.

**Comment by shadowtime2000** [comment]
Yes I agree this is not an API issue, but it is an issue with the Hypixel Skyblock system. Though, I cannot seem to find an API endpoint for collections.

**Comment by Flachdachs** [comment]
@shadowtime2000, see [resources documentation](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/resources.md).

**Comment by ConnorLinfoot** [comment]
If this is still an issue please report it to the game devs via https://hypixel.net/bugs as this does seem like its a game related issue.
