### ISSUE TITLE
global property for throttle response

### ISSUE THREAD

**Issue by mdashlw** [HypixelDev/PublicAPI#224]
Some time ago we had a "global" property = True if it's a global throttle, like this:
```json
{
  "success": false,
  "cause": "Global throttle",
  "throttle": true,
  "global": true
}
```
So now it's not a thing. Is it possible to get it back, because checking that is better than comparing "cause" that can potentially change at any time?

**Comment by ConnorLinfoot** [comment]
This was fixed but we seem to have forgotten to close this issue at the time.
