### ISSUE TITLE
ranked skywars is missing in /leaderboards

### ISSUE THREAD

**Issue by mdashlw** [HypixelDev/PublicAPI#225]
It's just not here, while "count" says there are 14 players
![image](https://user-images.githubusercontent.com/34678047/80860723-55b05000-8c72-11ea-9fb4-47437ada4139.png)

**Comment by mdashlw** [comment]
Seems to be fixed.

**Comment by mdashlw** [comment]
Seems to be broken again.

**Comment by mdashlw** [comment]
Bumping because the issue still persists. It seems that every season it has to be fixed manually. If we're not getting an automatic system, could you at least fix it right now?
cc @ConnorLinfoot

**Comment by ConnorLinfoot** [comment]
We're not sure what causes it to break, and we don't do anything that we know of that fixes this. It's not currently been investigated due to it being a low priority issue.

**Comment by ConnorLinfoot** [comment]
This issue should be resolved now, the ranked leaderboard should now update to the new season within an hour of it starting.
