### ISSUE TITLE
Player is friends with themselves

### ISSUE THREAD

**Issue by TheNullicorn** [HypixelDev/PublicAPI#230]
In the API, the player RobityBobity has a friendlist entry with themselves as both the sender and the receiver.
```
{
  "success": true,
  "records": [
    {
      "_id": "547222140cf2aa7fb7dcb85c",
      "started": 1416765972747,
      "uuidReceiver": "7071d9256663496681b3ce14ff325e6a", <---
      "uuidSender": "7071d9256663496681b3ce14ff325e6a" <--- Same sender and receiver UUID
    },
    ...
  ]
}
```
https://api.hypixel.net/friends?uuid=7071d9256663496681b3ce14ff325e6a&key=KEY
(This is also apparent on [Plancke](https://plancke.io/hypixel/player/friends/7071d9256663496681b3ce14ff325e6a))

**Comment by builder-247** [comment]
Yes, it was possible to friend yourself for a while  when the friends system was introduced.

**Comment by TheNullicorn** [comment]
> Yes, it was possible to friend yourself for a while when the friends system was introduced.

Okay thank you. Is it unlikely these entries will be purged from the database?

**Comment by Minikloon** [comment]
It is unlikely.
