### ISSUE TITLE
[Skyblock] Auction doesn't use Item IDs

### ISSUE THREAD

**Issue by test137E29B** [HypixelDev/PublicAPI#236]
I noticed recently that while the Bazaar uses Item IDs, the Auction API does not, which makes it much, much harder to match certain items between.

Is it anticipated that Auctions will be updated to the Item ID system that the Bazaar uses in the future? I could understand if not due to items being much more "unique" in the auction house with enchantments etc.

**Comment by puppy0cam** [comment]
I believe you can obtain the item ID from the NBT data

**Comment by Minikloon** [comment]
The Auction House was created just a bit before the item id system (so a long, long time ago).
It accepts Minecraft item stacks directly.

If you check the item's nbt it will contain the item id somewhere in there.
