### ISSUE TITLE
stats.SkyBlock.account.selected_profile does not exist

### ISSUE THREAD

**Issue by EdwinCRL** [HypixelDev/PublicAPI#238]
Recently I opened an issue about adding a selected_profile entry under the player endpoint, and received this response "It's available in stats.SkyBlock.account.selected_profile". 

![unnamed](https://user-images.githubusercontent.com/19798018/81878520-a8233200-95cb-11ea-8fa5-40ff4c308c76.png)

stats.SkyBlock.account.selected_profile does not exist.

**Comment by Picsou993** [comment]
Reference of #235.

**Comment by Omega172** [comment]
`skyblock/profiles?uuid=${UUID}
profiles.profile.selected
`

Worked for me

**Comment by ConnorLinfoot** [comment]
Closing this issue as we did add the selected boolean to the profiles endpoint to provide this information
