### ISSUE TITLE
MVP player

### ISSUE THREAD

**Issue by mdashlw** [HypixelDev/PublicAPI#239]
So there's a player 84146977443f4f21919ac265e8677002 called "MVP" that has the following data in the database:
```py
{'_id': '54fb26f9b70f47852738fae7', 'uuid': '84146977443f4f21919ac265e8677002', 'vanityTokens': 10000, 'displayname': {}}
```
Is it possible this player can get purged from db, because it essentially has no data and breaks a lot of stuff that relies on normal player schema. Like 'displayname' here is an object for some reason instead of string

**Comment by Plancke** [comment]
The document has been removed, thanks.
