### ISSUE TITLE
Session Endpoint

### ISSUE THREAD

**Issue by bsquidwrd** [HypixelDev/PublicAPI#24]
What is a usecase for getting a players session? Right now if I get mine I just get the following:

```json
{
  "session": null,
  "success": true
}
```

**Comment by KevyPorter** [comment]
https://api.hypixel.net/session?key=########-####-####-####-############&uuid=af2d221ba92f47618ab4e9b73e66447b

Will only return something other than null when a player is ingame

```json
{
    "session":
    {
        "_id":"568389b4c8f27fc302b0a5e3",
        "gameType":"SURVIVAL_GAMES",
        "server":"mini8G",
        "players":
        [
            "d59bd49a84424e59a5c6ed3056083b1e",
            "1a701652b91c49c2a33447f2fbb55412",
            "af2d221ba92f47618ab4e9b73e66447b",
            "93e27761b8bf4ab1a4e1fb003344a70f"
        ]
    },
    "success":true
}
```

**Comment by bsquidwrd** [comment]
Perfect! Tried it when I was in a game and it works wonderful. Thank you very much :)
