### ISSUE TITLE
Changes to /key ?

### ISSUE THREAD

**Issue by ChimneySwift** [HypixelDev/PublicAPI#240]
Old response content (as shown in the documentation) is different to the current response content

Old content:
```
{
    "key": "", 
    "ownerUuid": "", // not dashed
    "totalQueries": 142028083,
    "queriesInPastMin": 68
} 
```

Current:
```
{
    "key": "", 
    "owner": "", // is dashed
    // totalQueries removed?
    "queriesInPastMin": 68
} 
```

Main reason for opening this issue is to enquire as to why totalQueries was removed.

**Comment by Plancke** [comment]
This was accidentally removed during some changes to how we handle the keys, we've added it back.
