### ISSUE TITLE
Inconsistent formatting in semi-static resource

### ISSUE THREAD

**Issue by db1218** [HypixelDev/PublicAPI#241]
Kinda small, but in the semi-static resources for quests (http://api.hypixel.net/resources/quests), all quest descriptions follow "[Daily|Weekly] Quest: ...", apart from Bedwars which follow "[Daily|Weekly]: ..." could this be fixed so that bedwars follows the same format as the others?

**Comment by ConnorLinfoot** [comment]
This has been fixed and will update when the API next reloads these resources, likely in the next day or so.
