### ISSUE TITLE
Add bin flag to skyblock/auction and skyblock/auctions

### ISSUE THREAD

**Issue by zikeji** [HypixelDev/PublicAPI#242]
Presently there is no way to ascertain if it's a BIN auction or not in the data returned by those endpoints. Would be nice to have a simple `bin: true` in the data.

**Comment by ConnorLinfoot** [comment]
From what I can see the update already added a `bin` flag to the auctions. You can use this and the `starting_bid` value for BIN auctions.

**Comment by zikeji** [comment]
That surprising. I see a `bin: true` field now, it didn't exist when I opened this issue 4 hours ago. I'm glad to see it was resolved so quickly.
