### ISSUE TITLE
Add knownAliases for staff hidden in api

### ISSUE THREAD

**Issue by mdashlw** [HypixelDev/PublicAPI#244]
For staff that hid themselves from the api, there's no known aliases. I don't think it's any sensitive, so would be nice if it was added along with knownAliasesLower.

**Comment by db1218** [comment]
> 
> 
> added along with knownAliasesLower.

Do you mean lower cased? If so, why is this needed?

**Comment by TheNullicorn** [comment]
knownAliases would be nice, but they're really the only ones who need the lowercase version (for indexing).

**Comment by mdashlw** [comment]
> Do you mean lower cased? If so, why is this needed?

For consistency? If there's `knownAliases` for staff, so why not `knownAliasesLower`.

**Comment by ConnorLinfoot** [comment]
This is not something we wish to add. We have selected specific fields to be visible for staff that have their API data hidden.

**Comment by TheNullicorn** [comment]
> This is not something we wish to add. We have selected specific fields to be visible for staff that have their API data hidden.

A couple of questions about this,
- How do we determine if a staff member has some of their regular api data hidden? `settings.apiSession` and `settings. apiRecentGames` both refer to their respective endpoints, so what determines whether a staff member will only have whitelisted fields in their response?
- Would you be able to provide us with the list of fields that are whitelisted for those staff members? This might make it easier to create a more standard player object for players in general.

**Comment by mdashlw** [comment]
> How do we determine if a staff member has some of their regular api data hidden?

I do it by checking if the player doesn't have both `knownAlises` and `stats` fields. Not very reliable, because there can be a normal player without these, so maybe a new field can be added saying that this data is reduced?

> Would you be able to provide us with the list of fields that are whitelisted for those staff members?

Well you could request such player and see yourself: `uuid`, `displayname`, `playername`, `rank`, `packageRank`, `newPackageRank`, `socialMedia`, `firstLogin`.
