### ISSUE TITLE
Player without displayname

### ISSUE THREAD

**Issue by mdashlw** [HypixelDev/PublicAPI#247]
There's a player "Daniel" with the following data:
```json
{
  "_id":"571d54f0ee21327430fb120d",
  "uuid":"bcff27554f314ad187bcce5c5917e399",
  "newPackageRank":"MVP",
  "levelUp_MVP":1461540107827,
  "stats":{
    "SkyWars":{
      "skywars_chests":50
    },
    "Bedwars":{
      "bedwars_lunar_boxes":50
    }
  }
}
```
Can this document be deleted? It was generated back in 2016. If not, please set "displayname" to "Daniel" at least.

**Comment by ConnorLinfoot** [comment]
We don't guarantee that players have all the fields outside of the UUID. If a displayname is unavailable we recommend falling back to using Mojangs API to handle this.
