### ISSUE TITLE
Add RateLimit Headers to All Responses

### ISSUE THREAD

**Issue by Dance-Dog** [HypixelDev/PublicAPI#248]
Right now, the only way of checking your limit and remaining queries is by sending a request to /key, which has the potential to be throttled. It would be helpful if every response was sent with a **RateLimit-Limit** header (max queries per min) and a **RateLimit-Remaining** header (remaining queries in next min) so that we don't have to waste a query just to find out how many we have left. On top of that, it would be useful for throttle responses to send a **Retry-After** header indicating how long the key is throttled for (as mentioned in [RFC6585](https://tools.ietf.org/html/rfc6585#section-4)).

EDIT: Not Retry-After, not Reply-After

**Comment by puppy0cam** [comment]
That's Retry-After not Reply-After.

**Comment by Dance-Dog** [comment]
Fixed, thanks

**Comment by LJNeon** [comment]
Note that all headers would need `X-` at the start of the name to be standardized, and that the `X-RateLimit-Reset` is missing in this suggestion. Still an amazing idea that would make using the API incredibly easier.

**Comment by TheNullicorn** [comment]
> Note that all headers would need `X-` at the start of the name to be standardized, and that the `X-RateLimit-Reset` header is missing in this suggestion. Still an amazing idea that would make using the API incredibly easier.

Actually, the "X-" prefix is deprecated as of [RFC6648](https://tools.ietf.org/html/rfc6648).

**Comment by Plancke** [comment]
We've added all 4 headers to responses as of last night.

```
      RateLimit-Limit: 120
      RateLimit-Remaining: 119
      RateLimit-Reset: 60
      Retry-After: 60
```

**Comment by LJNeon** [comment]
@Plancke My apologies for the additional question, but your comment seems to imply that `Retry-After` is present in all headers instead of only throttled (status code 429), and that it may be the total time until reset, instead of the remaining time. Would you mind clarifying both of those points?

**Comment by Plancke** [comment]
It was present on all requests until now, sorry about that. `Retry-After` and `RateLimit-Reset` are implemented as remaining time until requests will be able to go through again, though this is not strictly guaranteed it should be a decent indicator.

**Comment by LJNeon** [comment]
`RateLimit-Reset` should be a UTC unix timestamp for when the current ratelimit is reset, not the remaining time until said reset. Also, `Retry-After` should be the only ratelimit header present on 429 responses. Thank you for the quick fixes though!

**Comment by TheNullicorn** [comment]
> `RateLimit-Reset` should be an unix timestamp for when the current ratelimit is reset, not the remaining time until said reset.

It's only a draft, but according to [this](https://tools.ietf.org/id/draft-polli-ratelimit-headers-00.html#rfc.section.3.3) document, either is acceptable. You could use the `Date` header to get the reset time yourself.

**Comment by mdashlw** [comment]
How headers gonna look like in case of global throttle?

**Comment by TheNullicorn** [comment]
> How headers gonna look like in case of global throttle?

I just managed to grab the headers for one of the global throttles. Just like with a normal throttle, the response code is 429 and the only ratelimit-related header is `Retry-After` (which appears to run on the same 60-second clock as usual). After that amount of time passed, the global throttle went away.

**Comment by Kuba314** [comment]
Is this in the docs yet? Didn't see it anywhere.
