### ISSUE TITLE
[Suggestion] Include "Unlocked %" per achievement in semi-static resource

### ISSUE THREAD

**Issue by db1218** [HypixelDev/PublicAPI#253]
In-game there is a percentage for each achievement stating the percentage of players that have unlocked that achievement, shown below:
![image](https://user-images.githubusercontent.com/56447862/83787407-a5c46d00-a68b-11ea-9f5a-996fe7f87516.png)

Could this added to the achievements semi-static resource?

e.g.
```json
{
    "achievements": {
        "tntgames": {
            "one_time": {
                "NO_YOU": {
                    "points": 5,
                    "name": "No You",
                    "description": "Tag a player 15 times in one round of TNT Tag and have them die",
                    "rarity": 0.003
                }
            }
        }
    }
}
```

I'm not sure how this value is stored server side, but the only issue I can see from my end value is this value is likely re-calculated more often than the current semi-static data.

**Comment by mdashlw** [comment]
Doesn't really fit into /resources/achivements. This data is not static like every thing in achievements resource, and needs to be calculated. Possibly a new endpoint could be introdued: /achivements that returns static data from resource + "rarity"

**Comment by ConnorLinfoot** [comment]
We've added these percentages to the achievements endpoint and they will be included when possible to one time achievements, they will not be included for legacy achievements. 

The fields added are `gamePercentUnlocked` and `globalPercentUnlocked` 😄

**Comment by db1218** [comment]
> We've added these percentages to the achievements endpoint and they will be included when possible to one time achievements, they will not be included for legacy achievements.
> 
> The fields added are `gamePercentUnlocked` and `globalPercentUnlocked` 😄
First off, THANK YOU
also just to confirm, is `gamePercentUnlocked` the percentage of players who have completed the achievement who have entered the lobby for that game, and `globalPercentUnlocked` is the percentage of all players who have logged onto the network?

**Comment by ConnorLinfoot** [comment]
> > We've added these percentages to the achievements endpoint and they will be included when possible to one time achievements, they will not be included for legacy achievements.
> > The fields added are `gamePercentUnlocked` and `globalPercentUnlocked` 😄
> 
> First off, THANK YOU!
> Also just to confirm, is `gamePercentUnlocked` the percentage of players who have completed the achievement who have entered the lobby for that game, and `globalPercentUnlocked` is the percentage of all players who have logged onto the network?

This is correct, there is some extra filters on our end such as not including players who haven't logged in for a long time (we're talking many years) but beyond that yes.

**Comment by db1218** [comment]
> 
> 
> > > We've added these percentages to the achievements endpoint and they will be included when possible to one time achievements, they will not be included for legacy achievements.
> > > The fields added are `gamePercentUnlocked` and `globalPercentUnlocked` 😄
> > 
> > 
> > First off, THANK YOU!
> > Also just to confirm, is `gamePercentUnlocked` the percentage of players who have completed the achievement who have entered the lobby for that game, and `globalPercentUnlocked` is the percentage of all players who have logged onto the network?
> 
> This is correct, there is some extra filters on our end such as not including players who haven't logged in for a long time (we're talking many years) but beyond that yes.

neat thank you,

finally, would it be possible to give a rough figure of the total player base these global percentages are taken from (I have a request to use this figure to calculate how many players have completed each achievement), I'd ask for a figure for per game too but that sounds like more work.

ps. no worries if no figure can be supplied, really appreciate this being added :)
