### ISSUE TITLE
[Issue] GameCounts endpoint response is inconsistent

### ISSUE THREAD

**Issue by ThomDeMeulder** [HypixelDev/PublicAPI#255]
Hi!

I was messing around a bit with the /gameCounts endpoint and noticed that not always all modes are returned upon requesting all games. Sometimes multiple modes are missing, I noticed this the most while looking at Skywars. I also noticed that there are sometimes games in the response that don't exist / are not active at the time I was making the API request. 

To take Skywars as an example, in [this](https://gyazo.com/3df411d6fe3de81c81dce74a96c26134) screenshot you can see that I only have 10 modes. In [this](https://gyazo.com/4ade193c019e4e44b85a0df5c372fff4) screenshot I suddenly have 13 modes, the second screenshot was taken a couple of seconds after the first one. I also have a mode that doesn't exist to my knowledge called _solo_insane_hunters_vs_beasts_. The mode _teams_insane_tnt_madness_ is also included in the second screenshot while this game is at the time not joinable for players. Only rush and slime are in the laboratory NPC visible. It isn't a problem if you ask me that TNT madness is included, but that only solo is included in the response is a bit weird.

Just as a note, I saw this also happen with other games, arcade as an example. But this was by far less inconsistent than Skywars.

**Comment by Picsou993** [comment]
Hi, the gameCounts endpoint returns modes that have at least 1 player on it.
Also, it is possible to join these SkyWars Laboratory Modes using the MVP++ Private Games feature and this is why they can be seen even if they are currently not in the NPC.

**Comment by ThomDeMeulder** [comment]
> Hi, the gameCounts endpoint returns modes that have at least 1 player on it.
> Also, it is possible to join these SkyWars Laboratory Modes using the MVP++ Private Games feature and this is why they can be seen even if they are currently not in the NPC.

Ah, that explains a lot. Thanks!

I would like to request to change this behaviour though, as we don't have any endpoint with all the modes listed. So what I would like to request is the following, it would be very helpful to either have an endpoint with a list of all modes or have modes with zero players still be visible in the response.

Why I'm requesting this is so it's easier to keep track of the player count over a bigger period of time without having to manually add/remove modes. If a mode would get removed I currently can't know whether or not it has zero players or has been removed. Which would be handy to know to clean-up data.

**Comment by mdashlw** [comment]
There's already an issue about a full list of modes: #197
