### ISSUE TITLE
Define "abuse"

### ISSUE THREAD

**Issue by TheNullicorn** [HypixelDev/PublicAPI#257]
This is an extension of #229.

Recently, the API has been automatically resetting keys that are determined to be linked to abuse (or if it was already a thing, it's become significantly more aggressive). The problem is that "abuse" isn't officially defined anywhere, so when a key gets reset, it's impossible for us to know if we did something wrong or if it was a false-positive.
As of now, the only example of abuse we have is...
> If your API key was reset it could be the case that the key was either compromised or being abused in some way, such as multiple keys being used.
which appears to be only one example.  

Could we get a more detailed definition of "abuse" so that users don't have to worry about their keys resetting for breaking a rule they didn't know existed? #234 aims to clarify this, but an official answer would be very helpful.  

Some questions I have:
- Is repetitively throttling a key considered abuse?
- Is using the **same key** for **different applications** considered abuse?
- Is using **different keys** for **different applications** considered abuse?

*Related: #229, #234, https://hypixel.net/threads/2988601*

**Comment by JSalenger** [comment]
I think an especially important point to clarify is the **different key** for **different application** problem. They may still be flagged as abuse though if multiple applications are run on the same server/ip/vps I don't know how abuse is detected. Also what constitutes a different application if I build two discord bots and a website is that three applications or two?

**Comment by ConnorLinfoot** [comment]
Hitting the maximum requests for an API key will not reset your key. We don't wish to discuss exactly what triggers abuse detection as it will lead to people working around the system instead. But anything that includes bypassing the limitations we set is a pretty clear example of abuse.

However, we can say that our values to trigger the abuse detection are pretty relaxed overall to include usages of multiple applications on a single server. If you feel you're being incorrectly hit feel free to open a support ticket. https://support.hypixel.net
