### ISSUE TITLE
[SUGGESTION] Game ID to recentGame Endpoint

### ISSUE THREAD

**Issue by KodaKay** [HypixelDev/PublicAPI#258]
Request: 
Add game ID to recentGames endpoint.

Reasoning:

1. At the end of a game, you can see the stats of your recent game eg: Bedwars, Skywars, UHC etc. However you can only see it if you go to lobby and wait for it too popup in chat. This doesn't always happen and forces you to miss out on this information which some people like. 

2. If you've just finished a sweaty game and want to see your stats but your party leader warps you into another game before you can get the message, you have no way to see how well you did apart from comparing outdated and refreshed stats on external sites like Plancke or sk1er.

3. If it's not possible to have all recentGame's game ids in the api, It would be nice to have the last 10 at minimum since those will be what most people are interested in compare to the last 100.

**Comment by ConnorLinfoot** [comment]
This data isn't tracked for each game and also isn't easily accessible to the API service. At this time we do not plan to include this.
