### ISSUE TITLE
Booster gameType is floating-point number

### ISSUE THREAD

**Issue by TheNullicorn** [HypixelDev/PublicAPI#262]
There's currently a booster in the API that has it's `gameType` property set to a floating-point number (`56.0` - Classic Games) rather than an integer. This isn't a huge issue, but it does cause an exception to be thrown in the Java API because it can't be parsed as an integer.

This particular booster also has a property called `originalGameType` with a value of `4.0` (Paintball). Were Classic Game boosters all merged into one at some point, causing this? If so, it seems that some part of the conversion is broken.

The Booster:
```json
{
    "_id": "57be54b4c8f25506e609e855",
    "purchaserUuid": "262a962a69414313bb35200b741b3a4a",
    "amount": 2.0,
    "originalLength": 3600,
    "length": 3600,
    "gameType": 56.0,
    "originalGameType": 4.0,
    "dateActivated": 1592071334290
},
```

![Screen Shot](https://user-images.githubusercontent.com/64789500/84578350-5caea000-ad92-11ea-9fb3-b354a406f8b7.png)

**Comment by ConnorLinfoot** [comment]
Seems like this issue resolved itself due to the booster ending. I also can't see any boosters active right now with the same issue, feel free to re-open if it pops up again.

**Comment by ConnorLinfoot** [comment]
Seems to have been some legacy boosters that were converted. I've fixed any double gameTypes in the database so this should no longer be an issue.
