### ISSUE TITLE
Status method and staff members.

### ISSUE THREAD

**Issue by Picsou993** [HypixelDev/PublicAPI#264]
Staff members are visible on the _[status method](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/status.md)_ if they have it enabled in their privacy settings in game (like the other players).

_Edit:_
**PS:** In the case it is intended, then there is another issue with it which is that if a staff member disabled its API, he his still visible with this method.

**Comment by mdashlw** [comment]
I'm pretty sure this is intended. If they're not fine with that, they can disable it in the settings like all players.

**Comment by TheNullicorn** [comment]
Now that we have the ability to toggle certain API responses, I don't see why staff should have it force-disabled. Perhaps they could have it off by default, so if `settings.apiSession` is not present, default to true for normal players and false for staff members and youtubers.

**Comment by ConnorLinfoot** [comment]
The behaviour mentioned is intended of the API.
