### ISSUE TITLE
KeyReply.Key#getOwnerUuid returns null every time

### ISSUE THREAD

**Issue by HydroPage90** [HypixelDev/PublicAPI#266]
Pretty self explanatory. `HypixelAPI#getKey().get().getRecord().getOwnerUuid()` returns `null` each and every time I attempt it. I'm using `CompletableFuture#get()` as a test, but each resolution method proves to yield the same result. I manually pasted `api.hypixel.net/key?key=(the target key)` into my browser, and the owner UUID showed up in the raw JSON

**Comment by HydroPage90** [comment]
By the way, I just forked the repository and made a `Main` class to test with. I can confirm the problem is not my version, since the latest version of the repository returned `null` as well

**Comment by TheNullicorn** [comment]
At some point the "ownerUuid" field was renamed to "owner", but the change never got made in the Java API. I just opened a pr to fix this.

**Comment by HydroPage90** [comment]
If I was the one to point this out to you, I’m glad to have been of
assistance
