### ISSUE TITLE
Bazaar error in java API

### ISSUE THREAD

**Issue by hannibal00212** [HypixelDev/PublicAPI#274]
https://github.com/HypixelDev/PublicAPI/blob/a60f273f28996a87cca69906739936acc9c0c06a/Java/src/main/java/net/hypixel/api/reply/skyblock/BazaarReply.java#L113

The field sellMovingWeek should be from type long instead of int since the quantity of stuff sold is bigger than the biggest possible int value (2147483647). Currently this just happen with enderpears sold.
The same problem can occur with the field buyMovingWeek.

**Comment by ConnorLinfoot** [comment]
If you wish you can open a PR with the required change and we'd be happy to merge it.
