### ISSUE TITLE
Server side calculation for your crit chance and other stats (Skyblock)

### ISSUE THREAD

**Issue by Zermusic0** [HypixelDev/PublicAPI#275]
I think that there should be a server-side calculation for the following stats in skyblock
-Health
-Crit chance
-Crit damage
-Attack speed
-speed
-strength
-intelligence
-pet luck 

The reasoning behind this is to make it easier for people to develop bots using these stats. Making bots for these stats is hard due to a large amount of time and coding that it takes to take effect for different armor pieces. Using the sky.lea site there is over 400 lines of code just to calculate these stats. I think that this should be server-side and shouldn't have to be done by the user

**Comment by mdashlw** [comment]
+1 It would make sense to do this on server, because there's so much stuff that needs to be taken into account, and hypixel developers know better how to calculate everything properly.
Possibly it should be controlled by new query param "withCounters" for /skyblock/profile

**Comment by ConnorLinfoot** [comment]
The API itself doesn't have any of the information required to calculate this information. It would require us to include a lot of the SkyBlock balancing values into the service and keep those up to date. Thus this is not something we wish to do.
