### ISSUE TITLE
Not on JitPack anymore

### ISSUE THREAD

**Issue by HydroPage90** [HypixelDev/PublicAPI#276]
Hey, what's going on here? I tried compiling my program today, and it stated that this dependency wasn't on JitPack anymore. And it isn't. If I look it up on JitPack, it doesn't show any commits. Even if I go to the readme file of this repository, the "jitpack" button isn't there under "Usage". Are you guys migrating? If so, how long will this last?

**Comment by TheNullicorn** [comment]
It's an issue on [JitPack's end](https://twitter.com/jitpack/status/1279033082239123456). Hopefully it'll be back soon

**Comment by HydroPage90** [comment]
We're good
