### ISSUE TITLE
Suggested Dungeons Addition

### ISSUE THREAD

**Issue by skyblockz** [HypixelDev/PublicAPI#278]
Here are some suggestions about what should be added to the API

1. Player's current unlocked floors, selected class, individual class skills
2. Player's essence inventory
3. ~~Player's dungeon best race time, and completed count~~ [Added already](https://i.imgur.com/JcscyWX.png)

**Comment by shadowtime2000** [comment]
I believe you can already view the player's dungeon best race time, as you can see that on [sky.lea.moe](https://sky.lea.moe/stats/milkchunks_/Blueberry)

**Comment by skyblockz** [comment]
> I believe you can already view the player's dungeon best race time, as you can see that on [sky.lea.moe](https://sky.lea.moe/stats/milkchunks_/Blueberry)
Apparently races got added earlier
https://i.imgur.com/JcscyWX.png

**Comment by ConnorLinfoot** [comment]
There is already an issue regarding dungeons #277, closing this as a duplicate
