### ISSUE TITLE
[Suggestion] api.hypixel.net/key?key=[YOURKEY] - shouldn’t count towards the 120/m limit

### ISSUE THREAD

**Issue by Eqrly** [HypixelDev/PublicAPI#279]
Title.

If you were to go to https://api.hypixel.net/key?key=[YOURKEY] and refresh the page you will see the queries within the last minute go up for each refresh.

Another solution or way to do this could be including it in the header as described in #248,
or adding it somewhere into all responses at the bottom or something.

Thank you 👍

**Comment by shadowtime2000** [comment]
I agree, but I cannot see an way that hitting that endpoint would actually be that useful it would need to be set to not count towards the 120/m limit.

**Comment by robere2** [comment]
> I agree, but I cannot see an way that hitting that endpoint would actually be that useful it would need to be set to not count towards the 120/m limit.

The biggest benefit is there's then no downside to checking how many more requests you can send until you're rate limited. This would be a non-issue if the API provided this information in headers, i.e. [IETF draft-polli-ratelimit-headers](https://tools.ietf.org/html/draft-polli-ratelimit-headers-03)

**Comment by ConnorLinfoot** [comment]
This endpoint still requires the data to be retrieved and is why it still counts as an API use. The better solution as stated would be the header which is already suggested in another issue.
