### ISSUE TITLE
[Guild Issue] Guild API Endpoint Inconsistency/Missing Documentation

### ISSUE THREAD

**Issue by AzureAaron** [HypixelDev/PublicAPI#280]
Before I start, **I'm aware there's already open issues like this**. I created this as an overall summary and go into further detail about the issues at hand.

Lately, I've noticed that there's inconsistencies and issues within the Guild API Endpoint which affect the accuracy of the data you intend to provide to the end-users of the API. I understand things aren't perfect but for the Guild API it's never consistent with the response that I should be getting.

### 1) Missing Documentation
If you query https://api.hypixel.net/guild?key=YOUR_KEY&id=5bb8dbe40cf2d46f5a5c5c21, you'll notice the documentation for the `"coins"` and `"coinsEver"` field is not present in the example response provided.

### 2) Inaccurate/Missing Daily Member GEXP.
I know there's already issues open about this; however I have added this here in hopes it will even get looked at as the other issues seem to be neglected.

When querying the Guild Endpoint; some member's in my guild seem to have missing, inaccurate and unorganized Daily GEXP Data such as one of my member's in this image. I get not all dates may be in order and that's not the big issue here, the issue is that there's *missing* fields/days where GEXP was earned as reported by "/g member" ingame and I'm sure **this is not intentional** as when you go to add up all of the member's Daily GEXP to get the Guild's overall Daily GEXP you can sometime underreport the amount of GEXP earned that day.

Here's an example of inaccurate/missing GEXP Data.
![image](https://user-images.githubusercontent.com/51387595/87508888-56843b80-c63e-11ea-9e03-103b37e9d562.png)
The ID of the Guild used in that screenshot is `5bb8dbe40cf2d46f5a5c5c21` AKA `The Wavy v2`.

At the time of writing this, there's 17 API Errors relating to GEXP inaccuracy within my guild (affects 17 unique UUIDs/People). To check this, make a JSON request to my guild or anyone really and run this in the browser console:
```js
body = JSON.parse(document.getElementsByTagName('pre')[0].innerHTML);
test = body.guild.members.filter(item => Object.keys(item.expHistory).length !== 7);
test.forEach(item => console.log(`Error: ${item.uuid}, Length: ${Object.entries(item.expHistory).length}`))
console.log("Number of API errors found: " + test.length)
```
That will return the number of API Errors present in the data along with the affected UUIDs.

**Comment by cpucuber** [comment]
It would be very helpful if they fixed these issues!

**Comment by mdashlw** [comment]
> you'll notice the documentation for the `"coins"` and `"coinsEver"` field is not present in the example response provided.

Coins are a concept of the legacy guild system, and thus undocumented on purpose, as you usually don't need them and it may be removed at any time.

**Comment by AzureAaron** [comment]
> > you'll notice the documentation for the `"coins"` and `"coinsEver"` field is not present in the example response provided.
> 
> Coins are a concept of the legacy guild system, and thus undocumented on purpose, as you usually don't need them and it may be removed at any time.

I agree, however this is apart of the response in the API and it should be documented with a note that it may be removed at any time.

**Comment by Eqrly** [comment]
Now we wait and see if both of these get fixed :D

**Comment by mdashlw** [comment]
> > > you'll notice the documentation for the `"coins"` and `"coinsEver"` field is not present in the example response provided.
> > 
> > 
> > Coins are a concept of the legacy guild system, and thus undocumented on purpose, as you usually don't need them and it may be removed at any time.
> 
> I agree, however this is apart of the response in the API and it should be documented with a note that it may be removed at any time.

I don't agree and it was me who removed the documentation for this, because deprecated stuff shall stay undocumented as you simply don't need it.

**Comment by shadowtime2000** [comment]
> > > > you'll notice the documentation for the `"coins"` and `"coinsEver"` field is not present in the example response provided.
> > > 
> > > 
> > > Coins are a concept of the legacy guild system, and thus undocumented on purpose, as you usually don't need them and it may be removed at any time.
> > 
> > 
> > I agree, however this is apart of the response in the API and it should be documented with a note that it may be removed at any time.
> 
> I don't agree and it was me who removed the documentation for this, because deprecated stuff shall stay undocumented as you simply don't need it.

Deprecated means it's no longer supported not unnecessary. The two skyblock bazaar product and list endpoints are deprecated yet the documentation is still there along with the note that those are deprecated endpoints.

**Comment by Kuba314** [comment]
Can we get a status update on why there still are errors such as entries missing in members' `expHistory`? And the wrong dates? How does it even happen, that 2020-01-31 can become 2020-02-31?

Was the bug found or did noone after almost 10 months find anything weird?

Or maybe the bug was found, but fixing it would break other things?

**Comment by Kenshayy** [comment]
Sometimes Im even getting errors multiple times a day because the API is returning the 31 of SEPTEMBER, which doesn't even exist.

**Comment by Plancke** [comment]
1) Coins for guilds are deprecated, it doesn't make sense to define a legacy field in documentation like that.
2) see https://github.com/HypixelDev/PublicAPI/issues/145#issuecomment-688327264
