### ISSUE TITLE
[Bug] Dummy item in API

### ISSUE THREAD

**Issue by SteveKunG** [HypixelDev/PublicAPI#282]
Dummy items shouldn't export though API, e.g. Accessory Bag with `Go Back arrow item`.
This happened on Potion/Fishing/Quiver Bag as well.

![image](https://user-images.githubusercontent.com/6128413/87875006-6ada8680-c9f8-11ea-8eb3-1d21d77c354a.png)

**Comment by ConnorLinfoot** [comment]
This isn't a bug of the API. The API serves the data as stored and SkyBlock stores these items in their respective menus.
