### ISSUE TITLE
[Suggestion] Auctions Api

### ISSUE THREAD

**Issue by TheBlackSnowman** [HypixelDev/PublicAPI#283]
With the auctions api containing a lot of data, it  would be useful to be able to query specific items, for example 

https://api.hypixel.net/skyblock/auctions?key=[API KEY]&item=[Item id]

it would make retrieving data a lot faster considering there's  usually 45+ pages of data to parse.

**Comment by ConnorLinfoot** [comment]
This would just shift the processing onto the API rather than locally, so this isn't something we want to implement.

**Comment by devonpmack** [comment]
You will save API processing because instead of receiving 45 requests you will only receive one.

**Comment by puppy0cam** [comment]
> You will save API processing because instead of receiving 45 requests you will only receive one.

They have to process 45 times the data for a single request.

**Comment by Michtdu** [comment]
also you can index item ids

you dont even have to let us search for items just get items of only one item id
that would be near instant and you cant tell me the 5 MB more ram you need for the indexing make up for the 3 GB banwith wasted for programs having to download 90 pages every minute
