### ISSUE TITLE
[BUG] Api not returning a valid response

### ISSUE THREAD

**Issue by KodaKay** [HypixelDev/PublicAPI#285]
From the 27-28th of July, the api has returned either "500 - Internal Error" or the Hypixel HTML. This happens after every 2-3 requests for about 1 second. 

I've tested this only on the "player" endpoint and it's been consistent for other people using the api too. Along with the api being slow and the endpoint consistently being down, it's really been effecting my projects. 

How to replicate:

1. Send 2 requests to the player endpoint
2. Send a 3rd requests and you will get 1 of the 2 invalid responses

**Comment by AzureAaron** [comment]
> From the 27-28th of July, the api has returned either "500 - Internal Error" or the Hypixel HTML. This happens after every 2-3 requests for about 1 second.
> 
> I've tested this only on the "player" endpoint and it's been consistent for other people using the api too. Along with the api being slow and the endpoint consistently being down, it's really been effecting my projects.
> 
> How to replicate:
> 
> 1. Send 2 requests to the player endpoint
> 2. Send a 3rd requests and you will get 1 of the 2 invalid responses

Yeah can confirm, these outages suck man I really wonder what's causing this though...
Maybe the increase in API Usage (Stats Bots, websites or overloaded) ?? It would be interesting to know why.....

**Comment by shadowtime2000** [comment]
I believe that SkyblockZ had to send out an announcement that SkyBotZ's commands won't work because they use the API.

**Comment by uwuplant** [comment]
confirming, same issues with Skyblock Simplified. all requests take over 10-15 seconds, and normally return either a 500/502. I have taken the bot down until this is resolved as it's becoming difficult to take care of all complaints regarding the API issues.

**Comment by TheNullicorn** [comment]
Likely linked to #286

**Comment by ConnorLinfoot** [comment]
This was due to an API outage that should no longer be an issue.
