### ISSUE TITLE
Allow for use of historical data

### ISSUE THREAD

**Issue by JSalenger** [HypixelDev/PublicAPI#287]
Could we have an endpoint or just a way to download historical bazaar data? Whether its just Minikloon adding an export to CSV option on stonks.gg or a new endpoint it'd be really useful. It doesn't make sense to me that this data isn't accessible anymore. I've been searching everywhere for it and even contacted many developers and none of them have it. I've been compiling it by hand for some time on stonks.gg but its going to be impossible to do for just one item let alone the whole bazaar. Sorry if this has already been discussed somewhere. I read the original PR and it didn't mention if it was coming back or where I could get it. 

Thanks

**Comment by robere2** [comment]
I imagine stonks.gg works by just caching the API data. The API might not store this data outside of realtime. I have not interacted with the Bazaar at all really, however is there a reason you can't just set up an application to poll the API hourly or something, and save that data in a database yourself?

**Comment by JSalenger** [comment]
> I imagine stonks.gg works by just caching the API data. The API might not store this data outside of realtime. I have not interacted with the Bazaar at all really, however is there a reason you can't just set up an application to poll the API hourly or something, and save that data in a database yourself?

Truthfully, I don't know how stonks.gg works so I won't comment on that, but Highcharts, which is used by the website has built in export options if enabled. Also, I need a large volume of data and it would take months to do it myself from this point on, which I have been doing since the need came.

**Comment by ConnorLinfoot** [comment]
stonks.gg isn't something that's part of Hypixel, so you'd have to contact Minikloon directly regarding that. Regarding the bazaar endpoint not having the `week_historic` data is that it's too much data to provide on that endpoint. You would be best using the API to continously populate the database yourself with the live data (this is how stonks.gg works for example)
