### ISSUE TITLE
Empty response body on throttle

### ISSUE THREAD

**Issue by TheNullicorn** [HypixelDev/PublicAPI#288]
With the addition of the new RateLimit headers (#248), requests throttled with a 429 response are now missing a response body; the content-type is still set to `application/json`, and the `RateLimit-Reset` header is present, but `{"success":false,"throttle":true}` is not sent.
![Screen Shot 2020-07-30 at 8 06 41 AM](https://user-images.githubusercontent.com/64789500/88920972-bdf3db00-d23b-11ea-8ebe-505e88884612.png)

**Comment by ConnorLinfoot** [comment]
This should be resolved now.
