### ISSUE TITLE
Weird text case in watchdogstats endpoint

### ISSUE THREAD

**Issue by crinny** [HypixelDev/PublicAPI#289]
`watchdogstats` endpoint responds with JSON similar to one below:
```json
{
  "success": true,
  "watchdog_lastMinute": 0,
  "staff_rollingDaily": 1700,
  "watchdog_total": 5269758,
  "watchdog_rollingDaily": 4757,
  "staff_total": 1694635
}
```
The keys are inconsistent - `watchdog_total` and `staff_total` are in snake case, while `watchdog_lastMinute`, `staff_rollingDaily` and `watchdog_rollingDaily` are a weird mix of camel and snake case.

I am trying to implement a Hypixel API wrapper that would automatically convert camelCase in API responses to Python's default snake_case but responses like this won't allow me to do so.

**Comment by ConnorLinfoot** [comment]
This endpoint has been set like this for a long time now, and changing it would actually be worse at this point. The format is because we first handle what the stats are related to then their periods.
