### ISSUE TITLE
Occasional HTTP 500 and 502 errors

### ISSUE THREAD

**Issue by Kuba314** [HypixelDev/PublicAPI#291]
Most requests of my application work, but sometimes I get HTTP 500 followed by HTTP 502.
Sometimes only the HTTP 502 error appears.

**Comment by ConnorLinfoot** [comment]
We would need more information on what requests are failing, as we're not seeing any elevated rate of errors over the last 48 hours.

**Comment by Kuba314** [comment]
@ConnorLinfoot I can't tell you much.
When I receive http 500 it's always this:
```json
{
    "success": false,
    "cause": "Internal error"
}
```
On the other hand... http 502 sends a huge HTML(most of it is b64 fonts in the head) with title `Hypixel | Maintenance` and this as a body:
```html
<body>

    <div id="container">
      <div class="h"></div>
      <h1>The Hypixel Website will be right back!</h1>
      <div class="store">The store and server are still online. <a href="https://store.hypixel.net/">Click here to visit the store.</a></div>

      <br /><br /><br />

      <div class="cf-error-details cf-error-502">
  <h1>Bad gateway</h1>
  <p>The web server reported a bad gateway error.</p>
  <ul class="cferror_details">
    <li>Ray ID: 5c12050f0959047e</li>
    <li>Your IP address: [redacted]</li>
    <li>Error reference number: 502</li>
    <li>Cloudflare Location: Paris</li>
  </ul>
</div>


    </div>

</body>
```

**Comment by Kuba314** [comment]
Since 2020-08-12 20:03-20:05 GMT the whole `guild` endpoint stopped working, always throws 502 bad gateway.
Same at 20:20-present(20:39, still doesn't work). Did someone change something?

**Comment by TheNullicorn** [comment]
The current outage is likely linked to the ongoing [network issues](https://hypixel.net/threads/3232989), not the original issue

**Comment by Kuba314** [comment]
Update: still a thing
![image](https://user-images.githubusercontent.com/35199722/90827961-77c30080-e33d-11ea-8002-5e82c8b69e87.png)
