### ISSUE TITLE
Error 403 in Google Sheet

### ISSUE THREAD

**Issue by AnsonYeung** [HypixelDev/PublicAPI#292]
So basically, custom formulas in Google sheet using Google Apps Script's fetch API would lead to hypixel api server returning 403 error with the cause "Too many invalid API keys", this would not happen (or much less often?) if the fetch api is invoked via a macro. It happens with custom formulas specifically.

**Comment by alfie1706** [comment]
This is a huge issue for me also. It seems to only apply to me when using auto-running scripts which is VITAL for what I'm using the API for!

**Comment by ConnorLinfoot** [comment]
This isn't something we can fix due to the nature of Google sheets or other shared services. If you really need to use features this offers you would be best creating your own API that you can then use via Google yourself.
