### ISSUE TITLE
auctions_gold_earned limited to 32-bit signed int limit in /skyblock/profile and /skyblock/profiles

### ISSUE THREAD

**Issue by Mippy** [HypixelDev/PublicAPI#293]
Hello,
One of my guild mates pointed out that their auction gold earned hadn't been going up in a while, or if it was going up it was doing so very slowly.

I took a look and it turns out his gold earned is just a little higher than the 32-bit signed integer limit which was interesting. I took a look at a few more profiles (such as AgroMC's Zucchini) and got a similar result with their gold earned being just a little bit over the 32 bit signed limit.

For AgroMC: 2147616747 gold earned
For my friend: 2147563647 gold earned (same as 32-bit signed?)
32-bit signed int: 2147563647

(As of writing this, it seems his gold earned reverted back to EXACTLY the limit now?)

Of course, AgroMC would have earned much more gold from the auction house than my friend. Is there some backend function that uses 32-bit signed ints to handle the number? But the storage limit is different since Agro's is OVER the limit?

Of course since this is an api issue you can also see this bug reflected on external sites like sky.lea.moe.

Please let me know, thanks!

My original forum post: [https://hypixel.net/threads/skyblock-auction-gold-earned-limit.3217676/](https://hypixel.net/threads/skyblock-auction-gold-earned-limit.3217676/)

**Comment by puppy0cam** [comment]
This is likely an issue with the game, not the API. The only transformations the API does to the data is redactions.

**Comment by ConnorLinfoot** [comment]
As mentioned above this isn't an API issue and I'd recommend you pass this on to the game developers by reporting it here https://hypixel.net/bug-reports/create
