### ISSUE TITLE
Duplicate properties with different values

### ISSUE THREAD

**Issue by LaniJW** [HypixelDev/PublicAPI#294]
What's up with the difference between games_played_bedwars and games_played_bedwars_1? Could this please be differentiated more clearly? Is it possible that maybe both values are wrong because wins and losses don't add up to either games_played_bedwars or games_played_bedwars_1.
There are a lot of properties that have ill-defined values. For every bedwars mode there's two different values for the amount of items purchased.

**Comment by TheNullicorn** [comment]
I can't answer the main question (I actually have the same value for both fields), but bugfroggy explained wins/losses not adding up [on the forums](https://hypixel.net/threads/3211763/post-22444289) a couple days ago.
> Joining a game and leaving after it starts will count as a game played, but not as a win or loss.

That was regarding Duels, but I assume it's the same for Bed Wars.

**Comment by LaniJW** [comment]
As a concrete example, if you look at the [stats of gamerboy80](https://api.hypixel.net/player?key=yourapikey&uuid=24c182c6-716b-47c6-8f60-a1be9045c449) there is differentiating information between the two games_played_bedwars properties. 
![image](https://user-images.githubusercontent.com/39264510/89980610-88ef7b80-dc72-11ea-889d-f6028d56187e.png)

Is it possible that one of the values is incremented if you join a lobby and the other only if you actually start the round?

**Comment by shadowtime2000** [comment]
In the picture you showed it looks like there are 3 `games_played_bedwars` properties.

**Comment by LaniJW** [comment]
Well yes, but actually no. There's two that are problematic. The third one "eight_one_games_played_bedwars" is a subcategory of one of the other two so it's not an issue.

**Comment by GoogleSites** [comment]
There's a lot of redundancy in the API for some reason. Maybe they were testing a new feature live and decided to use `games_played_bedwars_1` to not interfere with the original data or something. Either way, I'd use `games_played_bedwars_1` whenever it exists and `games_played_bedwars` as a fallback.

**Comment by LaniJW** [comment]
It should at least be documentet or named properly so it's clear what's meant by the property values.

**Comment by hunterm9980** [comment]
games_played_bedwars_1 will increase when the game begins and games_played_bedwars will increase when the game has finished
