### ISSUE TITLE
Missing achievement in semi-static resource

### ISSUE THREAD

**Issue by db1218** [HypixelDev/PublicAPI#296]
Resource in question: https://api.hypixel.net/resources/achievements

> there was a walls achievement called `Oh Canada`. However around 2018 the starter was removed and the achievement along with it. This caused many people to not be able to obtain this achievement and this was never added to Legacy as it was never a thing back then.

I believe this achievement is the one time achievement: `walls_canadian_kit`.

It is a legacy achievement but is not mentioned in the achievements semi-static resource which I think needs to be fixed.

**Comment by ConnorLinfoot** [comment]
This achievement is not available and has been removed, so it won't return via the API.
