### ISSUE TITLE
[Housing] How the number of weeks is generated in the housingMeta property?

### ISSUE THREAD

**Issue by jecsham** [HypixelDev/PublicAPI#303]
![image](https://user-images.githubusercontent.com/10292582/91769465-0db02400-eba5-11ea-8d61-f962c467b401.png)

I just want to link the  `given_cookies_...` properties to a start of the week (when the cookies are reset).

Currently I have an implementation in my program that takes a the number of the `given_cookies_...` and link it to a specific week, and so I calculate the rest of the weeks, however, this technique is not very effective.

Is the number of properties part of a timestamp?
How can I map those numbers to weeks?
What is the timezone of hypixel to reset cookies?

**Comment by Plancke** [comment]
`year * 52 + number week of year` = `2020 * 52 + 36` = `105076`
It could be off by one potentially, check what the current one is

**Comment by jecsham** [comment]
Thanks @Plancke
