### ISSUE TITLE
Missing GameType [REPLAY]

### ISSUE THREAD

**Issue by GoogleSites** [HypixelDev/PublicAPI#307]
It looks like the REPLAY GameType is not present in the documentation. However, it is returned in the API (namely, `/guild`). I don't know what the ID is but I'm currently just using `65`. If you guys could update the documentation to add `REPLAY` that'd be great, thanks!

**Comment by ConnorLinfoot** [comment]
Replay has now been added to the documentation.

**Comment by mdashlw** [comment]
@ConnorLinfoot is there a way to make https://api.hypixel.net open source so it's easier to track changes?
