### ISSUE TITLE
Guilds API returns irrelevant ranks for most members

### ISSUE THREAD

**Issue by IamMusavaRibica** [HypixelDev/PublicAPI#312]
A week or so ago, my guild changed their rank names. The ranks remained the same, just their names got changed.
The API returns correct Ranks, but in Members, a lot of members are returned with wrong ranks. 
My guild currently has ranks 'Youngins', 'Suppliers', 'Top Boys', 'Guild Officer' and 'Guild Co' , but in the response, only few members have the right ranks. Others have either 'Member' or 'Recruit', which my guild had changed names for. 
Request link:
https://api.hypixel.net/guild?id=5c5d106177ce84d0034413b7&key=KEY

Ranks from the response
`"ranks":[{"name":"Guild Co","default":false,"tag":"GC","created":1599964489239,"priority":5},{"name":"Officer","default":false,"tag":"GO","created":1599964490037,"priority":4},{"name":"Youngins","default":true,"tag":"Y","created":1599964532064,"priority":1},{"name":"Suppliers","default":false,"tag":"S","created":1599964568579,"priority":2},{"name":"Top Boys","default":false,"tag":"T","created":1599964574175,"priority":3}]`

An example of a member with wrong values:
`{"uuid":"74db31064d4e48f3943e02f49af1d079","rank":"Recruit","joined":1550088928320,"questParticipation":293,"expHistory":{"2020-09-19":0,"2020-09-18":0,"2020-09-17":0,"2020-09-16":0,"2020-09-15":0,"2020-09-14":0,"2020-09-13":0}}`

**Comment by ConnorLinfoot** [comment]
This is not an API issue. When a rank is renamed the guild system does not maintain players with the rank.
