### ISSUE TITLE
[Suggestion] List player houses

### ISSUE THREAD

**Issue by jecsham** [HypixelDev/PublicAPI#314]
In the `/player` endpoint, there is a property called `"housingMeta"`. It would be great if within that property you could put another one to list the player's houses.

Example: `playerHouses`

```json
{
   "housingMeta":{
      "playerHouses":[
         {
            "name":"Red House",
            "id":"be53cbd9-ac02-42d7-864f-47d50aaadb99"
         }
      ]
   }
}
```

Why? Currently the only way to relate an uuid to a player's house is by giving cookies to the house and then looking at the property `given_cookies` in the api to find the uuid.

**Comment by ConnorLinfoot** [comment]
I don't think this is something we will add, I'm also not really sure what uses having this information would provide.

**Comment by jecsham** [comment]
> I don't think this is something we will add, I'm also not really sure what uses having this information would provide.

Develop apps to known if a user gave cookies in a house, for example.
