### ISSUE TITLE
Duplicate keys under TNTGames with different values

### ISSUE THREAD

**Issue by ImPlotzes** [HypixelDev/PublicAPI#317]
Upon going to "https://api.hypixel.net/player?key=[MY-KEY]&uuid=e97b16f4719b45a5959c81ef52aaea7a" then there are two selected hats under TNTGames. One key is called "new_selected_hat" and one is called "selected_hat". They both show different hats. Please remove the old one and keep "new_selected_hat". 
![image](https://user-images.githubusercontent.com/47643346/94617851-8f7d9500-02aa-11eb-957b-2a6e895bf8fc.png)
![image](https://user-images.githubusercontent.com/47643346/94617867-94dadf80-02aa-11eb-8da2-17ba67877826.png) **<--- Correct hat**

This also goes for the Wizards selected class. There's "capture_class" and "wizards_selected_class". 
![image](https://user-images.githubusercontent.com/47643346/94618375-572a8680-02ab-11eb-8737-55e7b319f594.png)
![image](https://user-images.githubusercontent.com/47643346/94618383-5a257700-02ab-11eb-8fea-8f0ce8382405.png)

**Comment by ConnorLinfoot** [comment]
This isn't something we're likely going to change any time soon. Lots of games have similar scenarios but its not worth the time to go through convert and remove unused fields
