### ISSUE TITLE
[Problem] Missing info in Farming skill 51-60

### ISSUE THREAD

**Issue by Kenshayy** [HypixelDev/PublicAPI#322]
As stated in the title, in the API it is not included if an user actually unlocked (not reached, just unlocked from Anita NPC) any of the new Farming levels (51-60).
Without this info, we have to guess if the player has actually unlocked the farming levels.

**Comment by MartinNemi03** [comment]
> 
> 
> As stated in the title, in the API it is not included if an user actually unlocked (not reached, just unlocked from Anita NPC) any of the new Farming levels (51-60).
> Without this info, we have to guess if the player has actually unlocked the farming levels.

You don't have to guess, there's a small workaround, but it's very inefficient. It would be great if it was already added.

**Comment by Jordanm01** [comment]
This was actually added recently, look for "jacob2" in the /profiles endpoint and the information is under perks

**Comment by MartinNemi03** [comment]
> 
> 
> This was actually added recently, look for "jacob2" in the /profiles endpoint and the information is under perks

Yeah, @ConnorLinfoot could you close this issue then, please?
