### ISSUE TITLE
Documentation Readme: dashed UUIDs work just fine (Edit: ONLY dashed UUIDs work)

### ISSUE THREAD

**Issue by HydroPage90** [HypixelDev/PublicAPI#326]
Why don't you remove the section about UUID parameters needing to have no dashes. Dashed UUIDs work for me just fine

**Comment by HydroPage90** [comment]
To add on to this, a `UUID` object must be created to pass to the API, and from what I've seen, `UUID.fromString` actually doesn't like **non-dashed** UUID Strings. So, not only do dashed UUID Strings work fine, they're the only ones that work.

**Proof:**
![image](https://user-images.githubusercontent.com/31541490/101381164-4712c280-386b-11eb-9090-623f0e10e47b.png)
![image](https://user-images.githubusercontent.com/31541490/101381239-5b56bf80-386b-11eb-952d-c12faecd2147.png)

**Comment by mdashlw** [comment]
To avoid confusion, the actual api accepts both dashed and undashed uuids. It's java implementation that requires a UUID instance that cannot be created from an undashed version.

**Comment by HydroPage90** [comment]
I'll close when his PR gets merged (I'm sorry for notifying you, mdashlw)

**Comment by HydroPage90** [comment]
Closing, for his PR was closed
