### ISSUE TITLE
Farmhand Perk

### ISSUE THREAD

**Issue by MattTheCuber** [HypixelDev/PublicAPI#329]
I'm looking for the farmhand perk you buy from the new farming NPC and I pretty sure it's not in the API

(First time I've created an issue so I'm sorry if I did it wrong)

**Comment by TheLegendOfKitty** [comment]
Can't you calculate this using the player's skill level?

**Comment by MartinNemi03** [comment]
> Can't you calculate this using the player's skill level?

You can get this from Achievements, but that's only if they reached the level. You aren't able to see if they unlocked it before reaching said level.

**Comment by MartinNemi03** [comment]
This problem has already been mentioned in #322, but it would be great if it was resolved.

**Comment by MartinNemi03** [comment]
This issue is already resolved with an addition of jacob2 in /skyblock/profile endpoint.
@ConnorLinfoot Can you close this one as well, please?
