### ISSUE TITLE
quickjoin_map removed from player endpoint

### ISSUE THREAD

**Issue by hunterm9980** [HypixelDev/PublicAPI#332]
Hello, the past few weeks i've been working on a bot that will visualize people's favorite bedwars maps using graphs and the such. However for some reason randomly quickjoin_mapname got removed from the api, there was no documentation or warning that this was going to be removed.

How will I be able to access this stat in the future, and what is the reason it was removed without warning last night?

**Comment by ConnorLinfoot** [comment]
Stats based around the map selector were being used maliciously and are not something we wish to be public in the API.
