### ISSUE TITLE
Approaching(Next) Stacked Booster is inaccurate on booster endpoint?

### ISSUE THREAD

**Issue by ilsubyeega** [HypixelDev/PublicAPI#333]
As I purchased network boosters, im trying to use booster endpoint, multiplier, or stacked person isn't shown on the next boosters in each game.
EhBacon's Skywars network booster is the next booster, it should show EhBacon +10 another players who stacked but not shows another 10 players on API before his network booster starts.

the image from plancke.io seems to use hypixel-api (before/after)
![image](https://user-images.githubusercontent.com/37479424/100610564-4ce04380-3353-11eb-84e1-ac3e14b29b92.png)
![image](https://user-images.githubusercontent.com/37479424/100610632-7305e380-3353-11eb-8901-c21c4e48cd68.png)

**Comment by Plancke** [comment]
The database only gets the stacked boosters once it activates, though you should be able to calculate it clientside based on `dateActivated` timestamp and `"stacked": true` as they should get stacked in order, per game type of course.
