### ISSUE TITLE
Bazaar History

### ISSUE THREAD

**Issue by TheMG95** [HypixelDev/PublicAPI#343]
I know that this got asked before but a bazaar history would be great. Its a pain to store bazaar data and when you are going to make a project that needs old bazaar data you need to store the data for some time and start the project afterwards. It would be great if we had a bazaar history in the api.

Thanks

**Comment by ConnorLinfoot** [comment]
This isn't something we are going to add, it would require a lot of processing for us to keep and aggregate every bazaar sale.
