### ISSUE TITLE
random api key invalidation

### ISSUE THREAD

**Issue by mdashlw** [HypixelDev/PublicAPI#354]
Hypixel keeps randomly invalidating some of my api keys for no reason and I'm experiencing a lot of issues because of that. Please fix this problem.

**Comment by ThomDeMeulder** [comment]
You might want to take a look at a previous response from Connor. https://github.com/HypixelDev/PublicAPI/issues/257#issuecomment-643218383

**Comment by mdashlw** [comment]
> You might want to take a look at this previous response from Connor. [#257 (comment)](https://github.com/HypixelDev/PublicAPI/issues/257#issuecomment-643218383)

I saw that. But I still wanna receive a response from a knowledgeable admin (not Connor).

**Comment by ConnorLinfoot** [comment]
As ThomDeMeulder pointed out, this has already been addressed in a previous issue and will not be discussed further here.
