### ISSUE TITLE
[BUG] Cookies weekly ID generated incorreclty for this week

### ISSUE THREAD

**Issue by jecsham** [HypixelDev/PublicAPI#357]
The weekly sequential ID was generated incorrectly. The cookies system is not working properly.

![image](https://user-images.githubusercontent.com/10292582/103166589-a1130200-47f1-11eb-8b37-e13c7e976f39.png)

![image](https://user-images.githubusercontent.com/10292582/103166668-71182e80-47f2-11eb-9ffd-42f2cca1300b.png)

**Comment by ConnorLinfoot** [comment]
This is not the place to report game bugs, please use https://hypixel.net/bugs
