### ISSUE TITLE
wins_pvprun not counted towards wins in TNTGames

### ISSUE THREAD

**Issue by yolomilk** [HypixelDev/PublicAPI#360]
I am referring to the results form the `player` api method.
The wins from PvP Run are not counted towards the TNT Games wins (player -> stats -> TNTGame -> wins). I think that they should be counted, because 

1. PVP Run is in the TNT Games Lobby .
1. `wins_pvprun` is in player -> stats -> TNTGames.

A good example for this is the player with the uuid [`2c3bcc31173d410bad4456bb64f285ec`](https://plancke.io/hypixel/player/stats/2c3bcc31173d410bad4456bb64f285ec#TNTGames)
He currently has 672 PVP Run Wins, but just 265 TNTGames wins (Not shown on plancke.io).

I hope that this is the right place to report such bugs.

**Comment by mdashlw** [comment]
If anything, this should be reported to https://hypixel.net/bugs. But I doubt anything will change, because there's no actual reason for it.
