### ISSUE TITLE
Add settings back

### ISSUE THREAD

**Issue by mdashlw** [HypixelDev/PublicAPI#363]
Reopening because old issue isn't active. There's not a single reason to remove settings, having ability to see whether someone has status/games api enabled or disabled is completely useless and can be achieved even without actual settings.
Player is online but /status says offline -> they have it disabled
/recentgames returns empty list -> they probably have it disabled.

Lack of settings only adds issues, such as not being able to heavily rely on /status api as it could be disabled, so you have to check online normally, and it may glitch sometimes, for example this player
![image](https://user-images.githubusercontent.com/34678047/103769983-4e79e700-5036-11eb-8a10-1246b4ec3b6a.png)

If someone in the admin team doesn't want to add api settings back for some mysterious reason, at least everything else could be useful to some people and should be added back until there are actually problems with it.

**Comment by ConnorLinfoot** [comment]
Our decision on not providing this data is final.

**Comment by mdashlw** [comment]
> Our decision on not providing this data is final.

All I'm gonna say is that this decision is extremely stupid, just like a big part of them, and that is very unfortunate.
