### ISSUE TITLE
Strange IllegalStateException in HypixelAPI#get

### ISSUE THREAD

**Issue by HydroPage90** [HypixelDev/PublicAPI#386]
![image](https://user-images.githubusercontent.com/31541490/107076484-5ac1a300-67a0-11eb-9b45-40106c3f054c.png)

Using release 3.0.0

**Comment by OskarZyg** [comment]
Could you please provide actual logs instead of images?

**Comment by HydroPage90** [comment]
This was a while ago, and it’s very rare to occur. I can’t reproduce it

**Comment by OskarZyg** [comment]
Something related to an unstable connection I guess.

**Comment by mdashlw** [comment]
It's a syntax error, so if I had to guess, I would say it's cloudflare messing with stuff by returning html page

**Comment by HydroPage90** [comment]
For the past couple of hours today, this error has rendered my program completely useless. I changed nothing about my code which was working before, and now this same error keeps on occurring and occurring. I really would like to know what the real cause is

**Comment by AzureAaron** [comment]
> For the past couple of hours today, this error has rendered my program completely useless. I changed nothing about my code which was working before, and now this same error keeps on occurring and occurring. I really would like to know what the real cause is.
> 
> First reply asked for a real log, so here is a sample
> 
> ```
> java.util.concurrent.CompletionException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
> 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
> 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
> 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
> 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
> 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
> 	at net.hypixel.api.HypixelAPI.lambda$get$1(HypixelAPI.java:262)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:187)
> 	at com.google.gson.Gson.fromJson(Gson.java:805)
> 	at com.google.gson.Gson.fromJson(Gson.java:770)
> 	at com.google.gson.Gson.fromJson(Gson.java:719)
> Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
> 
> 	at com.google.gson.Gson.fromJson(Gson.java:691)
> 	at net.hypixel.api.HypixelAPI.lambda$null$0(HypixelAPI.java:254)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
> 	at net.hypixel.api.HypixelAPI.lambda$get$1(HypixelAPI.java:249)
> 	... 5 common frames omitted
> Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
> 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:387)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
> Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
> 
> 	... 14 common frames omitted
> ```

It’s because there is API issues rn where API returns Error 502 Bad Gateway on a significant amount of requests and serves an HTML page.


Hopefully it gets fixed soon, however there is no issue created about this :/

**Comment by HydroPage90** [comment]
> returns Error 502 Bad Gateway on a significant amount of requests

I did some testing, and my application is one that has to make a lot of requests in bulk. 300 or 400 requests over the span of a few minutes. I did some experimenting, and noticed that after a few hundred ish requests, this error happened. But it was way worse one or two days ago, it's becoming less chronic. Very annoying though, since my application is not fault tolerant to this because it was very rare

**Comment by ConnorLinfoot** [comment]
The exception itself (as people have pointed out) happens when the API is having issues and instead returns a non-json response, usually a Cloudflare error page. Hopefully, after recent changes to scale the service the issue should happen very infrequently now.
