### ISSUE TITLE
Authentication by API Key missing on some endpoints.

### ISSUE THREAD

**Issue by Picsou993** [HypixelDev/PublicAPI#387]
On some SkyBlock endpoints, it is not needed anymore to use a key to get the data.
If it's not a bug if the data is cached, then the documentation should be edited.

List of affected methods:
- https://api.hypixel.net/skyblock/bazaar
- https://api.hypixel.net/skyblock/auctions

Documentation:
- https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/skyblock/bazaar.md
- https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/skyblock/auctions.md

Furthermore, https://api.hypixel.net/skyblock/auctions_ended does not require an API Key too but it looks like this one is intended to not have one according to the documentation: https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/skyblock/auctions_ended.md

**Comment by ConnorLinfoot** [comment]
None of these endpoints require a key. The documentation has not been updated as we're working on rewriting it.
