### ISSUE TITLE
Missing SkyWars level leaderboard

### ISSUE THREAD

**Issue by Daafdemandoetmee** [HypixelDev/PublicAPI#395]
Hello there,
The current https://api.hypixel.net/leaderboards?key=KEY endpoint only returns the ranked rating, wins, kills, monthly kills, and weekly kills for SkyWars leaderboards. while there is a leaderboard for SkyWars level in the lobby.

**Comment by ConnorLinfoot** [comment]
We have added the leaderboard `skywars_exp`
