### ISSUE TITLE
content-encoding is set to utf-8

### ISSUE THREAD

**Issue by LEGENDFF** [HypixelDev/PublicAPI#40]
This is invalid, also doesnt work with the Apache Http Client
http://stackoverflow.com/questions/17154967/is-content-encoding-being-set-to-utf-8-invalid

**Comment by hdeadman** [comment]
I updated httpclient to the latest version and the examples started working for me. The error about UTF-8 not being a valid content encoding stopped happening in the SyncGetPlayerExample and other examples that hadn't been working (but where I didn't see that exception) started working. 

In Java/pom.xml:
```
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.2</version>
        </dependency>
```

**Comment by Plancke** [comment]
Fixed

**Comment by hdeadman** [comment]
How was this fixed? It doesn't appear that the httpclient version was updated.

**Comment by Plancke** [comment]
Our backend was sending the wrong headers, I changed it there. Is it still causing issues for you?

**Comment by hdeadman** [comment]
Sorry, it does work now with the old version of httpclient. I don't know if the new httpclient version worked with and without your fix or if I switched the httpclient at the same time you fixed the server and it made me think that it was the client change that fixed the problem.
