### ISSUE TITLE
Missing achievements in semi-static resource

### ISSUE THREAD

**Issue by db1218** [HypixelDev/PublicAPI#403]
Resource refering to:
https://api.hypixel.net/resources/achievements

The latest Mega Walls achievements are not in the achievements resource:
- Heavy Eater (Moleman)
- Sacred Bull (Cow)

Thanks :)

**Comment by db1218** [comment]
* Correction: Sacred Bull is the skin name, the achievement is called `Biological Restoration`

**Comment by ConnorLinfoot** [comment]
Seems like the automatic updating hasn't been running for a little while. I've manually run it so they should be up to date again and we'll investigate the auto-updating.
