### ISSUE TITLE
You have already looked up this name recently

### ISSUE THREAD

**Issue by mdashlw** [HypixelDev/PublicAPI#406]
Please revert this change. It's terrible. I'm confident this is the worst thing that has happened to the api so far. 
If looking up players by name is expensive for the api, then name->uuid could be cached for like 15 minutes (the cooldown between lookups is like 5 minutes anyway).
This is a breaking change that was never warned about and given no time to prepare for it. So even if you want to keep this, you should delay this until 4.0.0 PR is merged.

**Comment by ConnorLinfoot** [comment]
The endpoint is deprecated and should not be relied upon at all. There is an explanation for this change [here](https://hypixel.net/threads/hypixel-api-rate-limit-big-problem.3996327/post-29013586) and we will not be reverting it.
