### ISSUE TITLE
What is the cooldown for a search by player name?

### ISSUE THREAD

**Issue by HydroPage90** [HypixelDev/PublicAPI#409]
I recently discovered that HypixelAPI does not like it when you request the same player name in a short period of time. But what is the true cooldown time for this?

**Comment by shadowtime2000** [comment]
Duplicate of #407, which got converted to a discussion. This should be converted too or just closed and locked because it is a duplicate cc @ConnorLinfoot

**Comment by HydroPage90** [comment]
I'll do it myself, thank you
