### ISSUE TITLE
/resources/skyblock/skills uses "collections" and not "skills" as main key

### ISSUE THREAD

**Issue by GoogleSites** [HypixelDev/PublicAPI#417]
According to the [documentation](https://api.hypixel.net/#tag/SkyBlock/paths/~1resources~1skyblock~1skills/get), the JSON key to the list of skills should be `skills`. However, [in the API](https://api.hypixel.net/resources/skyblock/skills), it uses `collections`.

**Comment by ConnorLinfoot** [comment]
We've added the skills key while keeping the old key to avoid instantly breaking applications that use the incorrect key. We'll likely remove the invalid key sometime in the future, maybe in a month or something.
