### ISSUE TITLE
Bazaar quick_status SellPrice is wrong.

### ISSUE THREAD

**Issue by Ancient77** [HypixelDev/PublicAPI#418]
Under the https://api.hypixel.net/skyblock/bazaar endpoint, I got the data for products["REFINED_DIAMOND"].quick_status.

{"productId":"REFINED_DIAMOND","**sellPrice":40089.0492599162**,"sellVolume":1061173,"sellMovingWeek":6943,"sellOrders":138,"buyPrice":486713.7886227544,"buyVolume":528,"buyMovingWeek":11364,"buyOrders":65}}

The sellPrice should be something around 400k, it is only 40k tho, which can't be true (according to the ingame bazaar).

**Comment by shadowtime2000** [comment]
@Ancient77 Can you share a screenshot of it being 400k in the ingame bazaar?

**Comment by Ancient77** [comment]
![2021-04-04_22 40 48](https://user-images.githubusercontent.com/76914086/113520987-e5533280-9596-11eb-9ca3-e13556901286.png)

**Comment by Ancient77** [comment]
I've read the doc again, it says:
sellPrice and buyPrice are the weighted average of the top 2% of orders by volume.
This would make no sense for sellPrice since you can just order a lot for a very low price and change the sellPrice.

**Comment by TopDogger1** [comment]
buy summary/sell summary
