### ISSUE TITLE
skyblock/auctions 's paging is bugged

### ISSUE THREAD

**Issue by RobotHanzo** [HypixelDev/PublicAPI#424]
Proved by https://hypixel.net/threads/apparently-the-zero-th-page-and-the-first-page-of-the-skyblock-auction-is-the-same.2632194/
The endpoint's page 0 and page 1 is the same
And the last page isn't the real last page (by comparing last page's size with `totalAuctions`)
Please fix this, or we won't be able to get the whole auction properly

**Comment by ConnorLinfoot** [comment]
The issue has been resolved.
