### ISSUE TITLE
Several Issues with players skyblock data stats

### ISSUE THREAD

**Issue by MattTheCuber** [HypixelDev/PublicAPI#430]
https://api.hypixel.net/skyblock/profiles?key=APIKEY&uuid=2fc99625a91b49e889c092a58eef9284 returns https://pastebin.com/EbL4V42a

I have several issues with the stats data:
1. Private island endermen kill and end island enderman kills are combined
2. Goblin kills are super confusing
    For example: when the player Kian_Thrane_19 does /be and checks their goblin kills it shows 6418. The API has several (9) different stats for goblin kills. Zero combinations of these stats leads to the number 6418. I have literally no idea how to fix this.
3. Arachne kills, Magma Cube Boss kills, Headless Horseman and Endstone Protector kills only show last hits (would be great if they could show total bosses participated in as well)

**Comment by ConnorLinfoot** [comment]
The Hypixel API just provides data as-is from the database, so these stats are stored by the game in those ways.

If you believe this to be an issue then you can create a bug report for the game developers to investigate at https://hypixel.net/bug-reports/create
