### ISSUE TITLE
Internal api error

### ISSUE THREAD

**Issue by BiteSizedPopcorn** [HypixelDev/PublicAPI#431]
Ign:Coraze
it wont let me access sky crypt saying 
internal api error

**Comment by ConnorLinfoot** [comment]
Can you please provide the request you are attempting to make causing the error?

**Comment by MartinNemi03** [comment]
> 
> 
> Ign:Coraze
> it wont let me access sky crypt saying
> internal api error

Requesting both profiles on this user works fine for me, both for our site and in the API directly. 
Seems like an earlier issue that hasn't appeared since.
