### ISSUE TITLE
Internal api error, possibly due to integer bit limit

### ISSUE THREAD

**Issue by TheDeadlyBlaze** [HypixelDev/PublicAPI#432]
Ign: fire12324344
I managed to break my api when I attempted to go for the #1 highest critical damage.

**Comment by ConnorLinfoot** [comment]
Can you please provide the request you are attempting to make causing the error?

**Comment by TheDeadlyBlaze** [comment]
It happens whenever someone makes any request related to my profile on skyblock, even co-op members. I don't know much about how it works, sorry.

**Comment by MartinNemi03** [comment]
> 
> 
> Can you please provide the request you are attempting to make causing the error?

They're making a standard `/skyblock/profile` request for his profile "Papaya" (Profile ID: `90deaff45f7e4c10a706220da3a5e58f`) with the result being `{"success":false,"cause":"Internal error"}`.

**Comment by ConnorLinfoot** [comment]
I've fixed this specific profile and passed the issue onto the SkyBlock development team to investigate and fix the cause when possible, thanks for reporting!
