### ISSUE TITLE
Add more filtering options on Auctions Endpoint

### ISSUE THREAD

**Issue by franhida** [HypixelDev/PublicAPI#434]
It would be nice to have similar filtering options in the API as it can be done the in-game Auction House.
I would like to propose some more filtering options as query params:

- Item name. Eg: Heat Core => `item_name=Heat Core`
- End. Eg [timestamp] => `end=[now + 1h]`
- Limit. Eg 100 => `limit=100`

The full examples of the options above would be as follows:
- Item Name: `https://api.hypixel.com/skyblock/auctions?item_name=Heat Core`
- End: `https://api.hypixel.com/skyblock/auctions?end=[now + 1h]`
- Limit: `https://api.hypixel.com/skyblock/auctions?limit=100`

Of course, mixing the params should be allowed as well.
- `https://api.hypixel.com/skyblock/auctions?item_name=Heat Core&end=[now + 1h]`
- `https://api.hypixel.com/skyblock/auctions?limit=100&page=3`

Should I think any further options, they will be posted in this very issue.

**Comment by ConnorLinfoot** [comment]
Unfortunately, we don't have intentions at this time to implement filters to this endpoint. As usual, we like to keep processing to a minimum for performance reasons. This specific endpoint is already handling millions of requests per day and we can only handle that nicely due to heavy caching.

**Comment by franhida** [comment]
That's a pity.
Thanks for the quick response nonetheless.
Does this same response apply to all the endpoints or just this one in particular?
Thanks again @ConnorLinfoot

**Comment by ConnorLinfoot** [comment]
It basically goes for anything where we believe the processing is too much or just not required. We also do some processing for example on SkyBlock Profiles to clean up the output a little compared to the database but this was an edge case where it made sense.
