### ISSUE TITLE
API is broken

### ISSUE THREAD

**Issue by simonwolfsimonwolf** [HypixelDev/PublicAPI#439]
I broke my API by dealing a riciculously high damage number. 
https://sky.shiiyu.moe/stats/_simonwolf
My IGN is _Simonwolf, please fix this, it's been months since I submitted a bug report on the forums.

**Comment by ConnorLinfoot** [comment]
Can you please provide a profile ID of the issue?

**Comment by ConnorLinfoot** [comment]
I have removed the broken field from the profile.
