### ISSUE TITLE
bazaar endpoint's sellVolume/buyVolume is very wrong

### ISSUE THREAD

**Issue by csjh** [HypixelDev/PublicAPI#444]
The value for sellVolume (and buyVolume, but to a lesser degree), which the docs say is the "sum of item amounts in all orders", is off by a significant amount. Here is a list of the items I found were off (this is only items with less than 30 sell orders, since I can't manually count the amounts outside of that). It shows the disparity between the api's value for how many items are in buy orders vs. how many are actually in the buy orders. The list is formatted `product_id | api_amount - actual_amount | api_amount / actual_amount`

INK_SACK:3 1440521 1.48
BROWN_MUSHROOM 1032090 4.18
SPOOKY_SHARD 15591 1.5
INK_SACK:4 201997 1.26
TARANTULA_WEB 1516183 1.77
CARROT_ITEM 987173 1.32
ENCHANTED_POTATO 944905 2.95
ENCHANTED_SLIME_BALL 63626 1.24
ENCHANTED_RED_MUSHROOM 83868 1.51
ENCHANTED_GOLDEN_CARROT 1446501 95.55
ENCHANTED_RABBIT_HIDE 85223 7.44
FLAWED_AMETHYST_GEM 5507684 48.0
PERFECT_JADE_GEM 8567 7.68
ENCHANTED_BIRCH_LOG 358528 5.25
ENCHANTED_GUNPOWDER 101656 2.06
ENCHANTED_SUGAR 3472030 4.38
CACTUS 887490 1.36
FLAWED_JASPER_GEM 2374376 19.53
ENCHANTED_BLAZE_ROD 123452 2.29
ENCHANTED_CAKE 13928 3.51
PUMPKIN 720859 1.42
ENCHANTED_BROWN_MUSHROOM 346012 8.68
FLAWED_AMBER_GEM 2064232 8.47
NURSE_SHARK_TOOTH 48860 1.89
WHEAT 8427572 3.16
ENCHANTED_RAW_SALMON 301321 2.19
ENCHANTED_GLISTERING_MELON 30346 9.35
PRISMARINE_SHARD 1652751 1.84
ENCHANTED_EMERALD 210014 1.68
RED_MUSHROOM 292625 1.39
MUTTON 817618 11.39
ENCHANTED_MELON_BLOCK 122742 3.82
POWER_CRYSTAL 3169 1.1
RAW_SOULFLOW 6590024 67.87
SHARK_FIN 434928 3.71
WISE_FRAGMENT 57027 2.94
DIAMOND 4668007 1.73
COBBLESTONE 3322849 1.8
REFINED_MITHRIL 16159 8.74
SPIDER_EYE 7174801 5.71
RAW_FISH 993800 1.88
PERFECT_RUBY_GEM 109339 1.73
POTATO_ITEM 197467 1.14
ENCHANTED_NETHERRACK 371154 4.92
ENCHANTED_HUGE_MUSHROOM_1 8295 3.06
TIGHTLY_TIED_HAY_BALE 12191 3.41
PORK 2159306 5.08
PRISMARINE_CRYSTALS 112 1.0
ICE 822277 1.55
TIGER_SHARK_TOOTH 942 1.1
HUGE_MUSHROOM_1 927694 5.93
HUGE_MUSHROOM_2 1789052 4.65
ICE_BAIT 990434 3.05
LOG_2:1 1110984 1.41
STRING 1942456 2.85
GOLDEN_TOOTH 8015 1.86
RABBIT_FOOT 69625 1.29
REDSTONE 1166384 1.39
PUMPKIN_GUTS 4686 1.91
ENCHANTED_CARROT_ON_A_STICK 0 0.0
ENCHANTED_LAPIS_LAZULI_BLOCK 36655 2.64
ENCHANTED_STRING 1110933 4.78
STRONG_FRAGMENT 46156 4.64
SLIME_BALL 189905 2.15
SNOW_BALL 967125 1.36
ENCHANTED_ACACIA_LOG 309415 2.32
ENCHANTED_EGG 1911 1.03
SAND 993819 2.81
FLAWED_RUBY_GEM 195779 1.65
RAW_CHICKEN 670709 2.72
FLAWLESS_JASPER_GEM 1603 1.01
ANCIENT_CLAW 3466932 4.18
ENCHANTED_GHAST_TEAR 109897 1.17
ENCHANTED_LAPIS_LAZULI 5823796 13.82
ENCHANTED_COCOA 1800167 2.39
FINE_TOPAZ_GEM 119592 13.03
CARROT_BAIT 269277 5.82
FINE_RUBY_GEM 7126 1.83
SEEDS 6721 1.0
ENCHANTED_SPONGE 699319 5.75
PERFECT_AMBER_GEM 225289 3.65
HAY_BLOCK 582327 1.58
INK_SACK 3226155 12.16
FLINT 3648947 3.14
ENCHANTED_ROTTEN_FLESH 792910 6.08
WOLF_TOOTH 1241614 2.13
ENCHANTED_GRILLED_PORK 2921 1.28
ENCHANTED_NETHER_STALK 4919435 3.2
ENCHANTED_REDSTONE_BLOCK 91207 21.05
ENCHANTED_QUARTZ_BLOCK 79464 1.53
ENCHANTED_ANCIENT_CLAW 514359 13.52
GREEN_CANDY 2008602 5.03
ENCHANTED_REDSTONE_LAMP 5461 1.07
TREASURITE 229466 9.88
GRAVEL 2047 1.0
MELON 548335 1.36
ENCHANTED_PACKED_ICE 72165 1.9
RAW_FISH:3 4863157 9.6
ENCHANTED_PRISMARINE_SHARD 0 1.0
ENCHANTED_CARROT_STICK 1683 2.81
BONE 1019260 1.31
RAW_FISH:2 643947 1.85
RAW_FISH:1 538579 1.33
REVENANT_FLESH 933877 1.36
ENCHANTED_GLOWSTONE 1102 1.08
ROUGH_JASPER_GEM 3168104 6.91
FEATHER 268534 1.17
WHALE_BAIT 1681752 10.75
NETHERRACK 871070 2.02
SPONGE 4500693 16.76
BLAZE_ROD 2236732 5.54
ENCHANTED_DARK_OAK_LOG 180552 1.58
FLAWLESS_TOPAZ_GEM 12672 1.18
ENCHANTED_GOLD 1429335 2.99
ENCHANTED_RAW_CHICKEN 0 1.0
ENCHANTED_WATER_LILY 23907 1.82
ROUGH_AMETHYST_GEM 5624160 7.39
ROUGH_RUBY_GEM 7758790 3.44
LOG:1 1129138 1.74
FLAWLESS_RUBY_GEM -1 0.98
NULL_ATOM 85950 13.18
TITANIUM_ORE 91388 1.28
BLUE_SHARK_TOOTH 159633 42.17
LOG:3 2179650 1.61
LOG:2 1911271 3.27
BLESSED_BAIT 803828 1.93
ENCHANTED_INK_SACK 29719 3.88
ENCHANTED_CACTUS 6686 1.63
FLAWLESS_SAPPHIRE_GEM 4244 10.09
ENCHANTED_COOKED_SALMON 10886 1.95
ENCHANTED_SEEDS 61565 1.12
CONCENTRATED_STONE 106686 5.55
LOG 312689 1.24
ENCHANTED_BONE_BLOCK 308333 5.08
GHAST_TEAR 398556 1.35
ABSOLUTE_ENDER_PEARL 274323 15.26
UNSTABLE_FRAGMENT 114980 3.45
ENCHANTED_ENDER_PEARL 1609298 7.78
PURPLE_CANDY 279376 2.69
ENCHANTED_FERMENTED_SPIDER_EYE 18665 4.21
SPIKED_BAIT 525695 2.31
POLISHED_PUMPKIN 31586 5.97
ROUGH_JADE_GEM 6742502 3.47
ENCHANTED_FLINT 264442 2.6
IRON_INGOT 3811683 2.94
ENCHANTED_EMERALD_BLOCK 3353 1.4
NULL_OVOID 7442 3.82
ENCHANTED_CLAY_BALL 1845020 3.62
ROUGH_SAPPHIRE_GEM 8109345 9.94
GLOWSTONE_DUST 1241363 3.47
GOLD_INGOT 1507011 1.75
REVENANT_VISCERA 108863 3.28
PERFECT_AMETHYST_GEM 74054 34.13
TARANTULA_SILK 85892 9.23
TITANIC_EXP_BOTTLE 2105 1.13
NULL_SPHERE 1284518 8.12
SUPER_EGG 94172 8.11
MITHRIL_ORE 2994949 1.42
ENCHANTED_HAY_BLOCK 142536 2.69
ENCHANTED_BONE 2060686 5.84
ENCHANTED_PAPER 3680085 14.41
SPOOKY_BAIT 710288 1.77
MAGMA_BUCKET 971 2.78
EMERALD 1376436 1.6
LIGHT_BAIT 86208 1.22
HOT_POTATO_BOOK 26892 19.13
ENCHANTED_ICE 19345 1.32
CLAY_BALL 1992895 2.87
OLD_FRAGMENT 76108 3.93
GREEN_GIFT 104841 1.47
FLAWLESS_AMETHYST_GEM 11555 1.16
ROUGH_TOPAZ_GEM 4980359 6.9
PACKED_ICE 713329 3.86
ROUGH_AMBER_GEM 3168051 3.01
WATER_LILY 7001745 12.13
LOG_2 207621 1.72
ENCHANTED_OBSIDIAN 310372 2.74
ENCHANTED_COAL 7262011 93.33
COAL 1088960 1.79
ENCHANTED_QUARTZ 1815361 13.16
ENDER_PEARL 3795486 1.96
WEREWOLF_SKIN 85597 3.04
PERFECT_TOPAZ_GEM 2439 1.01
ENCHANTED_PRISMARINE_CRYSTALS 1 1.0
DAEDALUS_STICK 697 1.95
ENCHANTED_WET_SPONGE 1198 1.15
FLAWED_JADE_GEM 8844219 20.8
ENDER_STONE 507359 1.36
QUARTZ 851362 2.83
FOUL_FLESH 46446 8.31
RAW_BEEF 184538 1.26
ENCHANTED_EYE_OF_ENDER 225652 21.13
ECTOPLASM 171625 44.94
SUGAR_CANE 4894639 1.74
MAGMA_CREAM 145515 1.68
SHARK_BAIT 466461 1.33
ENCHANTED_RAW_BEEF 496893 2.81
ENCHANTED_FEATHER 62037 1.38
ENCHANTED_SLIME_BLOCK 13382 2.01
ENCHANTED_OAK_LOG 80561 1.69
RABBIT_HIDE 1724578 3.11
RABBIT 162771 1.25
NETHER_STALK 1168449 1.35
SULPHUR 284238 2.24
DARK_BAIT 331175 2.74
ENCHANTED_CARROT 7284849 6.35
ROTTEN_FLESH 4678644 4.25
OBSIDIAN 5664552 2.82
MINNOW_BAIT 94347 1.68
ENCHANTED_MAGMA_CREAM 20494 1.17
ENCHANTED_FIREWORK_ROCKET 0 1.0
HARD_STONE 4994942 1.85
FLAWED_TOPAZ_GEM 167361 1.48
FLAWLESS_JADE_GEM 10473 5.81
LEATHER 527857 2.45
ENCHANTED_COOKED_MUTTON 5347 1.36
ENCHANTED_RABBIT 90218 1.67
MUTANT_NETHER_STALK 17089 1.37
ENCHANTED_BREAD 1099391 4.2
FINE_JASPER_GEM 157998 132.88
FLAWLESS_AMBER_GEM 1378 1.02
ENCHANTED_CHARCOAL 114070 6.01
FLAWED_SAPPHIRE_GEM 148360 1.81
PERFECT_SAPPHIRE_GEM 104689 2.44
FISH_BAIT 1163074 4.25
SNOW_BLOCK 259755 1.15
ENCHANTED_DIAMOND 1787734 1.84
BAZAAR_COOKIE 0 0.0

These numbers range from being spot on (in the case of ENCHANTED_PRISMARINE_SHARD, ENCHANTED_RAW_CHICKEN, FLAWLESS_RUBY_GEM, ENCHANTED_PRISMARINE_CRYSTALS, and ENCHANTED_FIREWORK_ROCKET), to as high as off by a factor of 132.88x, in the case of FINE_JASPER_GEM.

As previously mentioned, the problem is also present in buyVolume, but to a much lesser degree.

**Comment by csjh** [comment]
It might be the case that this is an issue with the in-game bazaar data actually - who should I contact about that?

**Comment by ConnorLinfoot** [comment]
The data does indeed come directly from the SkyBlock Bazaar service, so if there are any issues it's a game bug rather than the API as the game uses the same data provided. You can create a bug report [here](https://hypixel.net/bug-reports/create) to report it, thanks!
