### ISSUE TITLE
Wrong Cause for 503 error in docs.

### ISSUE THREAD

**Issue by Picsou993** [HypixelDev/PublicAPI#445]
In the documentation at [api.hypixel.net](https://api.hypixel.net), all 503 errors (the ones at the right) are saying that it's caused by **Leaderboard data has not yet been populated** even if the endpoint is not a leaderboard: https://i.imgur.com/ArgvfUI.png

**Comment by ConnorLinfoot** [comment]
This is due to the documantation using a component, so they all share the same example.
