### ISSUE TITLE
None of the transport packages can be found by gradle

### ISSUE THREAD

**Issue by HydroPage** [HypixelDev/PublicAPI#449]
I attempt installing any of the new transport packages as stated in their pages using Gradle and declaring the proper repository. Gradle finds none of them
```
Could not resolve net.hypixel:hypixel-api-transport-reactor:4.0.

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```
All of them do this when I use the recommended gradle import in each one's page of the readme.
PS: HypixelAPI 3.0.0 imports just fine from the same repo

**Comment by ConnorLinfoot** [comment]
Are you able to try again now? May be due to the way it was deployed as I originally excluded the parent pom.

**Comment by HydroPage** [comment]
Yes, it worked now, thank you
