### ISSUE TITLE
Missing data in leaderboards

### ISSUE THREAD

**Issue by Picsou993** [HypixelDev/PublicAPI#452]
Some data are missing in the leaderboards. It's the same than in [issue 225](https://github.com/HypixelDev/PublicAPI/issues/225) but with other keys.

- Walls3: monthly_finalKills_a -> Count is 99 but there is only 7 players.
- Walls3: weekly_finalKills_b -> Count is 99 but list is empty.
- UHC: monthly_kills_a -> Count is 99 but there is only 6 players.
- UHC: monthly_wins_a -> Count is 99 but there is only 1 player.
- Quakecraft: kills_a -> Count is 99 but list is empty.
- Quakecraft: kills_b -> Count is 99 but list is empty.
- Walls: monthly_kills_a -> Count is 99 but there is only 69 players.
- Walls: weekly_kills_b -> Count is 99 but there is only 28 players.

Furthermore, the following leaderboards should be removed as they are not used anymore
- TrueCombat: kills_monthly_a (There is still 6 players on it somehow)
- TrueCombat: kills_weekly_b
- SkyClash: kills_a
- Prototype

After a quick test, it looks like that the API is not refreshing until someone request the leaderboard in the lobby by clicking on the leaderboard itself.

**Comment by ConnorLinfoot** [comment]
Thank you, we have removed/fixed any leaderboards necessary.

**Comment by Picsou993** [comment]
`3abe2f6b-d45a-4e22-82d4-f9014569db25` and `bc80e1a5-a192-4681-8a19-ccc054f7fe8c` somehow managed to get back on True Combat monthly and weekly leaderboard.
