### ISSUE TITLE
My API is broken 

### ISSUE THREAD

**Issue by ByKrayToX** [HypixelDev/PublicAPI#454]
I broke my API by dealing a really high damage number. (https://sky.shiiyu.moe/stats/ByKrayToX/Kiwi?cache=true#Dungeons)
But this is not update 
My IGN is ByKrayToX , please fix this.
https://sky.shiiyu.moe/stats/ByKrayToX

**Comment by Picsou993** [comment]
Internal error while looking on its Kiwi profile. Id: `d582ec67b56a41589161bd4f577abbe9`

**Comment by ConnorLinfoot** [comment]
We're no longer fixing these manually as it seems to be a recurring bug with the game. You can submit the bug report at https://hypixel.net/bug-reports if you wish
