### ISSUE TITLE
Under the guild API, guildExpByGameType displays wrong gametype.

### ISSUE THREAD

**Issue by tronving** [HypixelDev/PublicAPI#467]
I was wondering why a simple program to retrieve skyblock guild xp wasn't working, and it turns out all skyblock guild xp is put under the "prototype" section. When sending a request to api.hypixel.net/guild, guildExpByGameType has the option "skyblock" but all skyblock guild xp is put under the "prototype" key. As you can see, I have ~12,000 prototype guild xp, but no skyblock guild xp, even though that's the only game I played.

![SkyblockXPMissing](https://user-images.githubusercontent.com/81777001/132496041-fd251ba1-5348-45bd-92db-a6f767db28c9.png)

**Comment by tronving** [comment]
Upon further testing, it seems the gamemode "the pit" also has this issue, all guild exp earned in "the pit" also shows up in the prototype category.

**Comment by ConnorLinfoot** [comment]
A fix will be deployed for Pit, however, at this time SkyBlock is part of Prototype and this is correct to how its supposed to be categoirized.
