### ISSUE TITLE
Useless skyblock category in guildExpByGameType

### ISSUE THREAD

**Issue by tronving** [HypixelDev/PublicAPI#468]
A fix will be deployed for Pit, however, at this time SkyBlock is part of Prototype and this is correct to how its supposed to be categorized.

_Originally posted by @ConnorLinfoot in https://github.com/HypixelDev/PublicAPI/issues/467#issuecomment-915150762_

Hey again, sorry to recreate this thread, but I wanted to say that I understand that skyblock is a part of prototype, and I was merely suggesting that the "skyblock" key would be removed, as it is useless.

Also, English is not my first language, so I apologize if the grammar I'm using is incorrect.

**Comment by tronving** [comment]
![skyblockexample](https://user-images.githubusercontent.com/81777001/132508937-28a47bb1-0914-4b8a-bfca-00fa0005c73f.png)

**Comment by TheNullicorn** [comment]
Same goes for `LEGACY`, `SMP`, and (for some reason) `REPLAY`

**Comment by ConnorLinfoot** [comment]
I don't think we need to remove these keys as they are automatically populated by our registered gametypes and it does no harm as you can check the value.
