### ISSUE TITLE
2 games with same id?

### ISSUE THREAD

**Issue by palmtree5** [HypixelDev/PublicAPI#47]
I noticed in https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/misc/GameType.md that both Arena and Cops and Crims have the same id. Is this intentional or a typo?

**Comment by Plancke** [comment]
Fixed in https://github.com/HypixelDev/PublicAPI/commit/06a5b5c5efa4d8d8af0603604a02a6b7b33ae9ee
