### ISSUE TITLE
guildKickReason is public.

### ISSUE THREAD

**Issue by Picsou993** [HypixelDev/PublicAPI#473]
Field `guildKickReason` is public in `/player` method but it should be a private field.

**Comment by Picsou993** [comment]
Same goes for `customFilter`.

**Comment by ConnorLinfoot** [comment]
Thanks, updated.

**Comment by mdashlw** [comment]
another day, another loss for the api. sad

**Comment by TheNullicorn** [comment]
`customFilter` and similar player settings would make a good addition to the modding API if that ever sees the light of day. Though agreed that they shouldn't be visible in PublicAPI, at least not by default.
