### ISSUE TITLE
Game Masters have undefined rank using the API

### ISSUE THREAD

**Issue by hanatic** [HypixelDev/PublicAPI#475]
The `/player` endpoint of the API returns a `rank` field which sends a string of the player's rank with most ranks, however Game Masters (recently added) now return `undefined` instead. Evidence:

![image](https://user-images.githubusercontent.com/71867548/135756527-ca805a37-3854-4da6-b127-3bace66486db.png)

**Comment by mdashlw** [comment]
works for me, perhaps you are not extracting it correctly, or treating unknown values as `undefined`

https://api.hypixel.net/player?name=centranos&key= (or https://api.slothpixel.me/api/players/centranos)
![image](https://user-images.githubusercontent.com/34678047/135757862-f1599f66-5eaf-4377-bce7-557a034dba07.png)

**Comment by hanatic** [comment]
Turns out it was an issue with my API wrapper 🤦‍♂️
