### ISSUE TITLE
Missing arcade leaderboards

### ISSUE THREAD

**Issue by eatmyvenom** [HypixelDev/PublicAPI#480]
The `leaderboards` endpoint only reflects the coins leaderboard that is displayed in the arcade lobby. However, arcade contains 17 unique games, 16 of which have leaderboards in lobby. Therefore it would make sense for the leaderboards endpoint to reflect all these games. Also a side request would be a combined arcade wins leaderboard added here.

**Comment by ConnorLinfoot** [comment]
We don't plan on adding these leaderboards at this time, we may look at expanding it in the future similar to other games but not for now.
