### ISSUE TITLE
Frequently getting 504 error, though status.hypixel.net reports the API is up

### ISSUE THREAD

**Issue by tronving** [HypixelDev/PublicAPI#488]
![image](https://user-images.githubusercontent.com/81777001/140635884-b4781395-f33f-4c9a-b730-d3f9053f7dff.png)
I keep getting errors like this when trying to access the api, thought it was a problem with my program at first since it only happens every 1/7 or so responses, but its significantly slowing down my program, how can I work around this? Or is it a server issue?

**Comment by mdashlw** [comment]
the api is currently having issues, you can only wait and pray that it gets fixed soon

**Comment by ConnorLinfoot** [comment]
These issues seemed to be resolved now as I'm unable to replicate and currently seeing no 504's from Cloudflare, can you confirm?

**Comment by TheKodeToad** [comment]
This problem seems to have come back.
