### ISSUE TITLE
API error code:500

### ISSUE THREAD

**Issue by ByKrayToX** [HypixelDev/PublicAPI#491]
I have this issue for 5months and asked hypixel to fix it but they didn’t. The error is caused to my high amount of damage. Hypixel can’t read this Number and skycrypt too so the api can’t load. Please fix it or tell me how i can. (My profile in game is :ByKrayToX, you can try in skycrypt to see the error)

Thanks.

**Comment by ConnorLinfoot** [comment]
This is a bug within the game, and not the API. You can report game bugs here; https://hypixel.net/bug-reports/create

**Comment by ByKrayToX** [comment]
> This is a bug within the game, and not the API. You can report game bugs here; https://hypixel.net/bug-reports/create

I already do 5 post and the same guy answer and didn’t do anything. I saw someone ask here and his api get fix
