### ISSUE TITLE
API broken?

### ISSUE THREAD

**Issue by Xeitalys** [HypixelDev/PublicAPI#493]
Whenever I enter my name on SkyCrypt or sky.lea.moe an error message pops up saying "Hypixel API Error: Internal Error." This has been going on for roughly 10 months now. I've tried obtaining new API keys but the issue still persists.
![hypixelapibugreport](https://user-images.githubusercontent.com/61106621/144778664-31ef0036-b945-43f3-9874-eb9bdab61c9e.png)

**Comment by ConnorLinfoot** [comment]
This is likely due to a bug with your SkyBlock data, you can report this at https://hypixel.net/bugs
