### ISSUE TITLE
Deprecate the guild permission resource (?)

### ISSUE THREAD

**Issue by TheNullicorn** [HypixelDev/PublicAPI#496]
`/resources/guilds/permissions` was added in ed6ccad4 as one of the original resource endpoints, but hasn't really seen any love since then.
 - Its last update was on the same day it was released
 - The information it provides is no longer relevant anywhere in the API
   - Previously we had `guild.ranks[i].permissions`<sup>[1](#fn1)</sup>, but that eventually became hidden
- Even when it was relevant, all it provided was unsorted* english translations
  - *there isn't a key or identifier to map those translations to the permissions they represent

If the endpoint is getting traffic or people are finding a use for it, I can close this. But frankly it seems obsolete.

[1] <a name="fn1">https://hypixel.net/posts/13600397</a>

**Comment by ConnorLinfoot** [comment]
Seems correct that the endpoint isn't needed, it was just copied over when we moved to the resource's endpoint. 

Looking at the requests the endpoint is almost never called, so I think it's safe for us to just remove it since I can't see any possible reason for this actively being used, thanks! 😄
