### ISSUE TITLE
BIN boolean value missing from non-BIN auctions

### ISSUE THREAD

**Issue by csjh** [HypixelDev/PublicAPI#503]
Just a minor thing but it would be nice if you added a `"bin": False` to non-BIN auctions for consistency sake. At the moment, there's only `"bin": True`.

**Comment by Ekwav** [comment]
Seems like this is the case now. NotEnoughCoins had issues with it existing.

**Comment by ConnorLinfoot** [comment]
Yeah, this has now been changed to always include the boolean. I did hope people weren't relying on the field solely existing but anyone who is doing so will need to change it to check the boolean now.
