### ISSUE TITLE
My api is broken

### ISSUE THREAD

**Issue by ByKrayToX** [HypixelDev/PublicAPI#506]
I broke my API by dealing a riciculously high damage number.
https://sky.shiiyu.moe/stats/ByKrayToX
My IGN is ByKrayToX, please fix this, it's been 7months since I submitted a bug report on the forums.

**Comment by ConnorLinfoot** [comment]
Unfortunately, as this is a bug within the game it isn't an issue with the API itself.

**Comment by mdashlw** [comment]
> Unfortunately, as this is a bug within the game it isn't an issue with the API itself.

@ConnorLinfoot why would the api crash though? is it trying to deserialize it into int? isn't it supposed to just dump the whole document without much processing?
