### ISSUE TITLE
Install/Get Started Guide

### ISSUE THREAD

**Issue by chriscn** [HypixelDev/PublicAPI#52]
Someone needs to make a get started guide, I can only find one resource on it and that seems to be very outdated and not work anymore. For example a spigot plugin example.

**Comment by Plancke** [comment]
We are currently swamped with the release of our China network in collaboration with NetEase so we haven't been able to spend as much time on this as we'd like.

Once this has been completed I can look into deploying this to a public Maven repo/Gradle dependency which make things a lot easier.

**Comment by chriscn** [comment]
@Plancke Hi, thanks for you reply! Do you have any idea of when this could happen? I understand that you are very busy just for the life of me I can't get it working!

**Comment by Minikloon** [comment]
I recommend checking out how to use Maven for your Bukkit plugins, it's really useful.

If you're looking for a temporary solution so that your project is easily shareable, you can use Jitpack https://jitpack.io/#HypixelDev/PublicAPI/-SNAPSHOT.

**Comment by chriscn** [comment]
@Minikloon I have been using maven for a while now and really enjoying it because I just have to edit a file and it all works! But the jitpack things seems to be what  I needed! It would be good if you could get it on the public maven one but this is as good as it gets for now!

**Comment by Plancke** [comment]
Merged the PR that adds jitpack to the readme
