### ISSUE TITLE
Key Throttle for Unformatted Auth Keys

### ISSUE THREAD

**Issue by notKnei** [HypixelDev/PublicAPI#527]
Upon requesting any endpoint with a non-formatted API key(UUID4 Key) it results in a response of
```json
{
  "success": false,
  "cause" : "Key Throttle",
  "throttle": true
}
```
While requesting with a non-formatted Player UUID4 string will still result in a profile being fetched.
Unsure if this is intended or just a missed line.

**Comment by ConnorLinfoot** [comment]
Thanks for reporting, the issue has now been fixed!
