### ISSUE TITLE
[Enhancement] Transition from Joda-Time to Java 8 Date-Time APIs

### ISSUE THREAD

**Issue by themadmillenium** [HypixelDev/PublicAPI#53]
The Java implementation of the HypixelAPI makes extensive use of lambdas, a feature introduced in Java 8. However, Java 8 also introduces new date-time APIs, which provide near-identical facilities to those in Joda-Time.

Transitioning to Java 8's built-in facilities would eliminate a dependency, and reduce sizes of compiled JAR files, etc. This difference might be negligible, but hey, it's still a difference, with one less dependency to download. Testing the performance of JSON parsing with each date-time API, no major improvement or drawback was noted.

I've forked the master branch, and made the appropriate changes for you to review at https://github.com/themadmillenium/PublicAPI/commit/15af888109b878f17e8249d13d43bab90382f9f1.

**Comment by Plancke** [comment]
Could you update the Readme and the Maven pom to finish the changes? 
Once that's done, feel free to open a PR so we can merge it in.

**Comment by themadmillenium** [comment]
Done and dusted. Cheers!

**Comment by Plancke** [comment]
Merged https://github.com/HypixelDev/PublicAPI/pull/54
