### ISSUE TITLE
Get Player Rank

### ISSUE THREAD

**Issue by DongShaoNB** [HypixelDev/PublicAPI#531]
Hello, players have MVP+ or MVP++ all show MVP_PLUS

**Comment by Picsou993** [comment]
Hi, this is not a bug. MVP++ is a monthly rank and not a permanent rank so it is stored at `monthlyPackageRank`.
You can read more information about how to get the rank of a player at https://github.com/HypixelDev/PublicAPI/wiki/Common-Questions#how-do-i-get-a-players-rank-prefix.

**Comment by DongShaoNB** [comment]
> Hi, this is not a bug. MVP++ is a monthly rank and not a permanent rank so it is stored at `monthlyPackageRank`. You can read more information about how to get the rank of a player at https://github.com/HypixelDev/PublicAPI/wiki/Common-Questions#how-do-i-get-a-players-rank-prefix.

ok thank you, i have other problem,how to get player hypixel level

**Comment by Picsou993** [comment]
That is on the same page: https://github.com/HypixelDev/PublicAPI/wiki/Common-Questions#how-do-i-find-a-players-network-level.
If you have any more question feel free to create a discussion and not an issue instead.

**Comment by DongShaoNB** [comment]
> If you have any more question feel free to create a discussion and not an issue instead.

ok thx
