### ISSUE TITLE
Skyblock profile randomly doesent include banking data

### ISSUE THREAD

**Issue by Soopyboo32** [HypixelDev/PublicAPI#532]
For some reason the banking data in a skyblock profile is sometimes an empty object
![image](https://user-images.githubusercontent.com/49228220/162611541-14ff349b-0e1e-44ef-9e1c-2d203d656701.png)

instead of actually including the data
![image](https://user-images.githubusercontent.com/49228220/162611557-7ff64cba-e40e-4ebd-b76c-ea80bc08bd3f.png)

(this issnt caused by the person disabling banking API, as if the person disables banking API it wont include the banking object at all)
![image](https://user-images.githubusercontent.com/49228220/162611669-66f676f8-84e9-4250-9714-da8ae3c1cc9d.png)

**Comment by ConnorLinfoot** [comment]
Thanks for reporting, this is due to one of our API nodes not being updated with some recent changes and should now be resolved!
