### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by grahhnt** [HypixelDev/PublicAPI#539]
As of yesterday the PublicAPI library causes an SSL error while accessing api.hypixel.net. It appears that yesterday the SSL cert was updated.

I'm using the library in a Minecraft 1.8.9 mod

```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by grahhnt** [comment]
![image](https://user-images.githubusercontent.com/46821216/166553724-4cbe56f4-1592-4f1a-bc04-586a9cb781e2.png)
SSL cert for api.hypixel.net

**Comment by PyICoder** [comment]
Having similar issues, this makes the api unusable which is inconvenient for mod developers.

**Comment by ConnorLinfoot** [comment]
Hey, this was caused due to Cloudflare issuing a Let's Encrypt certificate (which is not supported in older versions of Java 8). We have had a different CA issued certificate to now resolve this.
