### ISSUE TITLE
WoolGames Data Bug

### ISSUE THREAD

**Issue by Polsulpicien** [HypixelDev/PublicAPI#543]
In the WoolGames data with the `/player` API endpoint, there are some bugs. For some players, you can't get the wins/games played per classes, only the global wins and games played.   

*See my stats, Polsulpicien, below:*
![image](https://user-images.githubusercontent.com/70817001/172055980-2de44f3d-8f95-4959-9e59-2c883c801110.png)

**And what it should look like (JthaloTime, top 1 wool wars stars leaderboard):**  
![image](https://user-images.githubusercontent.com/70817001/172056011-5221de43-8000-493a-bebe-929be960c02d.png)

And before you ask, yes I have won some games, otherwise why would I have 21 overall wins 😄

**Comment by ConnorLinfoot** [comment]
The wins and games per class are outdated fields and no longer tracked.

**Comment by Polsulpicien** [comment]
Oh, sad because it could be a good thing :/
