### ISSUE TITLE
Missing keys under nether_island_profile_data in Skyblock Profile

### ISSUE THREAD

**Issue by MattTheCuber** [HypixelDev/PublicAPI#547]
Hello,

I understand that some keys were removed from the API recently most likely because they revealed too much quest information for the Kuudra Manible Hunt (I could be completely wrong lol). However, several of these keys revealed nothing and developers had already started relying on. Specifically I am talking about the `nether_island_profile_data.quest_data.quest_list`, `nether_island_profile_data.quest_data.quest_rewards`, `nether_island_profile_data.quest_data.miniboss_daily`, and `nether_island_profile_data.last_reset`. These only relate to the daily quests that players can complete to gain faction reputation. These keys were very beneficial as users could easily see what they had left to complete and we could link summaries or guides on how to complete each quest. Yes, we spent several days just figuring out what every single daily quest key corresponded to.

Thank you for reading,
Skyblock Developers

**Comment by ConnorLinfoot** [comment]
These keys are intended to be hidden and should never have been in the API, sorry for the inconvenience.
