### ISSUE TITLE
[SkyBlock] Some auctions can't be gotten by UUID

### ISSUE THREAD

**Issue by mat-1** [HypixelDev/PublicAPI#550]
Sometimes when I try to fetch an auction by its UUID, the `auctions` array is empty.

Example: https://api.hypixel.net/skyblock/auction?uuid=d566aacc1e794a95b171c10dbbf86746&key=

I know for a fact that this auction UUID exists, because I got it from an auction_id in the auctions_ended endpoint. This happens for maybe around half of the auctions I tried, and there doesn't seem to be any obvious pattern.

**Comment by mat-1** [comment]
It seems that it's actually the auctions_ended endpoint that's wrong, I'm gonna close the issue for now and test some stuff.

**Comment by ConnorLinfoot** [comment]
It's worth noting that once all parties claim an auction it's no longer stored in our standard auctions database and is archived. At this point, the API won't be able to see it anymore and thus the lookup will fail. This specific auction mentioned was archived 6 minutes after ending, so it's possible it was already archived by the time it was looked up.
