### ISSUE TITLE
Dropper missing in endpoints.

### ISSUE THREAD

**Issue by Picsou993** [HypixelDev/PublicAPI#555]
`"DROPPER":"Dropper"` is missing in the `modeNames` of the `/resources/games` endpoint.

In addition of that (and probably a consequence of that), `mode` and `map` are set to `null` in the `recentGames` endpoint:
![image](https://user-images.githubusercontent.com/33390780/180861860-bf09f780-9601-4e86-916a-65d268c6b4e6.png)

**Comment by ConnorLinfoot** [comment]
Modes are not currently guaranteed to be part of the endpoint.

> As a fallback you can also take the mode key, replace the underscores with a space and capitalize each word, this is what we currently do for Game History and Replay's internally that also use this exact same data.

At this time, Prototype does not support "modes" in the traditional sense due to them being a "prototype mode". So for now these will remain null with modes and maps.
