### ISSUE TITLE
Enchanted Books and essence missing ExtraAttributes id field

### ISSUE THREAD

**Issue by csjh** [HypixelDev/PublicAPI#560]
All other items on the bazaar have an ExtraAttributes id field denoting what their identifier is on the /skyblock/bazaar endpoint except for enchanted books and essence with the new update. 

Would it be possible to add that to them (at least enchanted books) for the sake of standardization?

**Comment by ConnorLinfoot** [comment]
Can you provide more information on what field you are referring to? I'm not noticing a difference between the enchants vs other items.

**Comment by Picsou993** [comment]
I think what they are talking about is the NBT data of the item itself. If you get the NBT using eg `inv_content` from the `skyblock/profile` endpoint, all items have an `id` field in their `ExtraAttributes` field. However for enchanted books the field `id` in `ExtraAttibutes` is only retrieving the id of the enchanted book without the value of the enchant. So it's not possible to use the id to get this key to get the exact book for the bazaar endpoint.
 
![image](https://user-images.githubusercontent.com/33390780/186146453-24ef52c9-a4a8-4c31-8c2e-e50374bdb7e4.png)
![image](https://user-images.githubusercontent.com/33390780/186146688-93397c78-a086-4bcd-9e40-5cf129e8b919.png)
Here `id` is `ENCHANTED_BOOK` but I believe they would like it to be `ENCHANTMENT_FEATHER_FALLING_6`.

**Comment by ConnorLinfoot** [comment]
In that case this isn't an issue within the API and is unlikely to be changed. The NBT data in profiles is just raw data, so whatever the game uses/needs is what is there.

**Comment by csjh** [comment]
> In that case this isn't an issue within the API and is unlikely to be changed. The NBT data in profiles is just raw data, so whatever the game uses/needs is what is there.

In that case, would it be possible to add the names of the items to the endpoint? Would serve the same purpose
