### ISSUE TITLE
Inconsistencies in "last_save" in /skyblock/profiles

### ISSUE THREAD

**Issue by artificialair** [HypixelDev/PublicAPI#562]
This started about 7 hours before I'm posting this, the "last_save" property for players in each profile is not always showing when I get from the "api.hypixel.net/skyblock/profiles" URL.

**Comment by UP929312** [comment]
I'm experiencing this issue as well

**Comment by ConnorLinfoot** [comment]
The field should no longer show for any members, and this change is intentional.

**Comment by UP929312** [comment]
I agree with Matt heavily, without forcing users to input a profile name, we use this to detect their last played profile (without doing another API call), can we somehow have a field which shows it was last played or something then?

**Comment by SKTPentagod** [comment]
Agreed^

**Comment by ConnorLinfoot** [comment]
We have added a field of `selected` in the profiles endpoint that will be true for the currently active profile

**Comment by MattTheCuber** [comment]
Thank you very much!
