### ISSUE TITLE
Data inconsistencies between two endpoints.

### ISSUE THREAD

**Issue by ate8tee** [HypixelDev/PublicAPI#569]
Hi.

I have noticed the object name of a few games in `/resources/achievements` violating the GameTypes, therefore making it incompatible with `/resources/games`.

Example: 
- Cops and Crims using `copsandcrims` instead of `MCGO`.
- Warlords using `warlords` instead of `BATTLEGROUND` or `Battleground`.

While it is a minor impact, having to write a list will increase the file size for a project.

It'd save more space by fetching `/resources/achievements` and having them pre-populate the page. (Like how Hypixel does it here: [[1]](https://hypixel.net/player/ciulinuwu/achievements))

Then - Compare data from `/player` to highlight the unlocked achievements while keeping the locked ones around.

**Comment by mdashlw** [comment]
Changing the keys in `/resources/achivements` would mean changing it in `/player` under `achievements` and `achievements_one_time` (or whatever it's called), which likely won't happen

**Comment by ConnorLinfoot** [comment]
Achievement handlers aren't strictly tied to a game and internally are just provided for each game manually. This is why there are non-games there, such as "easter".
