### ISSUE TITLE
Hypixel API Returns Integer on GuildReply for guild.guildExpByGameType, causing NumberFormatException

### ISSUE THREAD

**Issue by DersWasTaken** [HypixelDev/PublicAPI#570]
Hello! I recently was working on a JDA Discord Bot which accesses the api, when I came across an error. 

`Exception in thread "DefaultDispatcher-worker-2" java.lang.IllegalStateException: java.util.concurrent.ExecutionException: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 2687175922 at line 1 column 31206 path $.guild.guildExpByGameType.`

This seemingly happens because in [GuildReply](https://github.com/HypixelDev/PublicAPI/blob/master/hypixel-api-core/src/main/java/net/hypixel/api/reply/GuildReply.java) the guildExpByGameType is a <GameType, Integer> map, but in certain instances, for example "The Dawns Awakening" guild, the actual number is larger than Integer.MAX.

This can easily be fixed by changing it from a Int to a Double/Long.

It is currently late at night for me, so I cannot make a PR, but if one is not made by tomorrow I will do so.

**Comment by DersWasTaken** [comment]
Note, the error is being thrown when attempting to get the guild data, NOT when trying to get the guild exp for a specific gamemode

Sample Code:
```kt
val guild = DawnBot.api.getGuildByPlayer(uuid).get()
```

**Comment by DersWasTaken** [comment]
Just found a PR with the exact same issue and a fix for it, its been 117 days since the PR was made.
https://github.com/HypixelDev/PublicAPI/issues/536

**Comment by ElotherYT** [comment]
I've been getting the exact same issue, is there an ETA of when this would be resolved by?

**Comment by ConnorLinfoot** [comment]
Fixed in #553
