### ISSUE TITLE
Negative Bedwars Experience

### ISSUE THREAD

**Issue by Polsulpicien** [HypixelDev/PublicAPI#581]
I just noticed a player with some negative Bedwars Experience, I don't think this is normal.
![image](https://user-images.githubusercontent.com/70817001/226989280-0c9e2adf-c5ab-4aec-b893-15a001595086.png)
Player uuid: `7d933d2c489a4e929952095f756bd174` (`Deo`)

**Comment by ConnorLinfoot** [comment]
Not an API issue, since the API just provides data from the stats database.

**Comment by Polsulpicien** [comment]
Where can I report it then? Or will you report it internally ?
