### ISSUE TITLE
[Skyblock] last_save not updating

### ISSUE THREAD

**Issue by Soopyboo32** [HypixelDev/PublicAPI#596]
Profiles `last_save` data in `skyblock/profiles` -> `profiles[profile].last_save` is not updating
eg my current profile has a last_save of 14 days ago (as of time of writing this) when it should be ~5mins ago

(i am talking about profile based last_save, not the one in `profiles[profile].members[member].last_save` as profilemember based last_save was removed)

**Comment by ConnorLinfoot** [comment]
This field was added to assist with the recent migration of the profile storage system, and since then we stopped updating it as profiles were split out from other data and we no longer needed to track this. This field has now been removed.
