### ISSUE TITLE
Missing totalQueries

### ISSUE THREAD

**Issue by VolgarIII** [HypixelDev/PublicAPI#597]
Hello,

Is there any reason why the `totalQueries` as been removed from the `/key` endpoint?
It is still specified in the documentation and it was useful to check that our key was not compromised.

Regards,
VolgarIII

**Comment by ConnorLinfoot** [comment]
This was removed accidentally during some internal migrations in preparation for the upcoming developer dashboard, we've added this back now.

We do plan to deprecate the /key endpoint in the near future, with all the information it provides in the headers or in the new dashboard. But we'll be announcing that with a timeline for removal in the thread with the release of the dashboard.
