### ISSUE TITLE
[Bug] Key information in dev-api/legacy is wrong

### ISSUE THREAD

**Issue by matteopolak** [HypixelDev/PublicAPI#603]
Viewing my key at https://dev-api.hypixel.net/key/legacy shows the following information (redacted most of it):

```json
{
	"key": {
		"id": "...",
		"key": "...",
		"owner": "...",
		"type": "LEGACY",
		"usable": true,
		"limit": 120,
		"limitDuration": 60000,
		"totalQueries": 0,
		"created": 0,
		"allowedIps": []
	}
}
```

However, my key only has a limit of 60, as seen by https://api.hypixel.net/key:

```json
{
	"success": true,
	"record": {
		"key": "...",
		"owner": "...",
		"type": "LEGACY",
		"limit": 60,
		"totalQueries": 0,
		"queriesInPastMin": 0
	}
}
```

The second one is correct, as it matches all of the `RateLimit-*` headers correctly.

**Comment by ConnorLinfoot** [comment]
Legacy keys aren't something we support in the developer dashboard, hence the mismatched response.
