### ISSUE TITLE
[BUG] Translated languages used instead of English

### ISSUE THREAD

**Issue by Clemintina** [HypixelDev/PublicAPI#607]
Hello,

I have discovered a small bug within the `player.stats.Bedwars.favourites_2` response. For example, Korean is shown in the response from the player `1b4ef49494ef4415b02713d980221f29` - `Youshin2009`. It appears to only be an issue with rotational items.

My sample from this player

`wool,거미줄,chainmail_boots,obsidian,bow,jump_v_potion_(45_seconds),tnt,fireball,iron_sword,blast-proof_glass,shears,arrow,invisibility_potion_(30_seconds),water_bucket,wooden_pickaxe,wooden_axe,oak_wood_planks,golden_apple,end_stone,ladder,magic_milk`

Regards
Kay

**Comment by ConnorLinfoot** [comment]
Player data endpoint just offers data from the game itself, so this isn't a bug with the API and just more how the game stores that data
