### ISSUE TITLE
Combo Duels hits/swings bugged.

### ISSUE THREAD

**Issue by Dueel** [HypixelDev/PublicAPI#616]
When trying to make a command using the duels endpoint specially combo duels, it seems like the the endpoints for Hits & Swings for combo are a bit different as some/many hits are not counted as swings.

Example one (qukc Number 1 Combo Duels Player):
![image](https://github.com/HypixelDev/PublicAPI/assets/105398949/e4975cfc-ce72-4f39-a6d0-54e0ab172fcf)

Example two (Shaidynn):
![image](https://github.com/HypixelDev/PublicAPI/assets/105398949/dbb5d93e-97cc-460c-932d-e9724c32e685)

Endpoints in question:
```json
{
"player": {
    "stats": {
        "Duels": {
            "combo_duel_melee_swings": 3686586,
            "combo_duel_melee_hits": 2438041,
            },
        },
    },
}
```

This might be a issue with out Duels endpoints but this is the only once I have checked.

**Comment by mdashlw** [comment]
Issues like this are usually redirected to https://hypixel.net/forums/server-bug-reports.35/ . API just returns the data in the database. If it's counted wrong, it's a game bug.

**Comment by Dueel** [comment]
> Issues like this are usually redirected to https://hypixel.net/forums/server-bug-reports.35/ . API just returns the data in the database. If it's counted wrong, it's a game bug.

Yeah probably, should have considered that first. It is a game bug & seems to be a old bug but I'll leave this up for the moment being but I'll also report it on their website.

**Comment by ConnorLinfoot** [comment]
As mentioned already this is not a bug with the API as it just reports stats from the players game data.
