### ISSUE TITLE
Skyblock "Auctions" endpoint does not return ID.

### ISSUE THREAD

**Issue by Facundo-Barbera** [HypixelDev/PublicAPI#617]
## Summary
When requesting a page using the endpoint `https://api.hypixel.net/skyblock/auctions` a field should be included called "_id" in each of the auctions according to the [Hypixel Public API](https://api.hypixel.net/#tag/SkyBlock/paths/~1skyblock~1auctions/get). The only unique identifier included is the UUID.

## Note
This is a big problem since the Recently Ended Auctions endpoint (`https://api.hypixel.net/skyblock/auctions_ended`) only includes auction_id and not UUID, which prevents to keep track of auctions that have ended without having to create an additional request to the API (Via `https://api.hypixel.net/skyblock/auction`)

**Comment by ConnorLinfoot** [comment]
It's probably a mistake in the documentation to include the `_id` field as I don't think we have a reason to expose this for auctions specifically, so I'll look to remove that soon. 

The `auction_id` of a recently ended auction is the UUID of said auction, you can see this by it being 32 characters in length, whereas a Mongo object ID is 24 characters. This is just an unfortunate implementation inconsistency with the way it was implemented, but they are comparable.

**Comment by ConnorLinfoot** [comment]
I've removed the mention of _id from the documentation now to remove any confusion.
