### ISSUE TITLE
Remove Base64 Image Assets

### ISSUE THREAD

**Issue by FreeMoneyHyb** [HypixelDev/PublicAPI#620]
The api when sending a request to get all info has many base64ed images. i presume that for most devs its an incovience. possibly remove these. makes people need to use a json path finder

**Comment by ConnorLinfoot** [comment]
We are unaware of any endpoints that return base64 images, you will have to be more specific to what endpoint you are referencing.

**Comment by Picsou993** [comment]
I think he is talking about the `skin` field available for `SKULL_ITEM` materials in `resources/skyblock/items`.
However I don't see why not having them would let you use something else than a json path finder as result would be in JSON anyway @FreeMoneyHyb.

**Comment by FreeMoneyHyb** [comment]
my bad some of this may not be image data but its is enlarged with some encryption for 0 reason.
x.profiles[(some profilenumber)].members.(some uuid).inv_armor.data 
x.profiles[(some profilenumber)].members.(some uuid).inv_contents.data 
x.profiles[(some profilenumber)].members.(some uuid).wardrobe_contents

Theres alot more thats encrypted dont think this is base64 but its large and makes looking through the data confusing for someone whos new to coding.
![image](https://github.com/HypixelDev/PublicAPI/assets/83422129/1c5b00ca-4247-406b-b207-71341a01b1dc)
@ConnorLinfoot

**Comment by ConnorLinfoot** [comment]
This data is the inventory data as described in the API documentation, we won't be removing this as the majority of SkyBlock based websites use this data.
