### ISSUE TITLE
Profile Member `deletion_notice` Field Missing

### ISSUE THREAD

**Issue by ptlthg** [HypixelDev/PublicAPI#622]
The `deletion_notice` field was added in #170 

It was still available after the API v2 migration, but suddenly no longer appears. I'm not sure when this happened, but it's been a few days since I noticed.

I transitioned all of my backend code to use this field to recognize deleted members because of how useful it is, as discussed in the original issue. Without the field, I now have broken links to deleted profile members, with the only alternative being to use a whole new `/profiles` API request for each member to update the deletion status.

### Example
https://api.hypixel.net/v2/skyblock/profile?profile=7da0c47581dc42b4962118f8049147b7

Both `7b7f77d1f8864096b4c78610f5fa7adb` and `c47c034cd45e4a748b6f42acef5de6bc` should (and used to) have this property

(Side note: This field was in the root of the member object, it would make a lot of sense to instead be under `profile` alongside `coop_invitation`)

**Comment by Nitroholic** [comment]
This issue should now be fixed. The key was missing in the mappings and has now been added and is showing in the API accordingly.
