### ISSUE TITLE
Developer dashboard indefinitely reloading

### ISSUE THREAD

**Issue by SylveonBottle** [HypixelDev/PublicAPI#626]
Tested with firefox, chrome, and edge.

![firefox_QziOKT2JXs](https://github.com/HypixelDev/PublicAPI/assets/17802843/8719848a-fb9f-45b9-9642-3c617fad1fa2)

**Comment by ConnorLinfoot** [comment]
Bug reports can be created at https://hypixel.net/bug-reports/create, however, please provide as much information as possible including any information provided in the F12 console, as we are unaware of any issues at this time. I would also recommend trying another browser or device.
