### ISSUE TITLE
Bingo Data goals is null and missing Community goals description.

### ISSUE THREAD

**Issue by HacktheTime** [HypixelDev/PublicAPI#627]
When the new bingo card is revealed the goals are reset to null.

{"success":true,"lastUpdated":1709014095252,"id":27,"goals":null}

The id is for next bingo event already. 27+1 = 28 Current

The Community goals descriptions are also missing when those goals are in the api.

**Comment by HacktheTime** [comment]
For clarity the request for this was sent an hour and ~8 Minutes after the card is revealed via npc.

**Comment by ConnorLinfoot** [comment]
The data seems to be populated currently unless I'm misunderstanding the issue. The data isn't populated instantly based on in-game due to how the game publishes data to the API if that is the concern.

**Comment by HacktheTime** [comment]
I can understand that updating may take some time but 6 and a half hours might be a bit much. It would be cool to get it via api at roughly the same time to allow sending card reveals in dc fully automated, but I dont have access to the code so I dont know how it is handled and how complex it would be to fix this.

Out of that perspective there is also data that would be useful to access. For example we cant really keep track of which bingo type it is and which occurrence it is. (Like Extreme Bingo #3) with automated measures. A point based system is not working fully since points overlap between extreme and normal.

**Comment by ConnorLinfoot** [comment]
You're correct that it shouldn't be reaching the point of 6 hours so that is likely a bug causing it not to be ready until servers reboot or something along those lines. We'll investigate and hopefully roll a change as soon as possible, but we won't know for sure if the issue is resolved until the start of the next event of course. I'll also see if we can add information regarding community goals but I'm unsure if that's easily possible right now.

As for the extreme bingo point, I'll see if we can add more context to the endpoint when we roll out the fix for the above issue.

**Comment by HacktheTime** [comment]
Yeah, testing solutions for things like that is hard and very annoying since it can't really be tested. I have a setup which is more or less testing it automatically anyway, so I can let you know if it happens next bingo.

I made a suggestion which is not up-to-date with my better understanding now from when I posted it. (#624 )

I combined the most important parts here and updated them where I got some more insight on in the past months, since I believe I understand it better now. All of those are additional. The only thing I want is that they were seen. And I believe I was able to achieve that now. I want them to be on the table, not necessarily that they get implemented.

- We could use the bingos display name (Extreme Bingo # 1 etc)
- Bingo type like a enum perhaps
- A public goal list with and all possible (Community and normal) goals with description and the even type they can happen in. The list in the wiki is not that good because it's often not up to date, and it's lacking the api names. Possibly replace the amount in the goal with %d since it changes with the tier.
  - I'm aware that this is not really possible with the current system though. But the data is probably worth enough to argue about this.
- a Historic Bingo API based on event id. I tried to get the data from other sources, which thought could be possible, but noone seems to have that data stored. This is so we can calculate max rewards of previous bingos.
  - (amount of people participated in each goal) [just a thought, seems like very small rewards for effort it takes to make]
  - amount of people that completed the card
- API access to all bingo contribution amounts in the profile api locked behind collections toggle
- Calendar API
  - I got some insight from a member in the resource creator discord, and know It's nothing new and don't expect it to come but wanted to mention it again because it would be an extremely powerful to get.

**Comment by ConnorLinfoot** [comment]
We've deployed some changes to the endpoint that should aim to resolve this issue, updated documentation of the additional information is available at https://api.hypixel.net/#tag/SkyBlock/paths/~1v2~1resources~1skyblock~1bingo/get

**Comment by HacktheTime** [comment]
> We've deployed some changes to the endpoint that should aim to resolve this issue, updated documentation of the additional information is available at https://api.hypixel.net/#tag/SkyBlock/paths/~1v2~1resources~1skyblock~1bingo/get

I would like to point out that the "name" attribute which is referred to as "display name" in its explanation does not match at least my definition of a display name.

![grafik](https://github.com/HypixelDev/PublicAPI/assets/131038646/c97e1569-8fcb-4b09-985c-0cee96b3747b)
![grafik](https://github.com/HypixelDev/PublicAPI/assets/131038646/464f916d-32e1-4b9e-82d3-e7af11a9d42a)

I would refer the red arrow marked attribute as a display name of the bingo.
![grafik](https://github.com/HypixelDev/PublicAPI/assets/131038646/8a19a7d1-fd92-4dd3-b0ef-4f822b76b9af)

I would also like to point out that it would be good to have documentation of how secret Bingo with its tips and name reveals behaves.

It should also be considered to add a new field for secret bingo when the next of any tipp type is revealed (name and tipps themself). That would mean that tipps can be noticed without spamming API reducing the requests significantly during secret bingos.
