### ISSUE TITLE
Missing Data in ['player']['stats']['Walls3']

### ISSUE THREAD

**Issue by merry-git** [HypixelDev/PublicAPI#635]
when pulling data from `['player']['stats']['Walls3']`, there is missing endpoints for the zombie class in mega walls. Every other class has these endpoints. This makes it hard for people to check their stats such as their FKD, KD, and overall progress. Popular bots like HyStats as well as my personal one cannot pull data about the `Zombie` class. 

When I run `grep -i "zombie" response.json`, I only get 3 results. Conversely, when running `grep -i "enderman" response.json`, I get 155 results. This implies that there is quite a bit of data that is missing from the zombie class.

Listed below, here are _some_ examples of endpoints that are missing for only the zombie kit. This is **not** all of the endpoints that are not present.

`data` is defined as the response.

1. `data['player']['stats']['Walls3'][`zombie_final_deaths_standard']`
2. `data['player']['stats']['Walls3'][`zombie_final_kills_standard']`
3. `data['player']['stats']['Walls3'][`zombie_final_assists_standard']`

**Comment by Picsou993** [comment]
I have checked on my own data and I have been able to find these fields (username: `Picsou993` - UUID: `c30ef18f85a6492b8ad6d3df445c4575`).
If the player you have checked has never got the data for these then it's normal that these fields are not present.
![image](https://github.com/HypixelDev/PublicAPI/assets/33390780/ed8340e4-3104-46e5-9c6a-4cc810cf1a38)

**Comment by ConnorLinfoot** [comment]
The player data endpoint provides whatever data exists on the player, if there is data missing for the stats of a specific game it's because that data simply does not exist and is not a bug with the API itself
