### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by 1leuc** [HypixelDev/PublicAPI#636]
dont know how to exactly fix it but my ign is i_hate_skyblock and when i type it in skycrypt i get Hypixel API Error: Internal error.

**Comment by DuckySoLucky** [comment]
Hello, this is the SkyCrypt developer. Currently, the Hypixel Public API is experiencing issues. Please try again later as we patiently await a fix.

**Comment by 1leuc** [comment]
do you know an estimated time?

**Comment by DuckySoLucky** [comment]
2-3 business days

**Comment by 1leuc** [comment]
https://github.com/HypixelDev/PublicAPI/assets/83911278/9357ea50-d516-44a1-9299-293fdda07410
