### ISSUE TITLE
Refined Jyrre count is incorrect

### ISSUE THREAD

**Issue by MattTheCuber** [HypixelDev/PublicAPI#639]
## Issue
`profileData.leveling.REFINED_JYRRE` is incorrect. It display as `4` if the player actually has actually drank 5.

## Proof
![image](https://github.com/HypixelDev/PublicAPI/assets/32849887/8fce94a6-2177-4338-a4f1-78d36dee38ee)

![image](https://github.com/HypixelDev/PublicAPI/assets/32849887/e0f22dd9-3a48-4d7e-bb15-97493cbdeb15)

**Comment by MattTheCuber** [comment]
@AzureAaron mentioned that it could be zero-based (not present if 0). I confirmed this *could* be true by checking a profile with 0 drank:

![image](https://github.com/HypixelDev/PublicAPI/assets/32849887/310381a3-854a-46d8-bfe4-a616a6acabda)

If this is the case, it would be great to simply know this.

**Comment by AzureAaron** [comment]
> @AzureAaron mentioned that it could be zero-based (not present if 0). I confirmed this _could_ be true by checking a profile with 0 drank:
> 
> ![image](https://private-user-images.githubusercontent.com/32849887/329732855-310381a3-854a-46d8-bfe4-a616a6acabda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzODYxMjEsIm5iZiI6MTcxNTM4NTgyMSwicGF0aCI6Ii8zMjg0OTg4Ny8zMjk3MzI4NTUtMzEwMzgxYTMtODU0YS00NmQ4LWJmZTQtYTYxNmE2YWNhYmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAwMDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YmQ1OWE4MWE1NjcxMjdiZDVkNjAwYzVkNjNiNGQ2YzNhZjJjMjVjMmY1MWNmNjRiMmYzOWZjYWJmODgxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2vbFlkT75ZjzCPsXsIi4aV5bIw6HLnXDyct9aty5ymM)
> 
> If this is the case, it would be great to simply know this.

Upon checking my own profile where I've only consumed one, it seems as though the API reports `1` for me so it can't be zero-based.
![image](https://github.com/HypixelDev/PublicAPI/assets/51387595/f5b87f8f-d584-481d-8eea-557828584e1a)
<img width="637" alt="image" src="https://github.com/HypixelDev/PublicAPI/assets/51387595/638abb39-7745-49e9-9b3c-ec8dc768e7f3">

**Comment by ConnorLinfoot** [comment]
The data under leveling appears to be incorrect due to it using another field for the underlying task implementation, we've added the field that the task uses to the API as `winter_player_data.refined_jyrre_uses` which should be correct.

Once possible, the old field will be removed accordingly, but this requires changes to the game first.

**Comment by MattTheCuber** [comment]
Amazing! Thank you very much!
