### ISSUE TITLE
Wrong `claimed_medal` value in some Finnegan Boosted Jacob Contests

### ISSUE THREAD

**Issue by ptlthg** [HypixelDev/PublicAPI#643]
I created contest viewing pages on my website for players to see how they compared to others in a Jacob contest, as a result you can easily view lists of participations and earned medals, which has lead to people discovering some anomalies during Finnegan Boosted Jacob contests.

Here's one example reported to me today:

User UUID: 627090444c9f4cd4a522739be3d10c28
Profile UUID: ee653cb9c305473db265f15265cc00e4

In Game:
![image](https://github.com/HypixelDev/PublicAPI/assets/24925519/9c8fb5e2-0bda-4afb-b7cf-257707e18b9a)
API Response:
![image](https://github.com/HypixelDev/PublicAPI/assets/24925519/918543e0-6974-4f5d-9bec-b75b0b99438b)
My website (because the API response is wrong):
![image](https://github.com/HypixelDev/PublicAPI/assets/24925519/4f23246f-d29e-4946-a764-ca5461d3f258)

My code implementation uses the `claimed_medal` value **always**, so all Finnegan boosted contests on my site are directly using the value from Hypixel's API. (Also I don't scrape data to fill these leaderboards, they're just collected as people's stats are looked up, you can view my implementation on my [Repo](https://github.com/EliteFarmers/API/blob/1cd6d5cc72f77f29c2672869b684b03add6db53e/EliteAPI/Parsers/Profiles/JacobContestParser.cs#L149)).

You can look through my contest leaderboard ([link to the one shown above](https://elitebot.dev/contests/351/12/18)) for more examples of this bug. It's actually very common, with around 5 wrong medals per contest. 

I can't really guess as to how this is happening, sorry. But it would be great if this could be fixed, as people keep reporting it as a bug to me.

**Comment by ptlthg** [comment]
Here's an even worse example, **someone got first place in this contest and only received a gold medal**:

Player UUID: 20d8721697984377b7f745577a727fa1
Profile UUID: 20d8721697984377b7f745577a727fa1

Hypixel API Response:
![image](https://github.com/HypixelDev/PublicAPI/assets/24925519/dee3dc26-0783-4e40-9c96-19f02ab0a8e5)

You can see way more examples on [my page for that contest too](https://elitebot.dev/contests/295/1/2)

**Comment by ConnorLinfoot** [comment]
The data the API provides for this is what is in the game, if you believe this data is incorrect you would have to report it as a bug [here](https://hypixel.net/bug-reports/create) as it's not an issue with the Public API itself.

**Comment by ptlthg** [comment]
> The data the API provides for this is what is in the game

I reported it here because the in game screenshot shows a diamond medal being claimed, while the API says platinum, so I wasn't sure where this error is occurring. I've opened a bug report that you should be able to see [here](https://hypixel.net/threads/5675855/), thanks for the quick reply.
