### ISSUE TITLE
Missing skill level data for Angel and Dragon classes in WALLS3

### ISSUE THREAD

**Issue by louisktari** [HypixelDev/PublicAPI#649]
I have identified an issue with the Hypixel public API regarding the retrieval of class data nested within `player.stats.Walls3.classes`. Specifically, the Angel and Dragon class objects are missing several expected fields, including skill levels and other related attributes. Here is a comparison of the JSON data retrieved for different classes:

```
{
  "renegade": {
    "unlocked": true,
    "skill_level_d": 5,
    "skill_level_a": 5,
    "enderchest_rows": 5,
    "skill_level_c": 3,
    "skill_level_b": 3,
    "skill_level_g": 3
  },
  "sheep": {
    "unlocked": true,
    "skill_level_d": 5,
    "skill_level_a": 5,
    "skill_level_b": 3,
    "skill_level_c": 3,
    "skill_level_g": 3,
    "enderchest_rows": 5
  },
  "angel": {
    "unlocked": true,
    "enderchest_rows": 5
  },
  "dragon": {
    "unlocked": true,
    "enderchest_rows": 5
  }
}
```

As shown, the Angel and Dragon classes are missing skill level attributes (e.g., `skill_level_d`, `skill_level_a`, etc.) that are present in other classes like renegade and sheep.

**Steps to Reproduce:**
Make a request to the Hypixel API to retrieve class data.
Observe the JSON response, noting the missing skill level fields for angel and dragon classes.

**Expected Behavior:**
All class objects should include consistent fields, including skill levels and other relevant attributes.

**Actual Behavior:**
The Angel and Dragon class objects are missing multiple fields that are present in other class objects.

**Comment by ConnorLinfoot** [comment]
All the fields that are tracked in the player data are available in the API, the API provides the data stored within the database and we don't exclude anything for Mega Walls. I don't believe Myhic classes have skill levels.

**Comment by Picsou993** [comment]
I can confirm that the data is missing too. Mythical classes have levels too.
For my data (UUID: `c30ef18f85a6492b8ad6d3df445c4575`), I do have the Renegade Skills in the API:
![image](https://github.com/HypixelDev/PublicAPI/assets/33390780/99b3f9fc-195a-4078-af10-bdfd0161e822)
As well as in game:
![image](https://github.com/HypixelDev/PublicAPI/assets/33390780/d50d59f7-808c-41c4-b696-4410cdf03d87)

However for the Dragon Class, I do have some skills leveled in game:
![image](https://github.com/HypixelDev/PublicAPI/assets/33390780/a569ce38-0295-4da6-8543-29677821f709)
But they are not in the API:
![image](https://github.com/HypixelDev/PublicAPI/assets/33390780/41450afa-0510-492c-92eb-3b7c9a0addd1)

PS: I did a comparison on my whole player data and it does not show anywhere. Could it be stored somewhere else not in the player data or in a filtered field?

**Comment by PlayfulPiano** [comment]
> All the fields that are tracked in the player data are available in the API, the API provides the data stored within the database and we don't exclude anything for Mega Walls. I don't believe Myhic classes have skill levels.

quickly want to reply that all classes including mythics do have skill levels. for mythics they are based on either class point totals for that mythic or via using the mythic favor currency to max a specific skill without needing the requirement.
