### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by Jestemkioskiem** [HypixelDev/PublicAPI#65]
Hey. I work for utopian.io, a platform that rewards people that contribute for Open Source projects. There have been a few people trying to contribute to your project, but you don't have an open source license, so we had to reject these. Furthermore, you even have a copyright on this one. Can you comment on the state of this project? Is it OpenSource or not? Thank you.

**Comment by original-codematrix** [comment]
@Plancke @ConnorLinfoot Does this have relevance?

**Comment by puppy0cam** [comment]
I would say it's unlikely to be relevant considering this repository's main purpose is to document the API.

**Comment by Semx11** [comment]
The site utopian.io doesn't exist anymore either. Dead link. Seems like this can be closed?

**Comment by puppy0cam** [comment]
In any case, I don't think that it's particularly relevant for us, and is probably better for whoever is in charge or legal matters at Hypixel. It is worth noting that the only other public repository on the HypixelDev organisation uses the MIT license - https://github.com/HypixelDev/ResourcePackConverter/blob/master/LICENSE
