### ISSUE TITLE
SkyBlock's Items Resource is missing 364 Items

### ISSUE THREAD

**Issue by ic22487** [HypixelDev/PublicAPI#650]
SkyBlock's Items Resource is missing 364 Items that are obtainable and fully released to the public.
Here is a list of said items.

### ABIPHONES
ABIPHONE_FLIP_DRAGON
ABIPHONE_FLIP_NUCLEUS
ABIPHONE_FLIP_VOLCANO

### RIFT
GLYPH_CONCLAMATUS
GLYPH_FIRMITAS
GLYPH_FORTIS
GLYPH_PERNIMIUS
GLYPH_POTENTIA
GLYPH_ROBUR
GLYPH_VALIDUS
GLYPH_VIS
RIFT_TROPHY_CHICKEN_N_EGG
RIFT_TROPHY_CITIZEN
RIFT_TROPHY_LAZY_LIVING
RIFT_TROPHY_MIRRORED
RIFT_TROPHY_SLIME
RIFT_TROPHY_VAMPIRIC
RIFT_TROPHY_WYLDLY_SUPREME

### KUUDRA FOLLOWER HUNT
HERRING_THE_FISH
KUUDRA_CAVITY
KUUDRA_FOLLOWER_BOOTS
KUUDRA_FOLLOWER_CHESTPLATE
KUUDRA_FOLLOWER_HELMET
KUUDRA_FOLLOWER_LEGGINGS
KUUDRA_RELIC
WET_NAPKIN

### CRIMSON ISLE
INFERNO_FUEL_BLAZE_ROD
INFERNO_FUEL_CRUDE_GABAGOOL
INFERNO_FUEL_GLOWSTONE_DUST
INFERNO_FUEL_MAGMA_CREAM
INFERNO_FUEL_NETHER_STALK
INFERNO_HEAVY_BLAZE_ROD
INFERNO_HEAVY_CRUDE_GABAGOOL
INFERNO_HEAVY_GLOWSTONE_DUST
INFERNO_HEAVY_MAGMA_CREAM
INFERNO_HEAVY_NETHER_STALK
INFERNO_HYPERGOLIC_BLAZE_ROD
INFERNO_HYPERGOLIC_CRUDE_GABAGOOL
INFERNO_HYPERGOLIC_GLOWSTONE_DUST
INFERNO_HYPERGOLIC_MAGMA_CREAM
INFERNO_HYPERGOLIC_NETHER_STALK
KUUDRA_BURNING_TIER_KEY
KUUDRA_FIERY_TIER_KEY
KUUDRA_HOT_TIER_KEY
KUUDRA_INFERNAL_TIER_KEY
KUUDRA_TIER_KEY

### PET ITEMS
BEJEWELED_COLLAR
GREEN_BANDANA
UNCOMMON_PARTY_HAT
YELLOW_BANDANA

### BINGO
BINGHOE
BINGO_BOOSTER
BINGO_COMBAT_TALISMAN
BINGO_LAVA_ROD
BINGOLIBUR
BINGONIMBUS_2000

### TROPHY FISH
BLOBFISH_BRONZE
BLOBFISH_DIAMOND
BLOBFISH_GOLD
BLOBFISH_SILVER
FLYFISH_BRONZE
FLYFISH_DIAMOND
FLYFISH_GOLD
FLYFISH_SILVER
GOLDEN_FISH_BRONZE
GOLDEN_FISH_DIAMOND
GOLDEN_FISH_GOLD
GOLDEN_FISH_SILVER
GUSHER_BRONZE
GUSHER_DIAMOND
GUSHER_GOLD
GUSHER_SILVER
KARATE_FISH_BRONZE
KARATE_FISH_DIAMOND
KARATE_FISH_GOLD
KARATE_FISH_SILVER
LAVA_HORSE_BRONZE
LAVA_HORSE_DIAMOND
LAVA_HORSE_GOLD
LAVA_HORSE_SILVER
MANA_RAY_BRONZE
MANA_RAY_DIAMOND
MANA_RAY_GOLD
MANA_RAY_SILVER
MOLDFIN_BRONZE
MOLDFIN_DIAMOND
MOLDFIN_GOLD
MOLDFIN_SILVER
OBFUSCATED_FISH_1_BRONZE
OBFUSCATED_FISH_1_DIAMOND
OBFUSCATED_FISH_1_GOLD
OBFUSCATED_FISH_1_SILVER
OBFUSCATED_FISH_2_BRONZE
OBFUSCATED_FISH_2_DIAMOND
OBFUSCATED_FISH_2_GOLD
OBFUSCATED_FISH_2_SILVER
OBFUSCATED_FISH_3_BRONZE
OBFUSCATED_FISH_3_DIAMOND
OBFUSCATED_FISH_3_GOLD
OBFUSCATED_FISH_3_SILVER
SKELETON_FISH_BRONZE
SKELETON_FISH_DIAMOND
SKELETON_FISH_GOLD
SKELETON_FISH_SILVER
SLUGFISH_BRONZE
SLUGFISH_DIAMOND
SLUGFISH_GOLD
SLUGFISH_SILVER
SOUL_FISH_BRONZE
SOUL_FISH_DIAMOND
SOUL_FISH_GOLD
SOUL_FISH_SILVER
STEAMING_HOT_FLOUNDER_BRONZE
STEAMING_HOT_FLOUNDER_DIAMOND
STEAMING_HOT_FLOUNDER_GOLD
STEAMING_HOT_FLOUNDER_SILVER
SULPHUR_SKITTER_BRONZE
SULPHUR_SKITTER_DIAMOND
SULPHUR_SKITTER_GOLD
SULPHUR_SKITTER_SILVER
VANILLE_BRONZE
VANILLE_DIAMOND
VANILLE_GOLD
VANILLE_SILVER
VOLCANIC_STONEFISH_BRONZE
VOLCANIC_STONEFISH_DIAMOND
VOLCANIC_STONEFISH_GOLD
VOLCANIC_STONEFISH_SILVER

### BARN SKINS
END_BARN_SKIN
BEACH_BALL_BARN_SKIN

### POWER ORB SKINS
GLOWING_GRAPE_FLUX
GOLDEN_APPLE_FLUX
GLISTENING_MELON_FLUX
PIRATE_BOMB_FLUX
GOLDEN_ANCIENT_EGG_FLUX
MAGIC_CUBE_FLUX
BEACH_BALL_FLUX
POLAR_LIGHTS_FLUX
CHERRY_BLOSSOM_FLUX

### HELMET SKINS
FROZEN_BLAZE_FROST_KNIGHT
BERSERKER_SANDSTORM_CAT
FERMENTO_ULTIMATE
GOBLIN_HELMET_GENIE
GOBLIN_HELMET_THIEF
GOBLIN_HELMET_BABY
GOBLIN_HELMET_DIAMOND
GOBLIN_HELMET_GOLDEN
SENTINEL_WARDEN
CADUCEUS_MENDING_CROWN
TARANTULA_REDBACK
FINAL_DESTINATION_ENDER_KNIGHT
GEMSTONE_DIVAN
METEOR_MAGMA_LORD
FERMENTO_LEAF
FERMENTO_BLOOM
SHADOW_ASSASSIN_SLY_FOX
GOLDOR_CELESTIAL
STORM_CELESTIAL
MAXOR_CELESTIAL
NECRON_CELESTIAL
TRUE_WARDEN
WITHER_GOGGLES_CYBERPUNK
WITHER_GOGGLES_CELESTIAL
LUNAR_RABBIT_HAT
BONZO_MASK_JESTER
PANDA_SPIRIT
REKINDLED_EMBER_BURNING
WATER_HYDRA_BABY
BAT_PERSON_HERO
FROZEN_BLAZE_ICEBERG
ANGLER_DEEP_SEA
STARLIGHT_STARKNIGHT
RABBIT_JERRY_ONESIE

### BACKPACK SKINS
AWAKENED_EYE_BACKPACK
BABYSEAL_BACKPACK
BAG_OF_COAL_BACKPACK
CHRISTMAS_STOCKING_BACKPACK
DRAGON_EGG_BACKPACK
DYE_LUCKY
GIFT_BLACK_BACKPACK
GIFT_BLUE_BACKPACK
GIFT_GOLD_BACKPACK
GIFT_GREEN_BACKPACK
GIFT_PURPLE_BACKPACK
GIFT_WHITE_BACKPACK
HAMBAGGER_BACKPACK
NORTH_STAR_BACKPACK
PENGUIN_BACKPACK
REINDEER_BACKPACK

### PET SKINS
PET_SKIN_AMMONITE_NATURAL
PET_SKIN_AMMONITE_MAGMA
PET_SKIN_ARMADILLO_ENCHANTED
PET_SKIN_ARMADILLO_SEAFOAM
PET_SKIN_BABY_YETI_DARK_SASQUATCH
PET_SKIN_BABY_YETI_LIGHT_SASQUATCH
PET_SKIN_BABY_YETI_MIDNIGHT
PET_SKIN_BABY_YETI_PLUSHIE
PET_SKIN_BAL_INFERNO
PET_SKIN_BAT_BONE
PET_SKIN_BAT_CANDY
PET_SKIN_BAT_VAMPIRE
PET_SKIN_BEE_BEEDAZZLED
PET_SKIN_BEE_BEELOVED
PET_SKIN_BEE_GREAT_GATSBEE
PET_SKIN_BEE_HIVE
PET_SKIN_BEE_HONEY
PET_SKIN_BEE_RGBEE
PET_SKIN_BEE_RUGBEE
PET_SKIN_BEE_SPELLING_BEE
PET_SKIN_BEE_USB
PET_SKIN_BEE_WANNA_BEE
PET_SKIN_BEE_WASABEE
PET_SKIN_BEE_ZOMBEE
PET_SKIN_BLACK_CAT_PURRANORMAL
PET_SKIN_BLAZE_FROZEN
PET_SKIN_BLAZE_PLUSHIE
PET_SKIN_BLUE_WHALE_PLUSHIE
PET_SKIN_CAT_SPACE_KITTY
PET_SKIN_CHICKEN_LUNAR_ROOSTER
PET_SKIN_CHICKEN_NESTED
PET_SKIN_CHICKEN_RUBBER
PET_SKIN_CHICKEN_TURKEY
PET_SKIN_DOLPHIN_LUNAR_HORSE
PET_SKIN_DOLPHIN_SNUBFIN
PET_SKIN_DOLPHIN_SNUBNOSE_GREEN
PET_SKIN_DOLPHIN_SNUBNOSE_PURPLE
PET_SKIN_DOLPHIN_SNUBNOSE_RED
PET_SKIN_ELEPHANT_BLACK_PLUSHIE
PET_SKIN_ELEPHANT_BLUE_PLUSHIE
PET_SKIN_ELEPHANT_COSMIC
PET_SKIN_ELEPHANT_GRAY_PLUSHIE
PET_SKIN_ELEPHANT_PINK_PLUSHIE
PET_SKIN_ENDER_DRAGON_BABY
PET_SKIN_ENDER_DRAGON_BABY_BLUE
PET_SKIN_ENDER_DRAGON_LUNAR
PET_SKIN_ENDER_DRAGON_UNDEAD
PET_SKIN_ENDERMAN_BLUE_MOON
PET_SKIN_ENDERMAN_NEBULA
PET_SKIN_ENDERMAN_NEON
PET_SKIN_ENDERMAN_SUN
PET_SKIN_ENDERMAN_XENON
PET_SKIN_ENDERMITE_DYNAMITE
PET_SKIN_FLYING_FISH_HARLEQUIN
PET_SKIN_FOUR_SEASONS_GRIFFIN
PET_SKIN_GIRAFFE_SAFARI
PET_SKIN_GLACITE_GOLEM_CAVERN
PET_SKIN_GOLDEN_DRAGON_ANCIENT
PET_SKIN_GOLDEN_DRAGON_ANCIENT
PET_SKIN_GOLDEN_DRAGON_ANUBIS
PET_SKIN_GOLDEN_DRAGON_ANUBIS
PET_SKIN_GOLEM_END
PET_SKIN_GRANDMA_WOLF_REAL
PET_SKIN_GRIFFIN_PEAFOWL
PET_SKIN_GRIFFIN_REINDRAKE
PET_SKIN_HOUND_BEAGLE
PET_SKIN_HOUND_LUNAR
PET_SKIN_JELLYFISH_LUMINESCENT
PET_SKIN_JERRY_FROZEN
PET_SKIN_JERRY_HANDSOME
PET_SKIN_JERRY_KING
PET_SKIN_JERRY_LEPRECHAUN
PET_SKIN_KUUDRA_LOYALTY
PET_SKIN_LION_HEART
PET_SKIN_MAGMA_CUBE_CHOCO_CUBE
PET_SKIN_MITHRIL_GOLEM_CHERRY_BLOSSOM
PET_SKIN_MITHRIL_GOLEM_COPPER
PET_SKIN_MITHRIL_GOLEM_CRYSTAL
PET_SKIN_MOLE_MINER
PET_SKIN_MONKEY_ASTRONAUT
PET_SKIN_MONKEY_LEMUR
PET_SKIN_MONKEY_LUNAR
PET_SKIN_MONKEY_SEE_HEAR_SPEAK
PET_SKIN_MOOSHROOM_COW_LUNAR_OX
PET_SKIN_MOOSHROOM_COW_MOOCELIUM
PET_SKIN_OCELOT_JUNGLE
PET_SKIN_OCELOT_SNOW_TIGER
PET_SKIN_PARROT_BUCCANEER
PET_SKIN_PARROT_GOLD_MACAW
PET_SKIN_PARROT_TOUCAN
PET_SKIN_PHEONIX_FLAMINGO
PET_SKIN_PHOENIX_ICE
PET_SKIN_PIGMAN_LUNAR_PIG
PET_SKIN_RABBIT_LUNAR
PET_SKIN_RABBIT_LUNAR_BABY
PET_SKIN_RABBIT_PLUSHIE
PET_SKIN_RAT_GYM_RAT
PET_SKIN_RAT_HIDE_AND_SQUEAK
PET_SKIN_RAT_JUNK_RAT
PET_SKIN_RAT_KARATE
PET_SKIN_RAT_LUNAR
PET_SKIN_RAT_MR_CLAWS
PET_SKIN_RAT_NINJA
PET_SKIN_RAT_PIRATE
PET_SKIN_RAT_RAT-STRONAUT
PET_SKIN_RAT_SECRAT_SERVICE
PET_SKIN_RAT_SECURATY_GUARD
PET_SKIN_RAT_SQUEAKHEART
PET_SKIN_REINDEER_AURORA
PET_SKIN_REINDEER_PLUSHIE
PET_SKIN_ROCK_BLINKING
PET_SKIN_ROCK_NORTH_STAR
PET_SKIN_ROCK_SURPRISED
PET_SKIN_ROCK_SUS
PET_SKIN_ROCK_SWEATING
PET_SKIN_SCATHA_ALBINO
PET_SKIN_SCATHA_DARK
PET_SKIN_SCATHA_GOLDEN
PET_SKIN_SCATHA_LUNAR_SNAKE
PET_SKIN_SHEEP_BLACK_CHROMATIC_CRUSH
PET_SKIN_SHEEP_BLACK_WOOLY
PET_SKIN_SHEEP_BLUE_CRUSH
PET_SKIN_SHEEP_CHROMA_WOOLY
PET_SKIN_SHEEP_LUNAR_GOAT
PET_SKIN_SHEEP_PINK_CRUSH
PET_SKIN_SHEEP_PURPLE_CRUSHED
PET_SKIN_SHEEP_WHITE_WOOLY
PET_SKIN_SLUG_AZURE_SEA_SLUG
PET_SKIN_SLUG_LEAF_SHEEP_SEA_SLUG
PET_SKIN_SLUG_VIOLET_SEA_SLUG
PET_SKIN_SNAIL_RAINBOW
PET_SKIN_SNOW_OWL
PET_SKIN_SNOWBALL_SPIRIT
PET_SKIN_SNOWMAN_ICE_GOLEM
PET_SKIN_SNOWMAN_PLUSHIE
PET_SKIN_SPIDER_BLACK_WIDOW
PET_SKIN_SPIDER_PEACOCK
PET_SKIN_SQUID_CHROMARI
PET_SKIN_SQUID_GLOW
PET_SKIN_TARANTULA_GREENBOTTLE
PET_SKIN_TARANTULA_PINK
PET_SKIN_TIGER_GOLDEN
PET_SKIN_TIGER_LUNAR
PET_SKIN_TIGER_NEON
PET_SKIN_TIGER_SABER_TOOTH
PET_SKIN_TURTLE_ANCIENT
PET_SKIN_TURTLE_ANCIENT_GOLDEN
PET_SKIN_WHALE_COSMIC
PET_SKIN_WOLF_DOGE
PET_SKIN_WOLF_DOGE_PLUSHIE
PET_SKIN_WOLF_HUSKY
PET_SKIN_ZOMBIE_BIG_BRAIN
PET_SKIN_ZOMBIE_BRAIN_FREEZE
PET_SKIN_ZOMBIE_SENTINEL

### GREAT SPOOK ITEMS
ALCHEMIST_RECIPE
BOO_STONE
DEAD_SEED
DWARVEN_IRON_HAMMER
EERIE_TOY
EERIE_TREAT
EPHEMERAL_GRATITUDE
FAIRY_WINGS
FREE_SPIDER
FRENCH_FRIES
FROZEN_SPIDER
GREAT_SPOOK_POTION
GREAT_SPOOK_REFORGING_MANUAL
OBSCURE_ENDING
PRECIOUS
ROGUE_FLESH
SCARY_GRIMOIRE
SIRIUS_BOOK
SLEEPY_HOLLOW
THE_SOUP_PAINTING
SPOOKY_TREE

### "VANILLA" ITEMS
(People have obtained these items through glitches, I have not included them in the total but figured I'd list them here anyway)
CARROTS
COCOA_PLANT
POTATOES
STILL_LAVA
STILL_WATER

**Comment by ConnorLinfoot** [comment]
Some items aren't defined or are hidden from the API by choice, we don't guarantee the existence of items
