### ISSUE TITLE
MegaWalls Monthly / Weekly Leaderboard Missing in API

### ISSUE THREAD

**Issue by merry-git** [HypixelDev/PublicAPI#651]
Hi,

I was wondering if this was intentional, but with the new megawalls update I was wondering why the Weekly Final kills / Monthly Final Kill leaderboard is not present in the leaderboards API? It would be useful to be able to implement this into quality of life discord bots so I can view monthly leaderboards without going in game.

I'm not asking to add each class to the leaderboard, but a general final kills / wins leaderboard for monthly (maybe weekly) would be great!

For reference:
I'm hitting this endpoint: `https://api.hypixel.net/v2/leaderboards`

And the `WALLS3` key only has:

```
"WALLS3": [
            {
                "path": "finalKills",
                "prefix": "Overall",
                "title": "Final Kills",
                "location": "-2554,54,712",
                "count": 99,
                "leaders": [
                    "f01736f9-4059-4585-895c-342c5f087464",
                    "599ec515-b661-4f70-a509-e50fb07fdc4a",
                    "024c5b04-f2ea-4a09-ab1c-1a1995a359f0",
                    "0fd143aa-5e00-48bc-a73d-baea0d9962fb",
                    "56bc9e11-fd61-4c87-9e35-43e388bdf1f1",
                    "3f420e5b-86c9-4512-bc97-2581d4504738",
                    "b5b77b82-b869-4823-82f9-bf9976df4f65",
                    "516a25ca-08f9-4d30-ac4e-ca842ce0d661",
                    "8b5bacc5-04d0-43d7-ba3a-c08d01613a64",
 ```
 
 While (I havent confirmed) every other game has at least one `prefix: monthly`.

**Comment by louisktari** [comment]
@ConnorLinfoot Could we expect any official update on this? Additionally, you closed my previous issue a few months ago regarding the new Mythic classes not having upgrades visible in the API, when in fact they should? https://github.com/HypixelDev/PublicAPI/issues/649

Thanks again, and appreciate your time.



Thanks!

**Comment by Alexdoru** [comment]
Yes please, the current leaderboard entry for mega walls is completely useless it only returns the 100 players with most final kills and the data isn't even accurate, some players are missing while others are banned and shouldn't appear on the leaderboard.

It would be nice to have :

- All time Final kills : 100 players
- All time Wins : 100 players
- All time Class Points : 100 players
- Monthly Final kills : 100 players
- Monthly Wins : 100 players
- Monthly Class Points : 100 players
- Weekly Final kills : 100 players
- Weekly Wins : 100 players
- Weekly Class Points : 100 players

If you think that's too much you can reduce the weekly and monthly leaderboards to  25 or 50 players.

Thanks!

**Comment by Clemintina** [comment]
> Yes please, the current leaderboard entry for mega walls is completely useless it only returns the 100 players with most final kills and the data isn't even accurate, some players are missing while others are banned and shouldn't appear on the leaderboard.
> 
> 
> 
> It would be nice to have :
> 
> 
> 
> - All time Final kills : 100 players
> 
> - All time Wins : 100 players
> 
> - All time Class Points : 100 players
> 
> - Monthly Final kills : 100 players
> 
> - Monthly Wins : 100 players
> 
> - Monthly Class Points : 100 players
> 
> - Weekly Final kills : 100 players
> 
> - Weekly Wins : 100 players
> 
> - Weekly Class Points : 100 players
> 
> 
> 
> If you think that's too much you can reduce the weekly and monthly leaderboards to  25 or 50 players.
> 
> 
> 
> Thanks!
> 
> 

 By design, the public Hypixel API doesn't remove banned players from leaderboards to my knowledge. Bans are considered private. Missing players is probably just them not logging into the server after an update (not populating it themselves) which effects leaderboard positions.

**Comment by louisktari** [comment]
> > Yes please, the current leaderboard entry for mega walls is completely useless it only returns the 100 players with most final kills and the data isn't even accurate, some players are missing while others are banned and shouldn't appear on the leaderboard.
> > It would be nice to have :
> > 
> > * All time Final kills : 100 players
> > * All time Wins : 100 players
> > * All time Class Points : 100 players
> > * Monthly Final kills : 100 players
> > * Monthly Wins : 100 players
> > * Monthly Class Points : 100 players
> > * Weekly Final kills : 100 players
> > * Weekly Wins : 100 players
> > * Weekly Class Points : 100 players
> > 
> > If you think that's too much you can reduce the weekly and monthly leaderboards to  25 or 50 players.
> > Thanks!
> 
> By design, the public Hypixel API doesn't remove banned players from leaderboards to my knowledge. Bans are considered private. Missing players is probably just them not logging into the server after an update (not populating it themselves) which effects leaderboard positions.

Banned players are removed from leaderboards on the API and in-game. This has been the case for a long time. Additionally I would like to second what Alex has said, given this information is already available in-game through the holographic leaderboards it seems trivial to make this available in the Public API, as it is for "newer" games.

**Comment by Alexdoru** [comment]
> By design, the public Hypixel API doesn't remove banned players from leaderboards to my knowledge. Bans are considered private. Missing players is probably just them not logging into the server after an update (not populating it themselves) which effects leaderboard positions.

First of all the bans aren't "private" when someone gets banned, they are removed from the in game leaderboards as well as the website leaderboards : https://hypixel.net/megawalls/leaderboard

Secondly that's besides the point, the point is this api endpoint has been returning the exact same 100 players for the past 4 years, and it doesn't not reflect the reality of the current leaderboards at all. 

On top of that it would be nice to have it return more information than just the 100 players will most fnial kills all time.

**Comment by ConnorLinfoot** [comment]
I have updated the final kills leaderboard to the correct key, and added the other overall leaderboards including monthly/weekly.

**Comment by Alexdoru** [comment]
Thank you Connor!

**Comment by Conncrs** [comment]
Great work fellow Connor bringing the name pride

**Comment by merry-git** [comment]
Thanks for closing the loop. Much appreciated
