### ISSUE TITLE
Housing - createdAt is 0

### ISSUE THREAD

**Issue by NoahTheNerd** [HypixelDev/PublicAPI#654]
Not to be a nerd, but I don't think Housing existed on January 1st, 1970.
Might be a weird edge case or that the house is so recent it hasn't made a creation date yet? Weird old edge case? No clue.

![image](https://github.com/user-attachments/assets/0a263573-92f0-48b4-865e-acc5e9a21039)

**Comment by Picsou993** [comment]
This 0 value is for houses created before the [1.0 Housing Update](https://hypixel.net/threads/housing-update-multiple-houses-new-lobby-new-themes-more.2670345/).
After this update, it has been possible to get multiple houses and all new houses have been created on the new storage system, while other just got migrated to it.
As far as I have seen, it seems that only legacy houses are impacted by this as the createdAt was probably not stored prior the update.

PS: You can easily identify which houses are legacy or not by checking if the housing uuid is the same as the owner uuid or not.

**Comment by NoahTheNerd** [comment]
Aha, interesting. Would personally prefer to have it just say the date is something like the day before the 1.0 release but I can just easily implement a case into my code to replace 0 with that. Thanks!

**Comment by ConnorLinfoot** [comment]
Yeah, it's correct that houses without a created time are ones created before being tracked with the March 2020 update. It makes more sense to return it as a zero and allow developers to deal with it how they see fit, rather than essentially faking a date which will also lead to confusion.
