### ISSUE TITLE
Missing significant amount of  Game Types 

### ISSUE THREAD

**Issue by stuffyerface** [HypixelDev/PublicAPI#658]
The games resources endpoint (/v2/resources/games) is missing a significant amount of data under "modeNames" per game. 

```py
{('WALLS3', 'standard'), ('MCGO', 'deathmatch_party'), ('SUPER_SMASH', '2v2_normal'), ('HOUSING', 'HOUSING'), ('UHC', 'TEAMS'), ('UHC', 'SOLO'), ('ARCADE', 'HOLE_IN_THE_WALL'), ('MCGO', 'normal_party'), ('VAMPIREZ', 'VAMPIREZ'), ('SPEED_UHC', 'team_normal'), ('MCGO', 'normal'), ('SUPER_SMASH', '1v1_normal'), ('ARCADE', 'THROW_OUT'), ('SUPER_SMASH', 'teams_normal'), ('SUPER_SMASH', 'friends_normal'), ('SURVIVAL_GAMES', 'solo_normal'), ('GINGERBREAD', 'normal'), ('ARCADE', 'HIDE_AND_SEEK_PROP_HUNT'), ('SKYBLOCK', 'SKYBLOCK'), ('SPEED_UHC', 'solo_normal'), ('ARCADE', 'ZOMBIES_DEAD_END'), ('WALLS', 'WALLS'), ('ARCADE', 'EASTER_SIMULATOR'), ('PAINTBALL', 'PAINTBALL'), ('ARENA', '1v1'), ('ARCADE', 'DEFENDER'), ('ARCADE', 'HIDE_AND_SEEK_PARTY_POOPER'), ('ARCADE', 'MINI_WALLS'), ('REPLAY', 'BASE'), ('ARCADE', 'FARM_HUNT'), ('SKYCLASH', None), ('ARCADE', 'SCUBA_SIMULATOR'), ('TRUE_COMBAT', None), ('MCGO', 'deathmatch'), ('PIT', 'PIT'), ('SURVIVAL_GAMES', 'teams_normal'), ('ARCADE', 'ZOMBIES_PRISON'), ('LEGACY', None), ('WOOL_GAMES', 'wool_wool_wars_two_four'), ('ARCADE', 'ZOMBIES_ALIEN_ARCADIUM'), ('WALLS3', 'face_off'), ('ARCADE', 'HALLOWEEN_SIMULATOR'), ('ARCADE', 'PIXEL_PARTY'), ('SMP', 'SMP'), ('ARENA', '2v2'), ('ARCADE', 'DROPPER'), ('ARENA', '4v4'), ('ARCADE', 'ZOMBIES_BAD_BLOOD'), ('SUPER_SMASH', 'solo_normal')}
```

This is most, but not all of what is missing. Data generated from the `/locraw` command in game, Game IDs may not align directly with backend resources, but can be mapped.

For community sourced data on a more complete list of gameTypes, see https://raw.githubusercontent.com/stuffybot/PublicAPI/main/apis/playcommands.json

Notably this is also missing some, but not all tournament gamemodes (not included in the list). (Resources only include `wool_wars_two_four_tourney` in `QUAKECRAFT` and `solo_tourney` in `WOOL_GAMES`

**Comment by ConnorLinfoot** [comment]
The games endpoint isn't guaranteed to contain all modes, they are defined as needed internally, especially for modes that have no difference from a clean name vs their key.
