### ISSUE TITLE
Objects not of type String found in "achievementsOneTime"

### ISSUE THREAD

**Issue by stuffyerface** [HypixelDev/PublicAPI#659]
via the player endpoint (/v2/player), users data may contain objects of the incorrect type, specifically, `achievementsOneTime` field should be of type String[] (only containing strings), but it can contain arrays?

Found in the following cases
uuid: 386258427e6a4b4980ac32d12df89791
![image](https://github.com/user-attachments/assets/6b518b7a-bb8c-46f8-86a9-ef83345432cc)

**Comment by ConnorLinfoot** [comment]
I have removed the array from this user. Still, it's worth being aware that data provided via endpoints such as the player data endpoint are from the database, and we cannot guarantee the types of objects contained within.
