### ISSUE TITLE
Turkish Traslation

### ISSUE THREAD

**Issue by halokaya67** [HypixelDev/PublicAPI#66]
I want to help this project by translating it into turkish. I'm turkish and 25 years old. I'm working as an english teacher in a school. I think i can help. Please just show me which file should i translate and you will see. You won't regret because i take my job serious.

**Comment by ninja-** [comment]
Hello, you can see progress on Turkish translation here - it's at 58% .
https://crowdin.com/project/hypixel/tr#
See here for instructions on how to join translations team - your application would need to be accepted before you can send translations - https://hypixel.net/threads/guide-how-to-help-translate-hypixel.800941/#post-7078195
😃
