### ISSUE TITLE
Removed, but not legacy achievements do not appear in the /resources/achievements api.

### ISSUE THREAD

**Issue by stuffyerface** [HypixelDev/PublicAPI#660]
The player endpoint (/v2/player) contains some players who have achievements not listed in the achievement resources endpoint (/resources/achievements)

I found this by trying to find data on an old vampirez achievement (vampirez_wizard) and it was not listed. I scanned some profiles to attempt to generate a list of other achievements missing from the achievement resource endpoint.

Cursory Glance found the following 38 achievements missing from the endpoint:
```py
['bridge_on_fire', 'vampirez_herobrine_upgrade', 'bridge_express_yourself', 'blitz_chaotic_madness', 'bridge_gg', 'skywars_mega_rich', 'general_buy_golem', 'bridge_got_ya', 'arena_utility', 'copsandcrims_late_to_the_party', 'walls3_martyrdom', 'general_join_vip_lobby', 'general_email', 'bridge_one_v_one_me', 'walls3_kill_groopo', 'bridge_clean_sweep', 'bridge_heart_hoarder', 'arena_ultimate', 'bridge_community_oriented', 'vampirez_wizard', 'skywars_beast_mode', 'blitz_final_destination', 'bridge_last_stand', 'general_use_pet', 'bridge_void_archer', 'skywars_fortunate', 'skywars_disco_play', 'bridge_carried', 'bridge_jumping_to_conclusions', 'quake_death_chant', 'bridge_omg_admin', 'bridge_ninja', 'walls_canadian_kit', 'truecombat_wither_slayer', 'blitz_youtuber', 'vampirez_close_call', 'bridge_hat_trick', 'walls3_kill_with_groopo']
```

Profiles Scanned:
```txt
Stuffy
ConnorLinFoot
sfarnham
Dosket
Dctr
hypixel
anrie
oJakey
```

**Comment by ConnorLinfoot** [comment]
Some achievements are removed and no longer declared internally, or even purposefully flagged to be hidden. Checking a few of the achievements provided it is correct that they are not in the endpoint.
