### ISSUE TITLE
Skyblock Negative Total Gemstone Powder 

### ISSUE THREAD

**Issue by minhperry** [HypixelDev/PublicAPI#673]
With this oneliner
```bash
curl -H "Api-Key: MY_API_KEY_HERE" https://api.hypixel.net/v2/skyblock/profile\?profile\=95bb24bd-73f6-427d-b35c-248295674ba1 > me3.json
```
and then opening the me3.json in an editor with autoformat, then the `powder_gemstone_total` at line 13413 is always negative for some reason.

However, with another profile with WAY more powder the number are not negative: (line 12791)
```bash
curl -H "Api-Key: MY_API_KEY_HERE" https://api.hypixel.net/v2/skyblock/profile\?profile\=1dfa4e68-4f56-46d2-90df-b8193bbb1ade > floating.json
```

**Comment by ConnorLinfoot** [comment]
The API provides profile data as its stored in-game, any bugs should be reported to the game developers https://hypixel.net/bug-reports/create

**Comment by minhperry** [comment]
![image](https://github.com/user-attachments/assets/b99fd1fd-3a57-40a7-9bac-d45fa3ab2efa)

For whatever reason it has been like that the last 30min
