### ISSUE TITLE
Community upgrade monetization data inadvertently exposed in API?

### ISSUE THREAD

**Issue by lunaynx** [HypixelDev/PublicAPI#674]
I've been told that Hypixel generally prefers to refrain from exposing any monetization data in their Public API, such as things related to SkyBlock Gems, Fame Rank, etc.

I couldn't help but notice that the `/v2/skyblock/profile` endpoint exposes information about whether a player has fast-tracked a Community Shop profile upgrade, which is only possible by spending SkyBlock Gems (redactions mine, the API provides unredacted data):

```
[...]
  "profile": {
    "profile_id": "[redacted]",
    "community_upgrades": {
      "upgrade_states": [
        {
          "upgrade": "minion_slots",
          "tier": 1,
          "started_ms": [redacted],
          "started_by": "[redacted]"
          "claimed_ms": [redacted],
          "claimed_by": "[redacted]",
          "fasttracked": true
        },
[...]
```
In particular, the `fasttracked` key, but `claimed_ms` can also be used to deduce this information.

**Comment by DuckySoLucky** [comment]
this is why we can't have nice things.
