### ISSUE TITLE
Missing BuildBattle leaderboards

### ISSUE THREAD

**Issue by DidiSkywalker** [HypixelDev/PublicAPI#70]
I've noticed that the `/leaderboards` endpoint is missing Build Battle leaderboards, even though Build Battle has been a standalone game for almost a year now and - I think - should be included.
Hope you can add that.

[Here's a forum post I made about this](https://hypixel.net/threads/hypixel-api-missing-games-in-leaderboards-endpoint.1839667/)

**Comment by HookedBehemoth** [comment]
I have the same problem.

**Comment by HookedBehemoth** [comment]
Nevermind fixed it...

**Comment by DidiSkywalker** [comment]
Fixed it how?
Worst thing you can do ever is just say you fixed it without explaining your solution .-.

**Comment by DidiSkywalker** [comment]
Oh, Build Battle was actually added, that's great news!
However there appears to only be one user per leaderboard which doesn't seem quite right
![image](https://user-images.githubusercontent.com/31072807/50761726-6e217d80-126b-11e9-8b76-4a6f15cf03c7.png)

**Comment by ConnorLinfoot** [comment]
@DidiSkywalker That should be resolved now, returning 15 players similar to other leaderboards.
