### ISSUE TITLE
FRIENDS_BY_UUID & SESSION_BY_UUID improvements

### ISSUE THREAD

**Issue by Mdashl** [HypixelDev/PublicAPI#72]
https://github.com/HypixelDev/PublicAPI/blob/master/Java/src/main/java/net/hypixel/api/request/RequestParam.java

FRIENDS_BY_UUID & SESSION_BY_UUID

You should do value as string, not UUID.
For example you already have UUID without dashes. Now you need to add dashes, then your code is gonna again delete them lol

**Comment by Plancke** [comment]
Fixed
