### ISSUE TITLE
Session data is inaccurate.

### ISSUE THREAD

**Issue by LewisTehMinerz** [HypixelDev/PublicAPI#77]
![https://pantsu.review/7595ea.png](https://pantsu.review/7595ea.png)

This is my session data **when I'm not logged in to Hypixel**. This was a game I joined and left for testing, and it appears that the API completely disregards the fact that I can log out of Hypixel or leave the game, and it will still set my session data to this. What I expect is that the session data gets set to `null` after I disconnect or log out of Hypixel, as this is causing issues with my Discord RPC and my other uses for the API.

**Comment by Dance-Dog** [comment]
As a workaround, I’d recommend that those working to create online statuses with the API take a look at the actual player data and make sure that their last login value is greater than their last logout value before getting their session.

Only when you know that they’re actually online should you really try fetching session data.

**Comment by Plancke** [comment]
The session data was never meant to be used as an online checker; it's more internal data than anything. This is why we deprecated it from the Java implementation. We'll probably remove the endpoint at some point.

**Comment by LewisTehMinerz** [comment]
Sooo.. how will we figure out what game they’re playing?

________________________________

**Comment by Plancke** [comment]
There's no alternative planned for now

**Comment by AgentK20** [comment]
The reason the session data still exists is that it's feeding directly from the database that we use for players to rejoin the game that they were in. That's what a "session" is in the codebase. Try it yourself ingame, just hop out of a game and into a lobby, then disconnect from the network and reconnect and you'll be put back in that game. As far as our management systems are concerned, until you join another game or until the old game ends, you are still "playing" that game.

**Comment by LewisTehMinerz** [comment]
Is there a way to figure out if they're in a lobby, or will I just have to run /whereami every 10 seconds?

**Comment by builder-247** [comment]
> Is there a way to figure out if they're in a lobby, or will I just have to run /whereami every 10 seconds?

You could just run whereami whenever the world changes
