### ISSUE TITLE
Zumulus Data

### ISSUE THREAD

**Issue by Picsou993** [HypixelDev/PublicAPI#86]
Admin Zumulus has stats from the hypixel website (https://hypixel.net/player/Zumulus/) but the API return "player":null when we try to get his data with his name or UUID.
I'm not sure if he is the only one.

**Comment by Plancke** [comment]
Zumulus' profile is used to gather global stats for old games. We're in the process of changing that and actually do it properly this time. But as long as those stats are there his profile has been manually disabled. The same goes for the 'MasterControl' player.
