### ISSUE TITLE
Reward type is empty

### ISSUE THREAD

**Issue by xdelsy** [HypixelDev/PublicAPI#89]
The reward type of "prototype_pit_daily_kills" is empty.

![image](https://user-images.githubusercontent.com/26819429/51428771-b00dd480-1c18-11e9-9fd0-33ace88add52.png)

**Comment by mdashlw** [comment]
This issue is still relevant, @ConnorLinfoot any chance of fixing it?

**Comment by ConnorLinfoot** [comment]
This has now been fixed.
