### ISSUE TITLE
New returns in a GuildReply

### ISSUE THREAD

**Issue by RogiJAG** [HypixelDev/PublicAPI#92]
_Tags: Enhancement, Suggestion_ 
Wondering if it is possible to add more information to a GuildReply that parallels the guild update
  
Some suggestions:
- **guildExpEarned**, for each Member object in a GuildReply - found in /g member [member]
- **questTierCompleted**, by the guild at that moment in time (resets weekly) - found in /g menu or /g quest

**Comment by mdashl** [comment]
About the first one, there is `exp` field

**Comment by RogiJAG** [comment]
That is a good point. Along with calculating level, expToday could also be calculated separately.
I have updated the issue, thanks.

**Comment by ConnorLinfoot** [comment]
We previously added the exp earned per member for the last 7 days. It's not easily possible to add the tier completed though.
