### ISSUE TITLE
Bad character encoding in Achievements.json

### ISSUE THREAD

**Issue by builder-247** [HypixelDev/PublicAPI#93]
On January the 5th, https://github.com/HypixelDev/PublicAPI/commit/59b6453e428ec91508ebffa2bc03de90da75a616 caused two characters to be improperly encoded on Achievements.json.

![image](https://user-images.githubusercontent.com/14019974/53182337-f97b8600-3601-11e9-884a-a349370500c6.png)

**Comment by ConnorLinfoot** [comment]
This seems to be fixed now using the resources endpoint.
