### ISSUE TITLE
Cecer mapFeedback

### ISSUE THREAD

**Issue by Picsou993** [HypixelDev/PublicAPI#95]
Cecer has a time travelling machine and keep it for himself.

Seriously there is a field call mapFeedback in his data, and I think that we shouldn't have access to them, but if we can, the timestamp is in the future (Saturday 13 July 2019 11:52:57.589).
![API  Cecer Time Travelling Machine](https://user-images.githubusercontent.com/33390780/54725116-2aea6180-4b6e-11e9-9690-6afa06ad6fe6.JPG)

**Comment by ConnorLinfoot** [comment]
Thanks, fixed.
